export const mockLastGitCommandOutput = [
    {
        start: '2023-07-18T10: 36: 24.576188Z',
        duration_seconds: 0.027963792,
        args: [
            'git',
            '-c',
            'credential.helper=',
            '-c',
            'protocol.version=2',
            'update-ref',
            '--',
            'refs/heads/test',
            'e60c82c7e2ba3adf9970d2f3a39e37901d29d0c3',
        ],
        dir: '/Users/bolajio/.sourcegraph/repos_1/github.com/sourcegraph-testing/markdowns/.git',
        path: '/usr/bin/git',
    },
    {
        start: '2023-07-18T10: 36: 22.835691Z',
        duration_seconds: 1.737891375,
        args: [
            'git',
            '-c',
            'credential.helper=',
            '-c',
            'protocol.version=2',
            'push',
            '--force',
            'https://<REDACTED>@github.com/sourcegraph-testing/markdowns',
            'e60c82c7e2ba3adf9970d2f3a39e37901d29d0c3:refs/heads/test',
        ],
        dir: '/Users/bolajio/.sourcegraph/repos_1/github.com/sourcegraph-testing/markdowns/.git',
        path: '/usr/bin/git',
    },
    {
        start: '2023-07-18T10:31:01.272432Z',
        duration_seconds: 1.007493875,
        args: [
            'git',
            '-c',
            'credential.helper=',
            '-c',
            'protocol.version=2',
            'fetch',
            '--progress',
            '--prune',
            'https://oauth2:<REDACTED>@github.com/sourcegraph-testing/markdowns',
            '+refs/heads/*:refs/heads/*',
            '+refs/tags/*:refs/tags/*',
            '+refs/pull/*:refs/pull/*',
            '+refs/merge-requests/*:refs/merge-requests/*',
            '+refs/pull-requests/*:refs/pull-requests/*',
            '+refs/changes/*:refs/changes/*',
            '+refs/sourcegraph/*:refs/sourcegraph/*',
        ],
        dir: '/Users/bolajio/.sourcegraph/repos_1/github.com/sourcegraph-testing/markdowns/.git',
        path: '/usr/bin/git',
    },
    {
        start: '2023-07-18T10:19:02.598279Z',
        duration_seconds: 1.010095709,
        args: [
            'git',
            '-c',
            'credential.helper=',
            '-c',
            'protocol.version=2',
            'fetch',
            '--progress',
            '--prune',
            'https://oauth2:<REDACTED>@github.com/sourcegraph-testing/markdowns',
            '+refs/heads/*:refs/heads/*',
            '+refs/tags/*:refs/tags/*',
            '+refs/pull/*:refs/pull/*',
            '+refs/merge-requests/*:refs/merge-requests/*',
            '+refs/pull-requests/*:refs/pull-requests/*',
            '+refs/changes/*:refs/changes/*',
            '+refs/sourcegraph/*:refs/sourcegraph/*',
        ],
        dir: '/Users/bolajio/.sourcegraph/repos_1/github.com/sourcegraph-testing/markdowns/.git',
        path: '/usr/bin/git',
    },
]
