fragment Commit on GitCommit {
    id
    abbreviatedOID
    canonicalURL
    subject
    body
    author {
        date
        person {
            name
            email
            ...Avatar_Person
        }
    }
    committer {
        date
        person {
            name
            email
            ...Avatar_Person
        }
    }
}
