ALTER TABLE cm_emails
    ADD COLUMN IF NOT EXISTS include_results BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE cm_webhooks
    ADD COLUMN IF NOT EXISTS include_results BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE cm_slack_webhooks
    ADD COLUMN IF NOT EXISTS include_results BOOLEAN NOT NULL DEFAULT FALSE;
