export const languageMarkdownID: { [name: string]: string } = {
    BASIC: 'basic',
    Bash: 'bash',
    C: 'c',
    'C#': 'csharp',
    'C++': 'cpp',
    COBOL: 'cobol',
    Elm: 'elm',
    Erlang: 'erlang',
    Fortran: 'fortran',
    Go: 'go',
    Groovy: 'groovy',
    Haskell: 'haskell',
    Java: 'java',
    JavaScript: 'javascript',
    Julia: 'julia',
    Kotlin: 'kotlin',
    Lisp: 'lisp',
    Matlab: 'matlab',
    'Objective-C': 'objectivec',
    PHP: 'php',
    Perl: 'perl',
    Python: 'python',
    R: 'r',
    Ruby: 'ruby',
    Rust: 'rust',
    Scala: 'scala',
    Swift: 'swift',
    TypeScript: 'typescript',
    Zig: 'zig',
}

export const languageNames = Array.from(Object.keys(languageMarkdownID))
