#!/bin/bash

# This script is a wrapper around `universal-ctags`.
#
# This wrapper script runs `universal-ctags` via the `us.gcr.io/sourcegraph-dev/symbols` Docker image. This is the
# same Docker image that actually runs the symbols service in production, and it has the `universal-ctags` compiled
# binary inside of it (because it needs it, too).
#
# To use your own `universal-ctags` binary instead of this wrapper in your local dev server, use
# `CTAGS_COMMAND=path/to/ctags dev/start.sh`.

unset CDPATH
cd "$(dirname "${BASH_SOURCE[0]}")/.." # cd to repo root dir

IMAGE=docker.sourcegraph.com/symbols:latest

if [[ -z "${OFFLINE-}" ]] && ! docker pull "$IMAGE" > /dev/null; then
	echo
	echo Unable to pull latest Docker image "$IMAGE" for universal-ctags, which is used by the symbols service.
	echo
	echo To run the dev server using the latest image available locally, rerun with OFFLINE=true.
	exit 1
fi

exec docker run -a stdin -a stdout -a stderr -i --user guest --name=universal-ctags --entrypoint /usr/local/bin/universal-ctags --rm "$IMAGE" "$@"
