#!/bin/bash
set -e
cd "$(dirname "${BASH_SOURCE[0]}")/../.."

export GOBIN="$PWD/.bin"
export PATH=$GOBIN:$PATH
export GO111MODULE=on

go install honnef.co/go/tools/cmd/megacheck

echo go install...
go install -buildmode=archive ./...

echo go vet...
go vet ./...

echo staticcheck and unused...
megacheck --simple.exit-non-zero=true ./...
