#!/bin/bash

# The "sg" script runs "sgx" pointing at the live site. Be aware that
# its name conflicts with the standard (but rarely used) "switch
# group" program.
#
# Symlink it into your $PATH to use it.
#
# Also, include this in your .bashrc to set up completion:
#   complete -F _sgx sg

SRC_ENDPOINT=https://sourcegraph.com/api/ SG_URL=https://sourcegraph.com exec sgx "$@"
