DROP TRIGGER IF EXISTS codeintel_scip_documents_dereference_logs_insert ON codeintel_scip_document_lookup;
DROP FUNCTION IF EXISTS update_codeintel_scip_documents_dereference_logs_delete;
DROP TABlE IF EXISTS codeintel_scip_documents_dereference_logs;
