# See explanation of linters at https://golangci-lint.run/usage/linters/
linters:
  disable-all: true
  enable:
    - bodyclose # nogo equivelant
    - depguard # nogo equivelant
    - forbidigo # nogo equivelant
    - gocritic # nogo equivelant
    - goimports
    - gosimple # nogo equivelant
    - govet # nogo equivelant
    - ineffassign # nogo equivelant
    #- nolintlint see https://github.com/golangci/golangci-lint/issues/3228.
    - staticcheck # nogo equivelant
    - typecheck
    - unconvert
    # - unused
    - unparam
    - exportloopref # nogo equivelant

linters-settings:
  depguard:
    list-type: denylist
    include-go-root: true
    packages-with-error-message:
      # Deprecated packages
      - io/ioutil: "The ioutil package has been deprecated"
      # Blacklisted error packages
      - errors: "Use github.com/sourcegraph/sourcegraph/lib/errors instead"
      - github.com/pkg/errors: "Use github.com/sourcegraph/sourcegraph/lib/errors instead"
      - github.com/cockroachdb/errors: "Use github.com/sourcegraph/sourcegraph/lib/errors instead"
      - github.com/hashicorp/go-multierror: "Use github.com/sourcegraph/sourcegraph/lib/errors instead"
      # More performant regexp
      - regexp: "Use github.com/grafana/regexp instead"
      - github.com/hexops/autogold$: "Use github.com/hexops/autogold/v2 instead"
  gocritic:
    disabled-checks:
      - appendAssign # Too many false positives
      - assignOp # Maybe worth adding, but likely not worth the noise
      - commentFormatting # No strong benefit
      - deprecatedComment # Unnecessary
      - exitAfterDefer # Only occurs in auxiliary tools
      - ifElseChain # Noisy for not much gain
      - singleCaseSwitch # Noisy for not much gain
  #unparam:

  govet:
    disable:
      - composites
  staticcheck:
    checks:
      - "all"
  forbidigo:
    forbid:
      # Use errors.Newf instead
      - '^fmt\.Errorf$'

issues:
  exclude-rules:
    # Exclude bodyclose lint from tests because leaking connections in tests
    # is a non-issue, and checking that adds unnecessary noise
    - path: _test\.go
      linters:
        - bodyclose
        - unparam
        - gosimple
        - unused

run:
  timeout: 5m

  skip-dirs:
    - client
    - ui
    - vendor
    - node_modules
    - docker-images/syntax-highlighter

  skip-files:
    # Auto-generated with depguard and forbidigo failures
    - schema/schema.go

    # Imports blacklisted errors
    # Unfortunately golangci-lint doesn't really like multiple go.mod files, so
    # whenever we reference a file here it's relative to its containing workspace.
    # These values are under the ./lib module.
    - errors/cockroach.go

    # These are all projects with distinct go.mod files that can't import lib
    # due to not knowing an absolute path to the user's sourcegraph directory
    # and go mod replace directives not accepting relative paths.
    #
    # We should remove the go.mod files in these directories and share the set
    # of dependencies in the root module (which has access to the colocated lib)
    # like we did with sg. That seemed very successful!

    # In ./enterprise/dev/insight-data-gen
    - main.go
    # In ./internal/cmd/progress-bot
    - main.go
