version: 1
snapshot:
  widths:
    - 960 # Half-width browser window (e.g. docked to the side next to an editor)
    - 1920 # Full-width browser window
  percy-css: |
    .percy-hide,
    .monaco-editor .cursor {
      visibility: hidden !important;
    }
