version: 2
snapshot:
  widths:
    - 1920 # Full-width browser window
  percy-css: |
    .percy-hide,
    .monaco-editor .cursor {
      visibility: hidden !important;
    }
    .percy-inactive-element {
      pointer-events: none !important;
    }
    .percy-display-none {
      display: none !important;
    }
discovery:
  disable-cache: true
