branch: release
verifyConditions:
  - semantic-release-firefox
  - semantic-release-chrome
  - '@semantic-release/github'
  - '@semantic-release/npm'
prepare:
  # Build bundles and output them to the dist folders
  - path: '@semantic-release/exec'
    cmd: yarn run build
  # Update Firefox manifest version, create xpi and zip sources
  - path: semantic-release-firefox
    distFolder: &firefoxDistFolder build/firefox
    xpiPath: &firefoxXpiPath sourcegraph-extension-firefox.xpi
    sourcesGlobOptions:
      dot: true # Files like .babelrc are needed to build
      ignore:
        - .git
        - .git/**
        - .github
        - .github/**
        - .npmrc # This is added by semantic-release and would cause npm install to fail for the reviewer because it references NPM_TOKEN
        - *firefoxXpiPath
        - build
        - build/**
        - ci
        - ci/**
        - cypress
        - cypress/**
        - node_modules
        - node_modules/**
        - sources.zip
  # Update Chrome manifest version and zip extension
  - path: semantic-release-chrome
    asset: &chromeAssetPath sourcegraph-extension-chrome.zip
    distFolder: &chromeDistFolder build/chrome
  # Update package.json version for Phabricator bundle on npm
  - path: '@semantic-release/npm'
    pkgRoot: &phabricatorPkgRoot build/phabricator
publish:
  # Publish to Mozilla Add-on store
  - path: semantic-release-firefox
    xpiPath: *firefoxXpiPath
    distFolder: *firefoxDistFolder
    addOnSlug: sourcegraph
    notesToReviewer: |
      This extension is open source at https://github.com/sourcegraph/browser-extensions

      Running from source:

      1.  With yarn 1.9.4 installed, run `yarn`
      2.  yarn run build
      3.  Go to about:debugging
      4.  Select "Enable add-on debugging"
      5.  Load Temporary Add-on
      6.  Click "Load Temporary Add-on" and select "build/bundles/firefox-bundle.xpi"

      How to use the extension:
      The Sourcegraph developer extension works on GitHub.com. Below you will find a list of Sourcegraph's features with relevant URLs as well as screenshots and videos to help verify the extension.

      Relevant URLs:
      Open on Sourcegraph URL: https://github.com/gorilla/mux
      Code browsing URL: https://github.com/gorilla/mux/blob/master/mux.go

      Main features of Sourcegraph:

      1.  Open in Sourcegraph - This feature takes the user from the repository homepage to viewing the repository on Sourcegraph.com https://goo.gl/jepnDz
      2.  Code intelligence when hovering over code tokens - This provides developers with IDE like code browsing tools on GitHub - https://goo.gl/G1cMMM
      3.  Action items for hover tooltip - Users can now see references, the definition, and also search based on the currently selected token. -
          https://goo.gl/CHFnjr
      4.  File tree navigation when viewing a GitHub repository - https://goo.gl/7NafYf
  # Publish to Chrome extension store
  - path: semantic-release-chrome
    asset: *chromeAssetPath
    distFolder: *chromeDistFolder
    extensionId: dgjhfomjieaadpoljlnidmbgkdffpack
  # Publish Phabricator bundle to npm so it can be bundled with Sourcegraph Server
  - path: '@semantic-release/npm'
    pkgRoot: *phabricatorPkgRoot
  # Create release on GitHub
  - path: '@semantic-release/github'
    assets:
      - path: *chromeAssetPath
      - path: *firefoxXpiPath
