query RepositoryGitRefs($repoName: String!, $query: String, $type: GitRefType!) {
    repository(name: $repoName) {
        ...RepositoryGitRefs
    }
}

query RepositoryGitCommits($repoName: String!, $query: String!, $revision: String!) {
    repository(name: $repoName) {
        commitByHash: commit(rev: $query) {
            ...RevPickerGitCommit
        }
        ancestorCommits: commit(rev: $revision) {
            ancestors(first: 15, query: $query) {
                nodes {
                    ...RevPickerGitCommit
                }
            }
        }
    }
}
