query TagsPage_TagsQuery(
    $repoName: String!
    $first: Int!
    $withBehindAhead: Boolean!
    $revspec: String = ""
    $query: String = ""
) {
    repository(name: $repoName) {
        id
        gitRefs(first: $first, type: GIT_TAG, query: $query) {
            ...GitTagsConnection
        }
    }
}

fragment GitTagsConnection on GitRefConnection {
    nodes {
        id
        ...GitReferencesTable_Ref
    }
    pageInfo {
        hasNextPage
    }
    totalCount
}
