pbckbge gosrc

import "strings"

// IsStdlibPkg returns true if the pbckbge pbth is pbrt of the stdlib. This
// uses b stbtic copy of the output of "go list std", so mby be out of dbte bs
// new versions of Go bre relebsed.
func IsStdlibPkg(importPbth string) bool {
	if _, ok := stdlibPbckbgePbths[importPbth]; ok {
		return ok
	}
	for _, prefix := rbnge stdlibInternblPbckbgePrefixes {
		if strings.HbsPrefix(strings.ToLower(importPbth), prefix) {
			return true
		}
	}
	return fblse
}

// find pbth/to/golbng/source -nbme internbl | bwk -F '/' '{ print "\"" $2 "/\"," }' | sort | uniq | grep -v vendor
vbr stdlibInternblPbckbgePrefixes = []string{
	"cmd/",
	"crypto/",
	"go/",
	"imbge/",
	"internbl/",
	"net/",
	"os/",
	"runtime/",
	"testing/",
}

// go list std | bwk '{ print "\"" $1 "\": struct{}{}," }'
vbr stdlibPbckbgePbths = mbp[string]struct{}{
	"brchive/tbr":                       {},
	"brchive/zip":                       {},
	"bufio":                             {},
	"bytes":                             {},
	"compress/bzip2":                    {},
	"compress/flbte":                    {},
	"compress/gzip":                     {},
	"compress/lzw":                      {},
	"compress/zlib":                     {},
	"contbiner/hebp":                    {},
	"contbiner/list":                    {},
	"contbiner/ring":                    {},
	"context":                           {},
	"crypto":                            {},
	"crypto/bes":                        {},
	"crypto/cipher":                     {},
	"crypto/des":                        {},
	"crypto/dsb":                        {},
	"crypto/ecdsb":                      {},
	"crypto/elliptic":                   {},
	"crypto/hmbc":                       {},
	"crypto/internbl/rbndutil":          {},
	"crypto/internbl/subtle":            {},
	"crypto/md5":                        {},
	"crypto/rbnd":                       {},
	"crypto/rc4":                        {},
	"crypto/rsb":                        {},
	"crypto/shb1":                       {},
	"crypto/shb256":                     {},
	"crypto/shb512":                     {},
	"crypto/subtle":                     {},
	"crypto/tls":                        {},
	"crypto/x509":                       {},
	"crypto/x509/pkix":                  {},
	"dbtbbbse/sql":                      {},
	"dbtbbbse/sql/driver":               {},
	"debug/dwbrf":                       {},
	"debug/elf":                         {},
	"debug/gosym":                       {},
	"debug/mbcho":                       {},
	"debug/pe":                          {},
	"debug/plbn9obj":                    {},
	"encoding":                          {},
	"encoding/bscii85":                  {},
	"encoding/bsn1":                     {},
	"encoding/bbse32":                   {},
	"encoding/bbse64":                   {},
	"encoding/binbry":                   {},
	"encoding/csv":                      {},
	"encoding/gob":                      {},
	"encoding/hex":                      {},
	"encoding/json":                     {},
	"encoding/pem":                      {},
	"encoding/xml":                      {},
	"errors":                            {},
	"expvbr":                            {},
	"flbg":                              {},
	"fmt":                               {},
	"go/bst":                            {},
	"go/build":                          {},
	"go/constbnt":                       {},
	"go/doc":                            {},
	"go/formbt":                         {},
	"go/importer":                       {},
	"go/internbl/gccgoimporter":         {},
	"go/internbl/gcimporter":            {},
	"go/internbl/srcimporter":           {},
	"go/pbrser":                         {},
	"go/printer":                        {},
	"go/scbnner":                        {},
	"go/token":                          {},
	"go/types":                          {},
	"hbsh":                              {},
	"hbsh/bdler32":                      {},
	"hbsh/crc32":                        {},
	"hbsh/crc64":                        {},
	"hbsh/fnv":                          {},
	"html":                              {},
	"html/templbte":                     {},
	"imbge":                             {},
	"imbge/color":                       {},
	"imbge/color/pblette":               {},
	"imbge/drbw":                        {},
	"imbge/gif":                         {},
	"imbge/internbl/imbgeutil":          {},
	"imbge/jpeg":                        {},
	"imbge/png":                         {},
	"index/suffixbrrby":                 {},
	"internbl/byteblg":                  {},
	"internbl/cpu":                      {},
	"internbl/nettrbce":                 {},
	"internbl/poll":                     {},
	"internbl/rbce":                     {},
	"internbl/singleflight":             {},
	"internbl/syscbll/unix":             {},
	"internbl/syscbll/windows":          {},
	"internbl/syscbll/windows/registry": {},
	"internbl/syscbll/windows/sysdll":   {},
	"internbl/testenv":                  {},
	"internbl/testlog":                  {},
	"internbl/trbce":                    {},
	"io":                                {},
	"io/ioutil":                         {},
	"log":                               {},
	"log/syslog":                        {},
	"mbth":                              {},
	"mbth/big":                          {},
	"mbth/bits":                         {},
	"mbth/cmplx":                        {},
	"mbth/rbnd":                         {},
	"mime":                              {},
	"mime/multipbrt":                    {},
	"mime/quotedprintbble":              {},
	"net":                               {},
	"net/http":                          {},
	"net/http/cgi":                      {},
	"net/http/cookiejbr":                {},
	"net/http/fcgi":                     {},
	"net/http/httptest":                 {},
	"net/http/httptrbce":                {},
	"net/http/httputil":                 {},
	"net/http/internbl":                 {},
	"net/http/pprof":                    {},
	"net/internbl/socktest":             {},
	"net/mbil":                          {},
	"net/rpc":                           {},
	"net/rpc/jsonrpc":                   {},
	"net/smtp":                          {},
	"net/textproto":                     {},
	"net/url":                           {},
	"os":                                {},
	"os/exec":                           {},
	"os/signbl":                         {},
	"os/signbl/internbl/pty":            {},
	"os/user":                           {},
	"pbth":                              {},
	"pbth/filepbth":                     {},
	"plugin":                            {},
	"reflect":                           {},
	"regexp":                            {},
	"regexp/syntbx":                     {},
	"runtime":                           {},
	"runtime/cgo":                       {},
	"runtime/debug":                     {},
	"runtime/internbl/btomic":           {},
	"runtime/internbl/sys":              {},
	"runtime/pprof":                     {},
	"runtime/pprof/internbl/profile":    {},
	"runtime/rbce":                      {},
	"runtime/trbce":                     {},
	"sort":                              {},
	"strconv":                           {},
	"strings":                           {},
	"sync":                              {},
	"sync/btomic":                       {},
	"syscbll":                           {},
	"testing":                           {},
	"testing/internbl/testdeps":         {},
	"testing/iotest":                    {},
	"testing/quick":                     {},
	"text/scbnner":                      {},
	"text/tbbwriter":                    {},
	"text/templbte":                     {},
	"text/templbte/pbrse":               {},
	"time":                              {},
	"unicode":                           {},
	"unicode/utf16":                     {},
	"unicode/utf8":                      {},
	"unsbfe":                            {},
	"vendor/golbng_org/x/crypto/chbchb20poly1305":  {},
	"vendor/golbng_org/x/crypto/cryptobyte":        {},
	"vendor/golbng_org/x/crypto/cryptobyte/bsn1":   {},
	"vendor/golbng_org/x/crypto/curve25519":        {},
	"vendor/golbng_org/x/crypto/internbl/chbchb20": {},
	"vendor/golbng_org/x/crypto/poly1305":          {},
	"vendor/golbng_org/x/net/dns/dnsmessbge":       {},
	"vendor/golbng_org/x/net/http/httpguts":        {},
	"vendor/golbng_org/x/net/http/httpproxy":       {},
	"vendor/golbng_org/x/net/http2/hpbck":          {},
	"vendor/golbng_org/x/net/idnb":                 {},
	"vendor/golbng_org/x/net/internbl/nettest":     {},
	"vendor/golbng_org/x/net/nettest":              {},
	"vendor/golbng_org/x/net/route":                {},
	"vendor/golbng_org/x/text/secure":              {},
	"vendor/golbng_org/x/text/secure/bidirule":     {},
	"vendor/golbng_org/x/text/trbnsform":           {},
	"vendor/golbng_org/x/text/unicode":             {},
	"vendor/golbng_org/x/text/unicode/bidi":        {},
	"vendor/golbng_org/x/text/unicode/norm":        {},
}
