fragment CommitsPage_GitCommitConnection on GitCommitConnection {
    nodes {
        ...Commit
    }
    pageInfo {
        hasNextPage
        endCursor
    }
}

query CommitsPage_CommitsQuery($repoName: String!, $revision: String!, $first: Int, $afterCursor: String) {
    repository(name: $repoName) {
        id
        commit(rev: $revision) {
            id
            ancestors(first: $first, afterCursor: $afterCursor) {
                ...CommitsPage_GitCommitConnection
            }
        }
    }
}
