fragment CommitsPage_GitCommitConnection on GitCommitConnection {
    nodes {
        ...Commit
    }
    pageInfo {
        hasNextPage
        endCursor
    }
}

query CommitsPage_CommitsQuery($repoName: String!, $revision: String!, $first: Int, $afterCursor: String) {
    repository(name: $repoName) {
        id
        commit(rev: $revision) {
            id
            ancestors(first: $first, afterCursor: $afterCursor) {
                # This is a bit hacky, but by fetching all the data needed by both
                # the history panel and the commits page we ensure that our custom
                # Apollo infinitiy scroll cache handling for this field works
                # correctly. Eventually we should revisit the use of infinity scroll
                # on the commits page.
                ...HistoryPanel_HistoryConnection
                ...CommitsPage_GitCommitConnection
            }
        }
    }
}
