# Dockerfile for running org-grep. This is to make it convenient to test searcher in
# the same network as a production environment.
#
# $ docker build -f Dockerfile.org-grep -t org-grep .
# $ docker run --rm=true org-grep github.com/sourcegraph/go-langserver vscode
FROM python:3-alpine@sha256:0c2d5177f1c01690e8ac6bc6391bb8e5ea9c3b4f65ef50f27dca1bc21c8c6711

RUN pip install requests==2.18.4

COPY org-grep.py /org-grep.py

ENTRYPOINT ["python", "/org-grep.py"]
