#!/bin/bash
set -e
cd "$(dirname "${BASH_SOURCE[0]}")/../.."

export GOBIN="$PWD/.bin"
export PATH=$GOBIN:$PATH

go install honnef.co/go/tools/cmd/megacheck

echo go install...
go install -buildmode=archive ./...

echo go vet...
go vet ./...

# TODO(beyang): Re-enable once https://github.com/dominikh/go-tools/issues/328 is resolved
# echo staticcheck and unused...
# megacheck --simple.exit-non-zero=true ./...
