#!/bin/bash

set -euf -o pipefail

# Mirroring:
# - https://github.com/sourcegraph/infrastructure/blob/d67cfdaf7760b926df165745e40f7bd9507d1c20/docker-images/zoekt-indexserver/Dockerfile#L28-L35
# - https://github.com/sourcegraph/infrastructure/blob/d67cfdaf7760b926df165745e40f7bd9507d1c20/docker-images/zoekt-webserver/Dockerfile#L27-L34
export GOGC=50

case "$1" in

    indexserver)
        exec zoekt-sourcegraph-indexserver -sourcegraph_url http://localhost:3090 -index $HOME/.sourcegraph/zoekt/index -interval 1m -listen :6072
        ;;

    webserver)
        exec zoekt-webserver -index $HOME/.sourcegraph/zoekt/index -pprof -rpc -listen :3070
        ;;

    *)
        echo "USAGE: $0 (indexserver|webserver)"
        exit 1
        ;;

esac
