#!/bin/bash

# Check: httpapi package should not depend on auth in anyway. The httpapi layer
# should be agnostic to the identity and permission of the actor. NOTE: ideally
# this would include recursive dependencies, but there are a few warts in the
# import structure that prevent this from being enforced.

found_violation=
declare -a no_auth_pkgs=("sourcegraph.com/sourcegraph/sourcegraph/services/httpapi/..." "sourcegraph.com/sourcegraph/sourcegraph/app/...")
for pkg in "${no_auth_pkgs[@]}"; do
		illegal_imports=$(go list -f '{{join .Deps "\n"}}' "$pkg" | grep 'sourcegraph.com/sourcegraph/sourcegraph/pkg/auth')
		if [[ ! -z "$illegal_imports" ]]; then
				echo "Found illegal import of sourcegraph.com/sourcegraph/sourcegraph/pkg/auth from $pkg";
		fi
done;

if [[ ! -z "$found_violation" ]]; then
		exit 1;
fi
