#!/bin/bash

set -e

go-get() {
    local pkg=$1
    local cmd=$(basename $pkg)
    command -v $cmd >/dev/null 2>&1 || go get $pkg
}

go-get honnef.co/go/staticcheck/cmd/staticcheck

echo go list...
PKGS=$(go list ./... | grep -v /vendor/)

echo go vet...
go vet ${PKGS}

echo staticcheck...
staticcheck ${PKGS}
