#!/bin/bash

# Runs go-generate-all and ensures no files changed. This relies on the go
# generation that ran are idempotent.

set -e

working_copy_hash=$((git diff; git status) | (md5sum || md5) 2> /dev/null)

$(dirname $0)/go-generate-all

new_working_copy_hash=$((git diff; git status) | (md5sum || md5) 2> /dev/null)

if [[ ${working_copy_hash} = ${new_working_copy_hash} ]]; then
    echo "SUCCESS: go generate did not change the working copy"
else
    echo "FAIL: go generate changed the working copy"
    git diff
    git status
    exit 2
fi
