coverage:
  range: 50...75
  status:
    project:
      default:
        informational: true
      codeintel:
        informational: true
        paths:
          - cmd/precise-code-intel-*
          - internal/codeintel
          - enterprise/internal/codeintel
      typescript:
        informational: true
        flags:
          - typescript
      go:
        informational: true
        flags:
          - go
    patch:
      default:
        target: 5%
comment:
  require_changes: yes
  layout: 'diff, flags, files'
ignore:
  - '**/bindata.go'
