coverage:
  range: 50...75
  status:
    project:
      default:
        informational: true
      codeintel:
        informational: true
        paths:
          - cmd/symbols
          - enterprise/cmd/precise-code-intel-*
          - enterprise/internal/codeintel
      batches:
        informational: true
        paths:
          - cmd/frontend/graphqlbackend/batches.go
          - internal/usagestats/batches.go
          - enterprise/cmd/frontend/internal/batches
          - enterprise/internal/batches
          - client/web/src/enterprise/batches
      insights:
        informational: true
        paths:
          - client/web/src/insights
          - client/web/src/views
      search:
        informational: true
        paths:
          - client/shared/src/search
          - client/web/src/enterprise/search
          - client/web/src/search
          - cmd/frontend/graphqlbackend/*search*
          - cmd/frontend/internal/search
          - cmd/searcher
          - internal/search
      typescript:
        informational: true
        flags:
          - typescript
      go:
        informational: true
        flags:
          - go
    patch:
      default:
        informational: true
        only_pulls: true
        target: 5%
comment: false
ignore:
  - '**/bindata.go'
  - 'client/vscode/**/*'

flags:
  typescript:
    carryforward: true

github_checks:
  annotations: false
