#!/usr/bin/env bash
#
# Convenience script that wraps `go` invocations by ensuring the `replace
# github.com/sourcegraph/sourcegraph` directive is removed and running `go mod tidy` afterward.

export GO111MODULE=on
go mod edit -dropreplace github.com/sourcegraph/sourcegraph
go "$@"
go mod tidy

