#!/bin/bash

# Runs go generate on all directories

blacklist_re='(vendor|gitserver|go-sourcegraph|pkg/inventory|pkg/vcs)'

set -e
cd $(git rev-parse --show-toplevel)

git grep -l go:generate \
    | grep '\.go$' \
    | egrep -v ${blacklist_re} \
    | xargs -n1 dirname \
    | sort | uniq \
    | awk '{ print "./" $1 }' \
    | xargs go generate
