#!/bin/bash

# Runs go generate on all directories

blacklist_re='(_workspace|devdoc|gitserver)'

set -e
cd $(git rev-parse --show-toplevel)

sgxosname=$(uname -o 2>/dev/null || uname -s)

if [[ $sgxosname == "Cygwin" ]] || [[ $sgxosname == "Msys" ]] || [[ $sgxosname == MINGW* ]]; then
	p=$(cmd /C "echo %cd%/Godeps/_workspace;%GOPATH%")
	# removing trailing line feed
	p="$(echo "${p}" | sed -e 's/[[:space:]]*$//')"
	export GOPATH="$p"
else
	export GOPATH=$PWD/Godeps/_workspace:$GOPATH
fi

git grep -l go:generate \
    | grep '\.go$' \
    | egrep -v ${blacklist_re} \
    | xargs -n1 dirname \
    | sort | uniq \
    | awk '{ print "./" $1 }' \
    | xargs go generate
