#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")/.."

find . -path ./.git -prune -o -print | git -c core.excludesfile=$(cat .github/CODEOWNERS | awk -F " +@" '{ print $1 }' > /tmp/ignore && echo /tmp/ignore) check-ignore --verbose --no-index -n --stdin | grep '^::\s' | grep -v '^::\s\.$'
