# Note: This file is ran relative to the sourcegraph/sourcegraph repo root.
# delve-hook is for debugging Go processes
gitserver: ./dev/delve-hook gitserver
indexer: ./dev/delve-hook indexer
query-runner: ./dev/delve-hook query-runner
repo-updater: ./dev/delve-hook repo-updater
searcher: ./dev/delve-hook searcher
symbols: ./dev/delve-hook symbols
github-proxy: ./dev/delve-hook github-proxy
lsp-proxy: ./dev/delve-hook lsp-proxy
xlang-go: ./dev/delve-hook xlang-go -mode=tcp -addr=:4389
frontend: ./dev/delve-hook frontend
watch: ./dev/changewatch.sh
web-enterprise: ./node_modules/.bin/gulp --color watch
web-oss: sh -c "cd ../sourcegraph && ./node_modules/.bin/gulp --color watchDist"
# Checks that `yarn link`ed repositories are not behind the version in package.json
yarn-link-check: yarn check-npm-links --watch --color
syntect_server: ./dev/syntect_server
zoekt-indexserver: ./dev/zoekt-wrapper zoekt-sourcegraph-indexserver -sourcegraph_url http://localhost:3090 -index $HOME/.sourcegraph/zoekt/index -interval 1m -listen :6072
zoekt-webserver: ./dev/zoekt-wrapper zoekt-webserver -index $HOME/.sourcegraph/zoekt/index -pprof -rpc
keycloak: ./dev/auth-provider/keycloak.sh
# jaeger: docker run --name=jaeger --rm -p5775:5775/udp -p6831:6831/udp -p6832:6832/udp -p5778:5778 -p16686:16686 -p14268:14268 jaegertracing/all-in-one:latest
