#!/usr/bin/env bash

# This script is a wrapper around `scip-ctags`.
#
# It checks if scip-ctags has been installed through ./dev/scip-ctags-install.sh or falls back to a dockerized version.
#
# To use your own `scip-ctags` binary instead of this wrapper in your local dev server, use
# `SCIP_CTAGS_COMMAND=path/to/ctags sg start`.

root="$(dirname "${BASH_SOURCE[0]}")/.." >/dev/null
TARGET=$("$root/dev/scip-ctags-install.sh" which)

if [ ! -f "${TARGET}" ]; then 
  exec docker run --rm -i \
    -a stdin -a stdout -a stderr \
    --user guest \
    --name=scip-ctags-$$ \
    --entrypoint /usr/local/bin/scip-ctags \
    scip-ctags "$@"
else 
  ${TARGET} "$@"
fi
