#!/bin/bash

# restarts a travis build continuously until it fails, and prints the
# number of successful builds before failure. used for testing whether
# a build is flaky.

BUILDNUM="$1"

echo Restarting build $BUILDNUM until it fails...

i=0
while true; do
    echo Waiting for build $BUILDNUM to complete
    while true; do
        (travis show $BUILDNUM | grep -E '(passed|failed)') && break
        sleep 5
        echo -n .
    done

    state=$(travis show $BUILDNUM | grep -E '(passed|failed)')
        
    if [[ "$state" == "failed" ]]; then break; fi
    echo
    echo '========================================================='
    echo
    (( i+=1 ))
    echo $i successes as of `date`
    sleep 0.1

    echo Restarting build $BUILDNUM...
    travis restart $BUILDNUM
done
