#!/bin/bash

set -euf -o pipefail
unset CDPATH
REPOROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/.. && pwd )"


# Fails and prints matches if any code files contain 'TODO(security)'.

found=$(grep -Hnr --exclude-dir=Godeps --exclude-dir=node_modules --exclude-dir=bower_components --exclude-dir=.git --exclude-dir=assets --exclude='*.test' --exclude=SECURITY.md --exclude=todo-security 'TODO(security)' "$REPOROOT" || echo -n)

if [[ ! "$found" == "" ]]; then
    echo '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
    echo '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
    echo 'Found instances of TODO(security) in code. Fix these!'
    echo '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
    echo '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
    echo "$found"
    exit 1
fi

exit 0
