#!/usr/bin/env bash

# This script is a wrapper around `universal-ctags` to download and run universal-ctags using bazel
#
# To use your own `universal-ctags` binary instead of this wrapper in your local dev server, use
# `CTAGS_COMMAND=path/to/ctags sg start`.

# We silence a few things, because the arguments that symbols pass to this script, which are then passed to
# the bazel run are printed out again by Bazel by default. And they're very long, so much that it hads about
# 40 lines, adding unecessary noise to the output of `sg start`
bazel run //dev/tools:universal-ctags --logging=0 --noshow_progress --ui_event_filters=-info,-debug,-stdout -- "$@"
