package gosyntect

var treesitterSupportedFiletypes = map[string]struct{}{
	"c":          {},
	"c++":        {},
	"c_sharp":    {},
	"cpp":        {},
	"go":         {},
	"java":       {},
	"javascript": {},
	"jsonnet":    {},
	"jsx":        {},
	"kotlin":     {},
	"nickel":     {},
	"perl":       {},
	"python":     {},
	"ruby":       {},
	"rust":       {},
	"scala":      {},
	"smithy":     {},
	"tsx":        {},
	"typescript": {},
	"xlsg":       {},
	"zig":        {},
}
