fragment TreePage_TreeWithCommitInfo on GitTree {
    canonicalURL
    entries(first: $first) {
        ...TreeEntryWithCommitInfo
    }
}

query TreePageCommitInfoQuery($repoID: ID!, $commitID: String!, $filePath: String!, $first: Int) {
    node(id: $repoID) {
        __typename
        id
        ... on Repository {
            commit(rev: $commitID) {
                id
                tree(path: $filePath) {
                    ...TreePage_TreeWithCommitInfo
                }
            }
        }
    }
}

query TreePageReadmeQuery($repoID: ID!, $revspec: String!, $path: String!) {
    node(id: $repoID) {
        ... on Repository {
            id
            commit(rev: $revspec) {
                id
                blob(path: $path) {
                    canonicalURL # key field
                    ...RepoPage_Readme
                }
            }
        }
    }
}

fragment TreePage_Readme on GitBlob {
    name
    ...Readme_Blob
}
