fragment DiffSummaryHeaderCommit on GitCommit {
    id
    abbreviatedOID
    canonicalURL
    ancestors(first: 2) {
        nodes {
            id
            abbreviatedOID
            canonicalURL
            perforceChangelist {
                cid
                canonicalURL
            }
        }
    }
    diff {
        fileDiffs(paths: [$path]) {
            diffStat {
                added
                deleted
            }
        }
    }
    perforceChangelist {
        cid
        canonicalURL
    }
}
