fragment FileViewGitBlob on GitBlob {
    canonicalURL
    binary
    content
    richHTML
    languages
    totalLines
    byteSize

    ...OpenInCodeHostAction
    ...FileIcon_GitBlob
}

fragment FileViewHighlightedFile on HighlightedFile {
    aborted
    lsif
}

fragment FileView_ResolvedRevision on Repository {
    externalRepository {
        serviceType
    }
    externalURLs {
        url
        serviceKind
    }
}

fragment FileViewCommit on GitCommit {
    canonicalURL
    abbreviatedOID
}

fragment FileViewCodeGraphData on CodeGraphData {
    id
    provenance
    commit
    toolInfo {
        name
        version
    }

    occurrences(first: 10000) {
        nodes {
            ...FileViewOccurrence
        }
        pageInfo {
            endCursor
            hasNextPage
        }
    }
}

fragment FileViewOccurrence on SCIPOccurrence {
    symbol
    range {
        start {
            line
            character
        }
        end {
            line
            character
        }
    }
    roles
}
