query BlobDiffQuery($repoName: String!, $revspec: String!, $paths: [String!]) {
    repository(name: $repoName) {
        id
        commit(rev: $revspec) {
            id
            diff {
                fileDiffs(paths: $paths) {
                    nodes {
                        ...FileDiff_Diff
                    }
                }
            }
        }
    }
}

query BlobPageQuery($repoName: String!, $revspec: String!, $path: String!) {
    repository(name: $repoName) {
        id
        commit(rev: $revspec) {
            id
            oid
            blob(path: $path) {
                ...BlobPage_Blob
            }
        }
    }
}

fragment BlobPage_Blob on GitBlob {
    canonicalURL
    content
    richHTML
    languages
}

query BlobSyntaxHighlightQuery(
    $repoName: String!
    $revspec: String!
    $path: String!
    $disableTimeout: Boolean!
    $format: HighlightResponseFormat = JSON_SCIP
) {
    repository(name: $repoName) {
        id
        commit(rev: $revspec) {
            id
            blob(path: $path) {
                canonicalURL
                highlight(disableTimeout: $disableTimeout, format: $format) {
                    aborted
                    lsif
                }
            }
        }
    }
}
