query BlobDiffViewCommitQuery($repoName: String!, $revspec: String!, $path: String!) {
    repository(name: $repoName) {
        id
        commit(rev: $revspec) {
            id
            perforceChangelist {
                cid
                canonicalURL
            }

            blob(path: $path) {
                ...DiffViewGitBlob
            }

            ...DiffViewCommit
        }
    }
}

query BlobFileViewBlobQuery($repoName: String!, $revspec: String!, $path: String!) {
    repository(name: $repoName) {
        id

        commit(rev: $revspec) {
            id
            oid
            blob(path: $path) {
                ...FileViewGitBlob
            }
            perforceChangelist {
                cid
                canonicalURL
            }
        }
    }
}

query BlobFileViewHighlightedFileQuery(
    $repoName: String!
    $revspec: String!
    $path: String!
    $disableTimeout: Boolean!
    $format: HighlightResponseFormat = JSON_SCIP
) {
    repository(name: $repoName) {
        id
        commit(rev: $revspec) {
            id
            blob(path: $path) {
                canonicalURL
                highlight(disableTimeout: $disableTimeout, format: $format) {
                    ...FileViewHighlightedFile
                }
            }
        }
    }
}

query BlobFileViewCodeGraphDataQuery($repoName: String!, $revspec: String!, $path: String!) {
    repository(name: $repoName) {
        id
        commit(rev: $revspec) {
            id
            blob(path: $path) {
                codeGraphData {
                    ...FileViewCodeGraphData
                }
            }
        }
    }
}

query BlobViewCodeGraphDataNextPage($codeGraphDataID: ID!, $after: String!) {
    node(id: $codeGraphDataID) {
        ... on CodeGraphData {
            occurrences(first: 10000, after: $after) {
                nodes {
                    ...FileViewOccurrence
                }
                pageInfo {
                    endCursor
                    hasNextPage
                }
            }
        }
    }
}

query BlobFileViewCommitQuery_revisionOverride($repoName: String!, $revspec: String!) {
    repository(name: $repoName) {
        commit(rev: $revspec) {
            ...FileViewCommit
            perforceChangelist {
                cid
                canonicalURL
            }
        }
    }
}

fragment BlobPage_ResolvedRevision on Repository {
    ...FileView_ResolvedRevision
}
