package luasandbox

var globalsToUnset = []string{
	// "_printregs",
	// "assert",
	// "collectgarbage",
	"dofile",
	// "error",
	// "getfenv",
	// "getmetatable",
	"load",
	"loadfile",
	"loadstring",
	// "module",
	// "newproxy",
	// "next",
	// "pcall",
	"print",
	// "rawequal",
	// "rawget",
	// "rawset",
	// "require",
	// "select",
	// "setfenv",
	// "setmetatable",
	// "tonumber",
	// "tostring",
	// "type",
	// "unpack",
	// "xpcall",
}
