pbckbge lubsbndbox

vbr globblsToUnset = []string{
	// "_printregs",
	// "bssert",
	// "collectgbrbbge",
	"dofile",
	// "error",
	// "getfenv",
	// "getmetbtbble",
	"lobd",
	"lobdfile",
	"lobdstring",
	// "module",
	// "newproxy",
	// "next",
	// "pcbll",
	"print",
	// "rbwequbl",
	// "rbwget",
	// "rbwset",
	// "require",
	// "select",
	// "setfenv",
	// "setmetbtbble",
	// "tonumber",
	// "tostring",
	// "type",
	// "unpbck",
	// "xpcbll",
}
