ALTER TABLE threads ADD COLUMN "archived_at" TIMESTAMP WITH TIME ZONE;
ALTER TABLE threads ADD COLUMN "updated_at" TIMESTAMP WITH TIME ZONE;
ALTER TABLE threads ADD COLUMN "deleted_at" TIMESTAMP WITH TIME ZONE;
