query AllBranchesPage_BranchesQuery(
    $repoName: String!
    $first: Int!
    $withBehindAhead: Boolean!
    $revspec: String = ""
    $query: String = ""
) {
    repository(name: $repoName) {
        id
        branches(first: $first, query: $query) {
            ...GitBranchesConnection
        }
    }
}

fragment GitBranchesConnection on GitRefConnection {
    nodes {
        id
        ...GitReferencesTable_Ref
    }
    pageInfo {
        hasNextPage
    }
    totalCount
}
