(package "lsp-cody"
         "0.0.1"
         "A Client to Connect to the Cody LSP Gateway")

(website-url "https://sourcegraph.com/")
(keywords "languages")

(package-file "lsp-cody.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)

(depends-on "emacs" "26.1")
