env:
  ENTERPRISE: '1'
  MINIFY: '1'
  FORCE_COLOR: '3'
  NODE_OPTIONS: --max_old_space_size=8192

steps:
  - command:
      - COVERAGE_INSTRUMENT=true dev/ci/yarn-run.sh storybook:build
      - yarn run cover-storybook
      - yarn nyc report -r json
      - bash <(curl -s https://codecov.io/bash) -c -F typescript -F storybook
    label: ':storybook::codecov: Storybook coverage'
  - command:
      - dev/ci/yarn-build.sh client/web
      - yarn lhci autorun
    label: ':lighthouse: Lighthouse'
    retry:
      automatic:
        limit: 1
    env:
      NODE_ENV: production
      WEBPACK_SERVE_INDEX: 'true'
      SOURCEGRAPH_API_URL: https://sourcegraph.com
      SOURCEGRAPHDOTCOM_MODE: 'true'
