env:
  ENTERPRISE: "1"
  MINIFY: "1"
  FORCE_COLOR: "3"

steps:
- command:
  - COVERAGE_INSTRUMENT=true dev/ci/yarn-run.sh build-storybook
  - yarn run cover-storybook
  - yarn nyc report -r json
  - bash <(curl -s https://codecov.io/bash) -c -F typescript -F storybook
  label: ':storybook::codecov: Storybook coverage'
