env:
  VAGRANT_RUN_ENV: "CI"
steps:
- label: ':chromium: Sourcegraph E2E'
  artifact_paths: ./*.png;./*.mp4;./ffmpeg.log;./*.log
  retry:
    automatic:
      exit_status: "*"
      limit: 1
  agents:
    queue: 'baremetal'
  command:
    - .buildkite/vagrant-run.sh sourcegraph-e2e

- label: ':docker::chromium: Sourcegraph QA'
  retry:
    automatic:
      exit_status: "*"
      limit: 1
  artifact_paths: ./*.png;./*.mp4;./*.log
  agents:
    queue: 'baremetal'
  command:
    - .buildkite/vagrant-run.sh sourcegraph-qa-test

- label: ':docker::brain: Code Intel QA'
  command:
    - dev/ci/test/code-intel/test.sh
  artifact_paths: ./*.log

- label: ':docker::arrow_double_up: Sourcegraph Upgrade'
  retry:
    automatic:
      exit_status: "*"
      limit: 1
  command:
  - .buildkite/vagrant-run.sh sourcegraph-upgrade
  artifact_paths: ./*.png;./*.mp4;./*.log
  agents:
    queue: 'baremetal'

# Flaky deployment. https://github.com/sourcegraph/sourcegraph/issues/25977
# - label: ":k8s: Sourcegraph Cluster (deploy-sourcegraph) QA"
#   commands:
#     - dev/ci/test/cluster/cluster-test.sh
#   artifact_paths: ./*.png;./*.mp4;./*.log
#   concurrency: 1
#   concurrency_group: "cluster-test"
#   timeout_in_minutes: 30
