steps:
  - group: ":bazel::go:Build backend for different platforms"
    key: "backend-builds"
    steps:
      - label: ':bazel::linux: Build for Linux'
        key: 'build-sourcegraph-app-linux'
        agents: { queue: bazel }
        env:
          PLATFORM: x86_64-unknown-linux-gnu
        command:
          - './dev/app/build-backend.sh'
      - label: ':bazel::mac: Build for MacOS arm64'
        key: 'build-sourcegraph-app-macos-arm64'
        agents: { queue: macos }
        env:
          PLATFORM: aarch64-apple-darwin
        command:
          - './dev/app/build-backend.sh'
      - label: ':go::mac:Build for MacOS x86_64'
        key: 'build-sourcegraph-app-macos-x86_64'
        depends_on: 'build-sourcegraph-app-macos-arm64'
        agents: { queue: macos }
        env:
          PLATFORM: x86_64-apple-darwin
          CROSS_COMPILE_X86_64_MACOS: 1
        command:
          - './dev/ci/pnpm-install-with-retry.sh'
          - './dev/app/build-backend.sh'
  - group: ":tauri: Bundle and sign using Tauri"
    key: "tauri-bundles"
    depends_on: "backend-builds"
    steps:
      - label: ':linux::tauri: Bundle with Tauri'
        key: 'linux-build-tauri-sourcegraph-app'
        agents: { queue: stateless }
        command:
          - './dev/ci/pnpm-install-with-retry.sh'
          - './dev/app/tauri-build.sh'
        env:
          SRC_APP_UPDATER_BUILD: 1
          AWS_CONFIG_FILE: /buildkite/.aws/config
          AWS_SHARED_CREDENTIALS_FILE: /buildkite/.aws/credentials
        plugins:
        - https://github.com/sourcegraph/cache-buildkite-plugin.git#master:
            backend: s3
            id: node_modules_pnpm
            key: cache-node_modules-pnpm-{{ checksum 'pnpm-lock.yaml' }}
            paths:
            - node_modules
            restore_keys:
            - cache-node_modules-pnpm-{{ checksum 'pnpm-lock.yaml' }}
            s3:
              bucket: sourcegraph_buildkite_cache
              endpoint: https://storage.googleapis.com
              profile: buildkite
              region: us-central1
            tarball: {}
      - label: ':macos::tauri: (arm64) Bundle and sign with Tauri'
        key: 'mac-build-arm64-tauri-sourcegraph-app'
        agents: { queue: macos }
        env:
          CODESIGNING: 1
          SRC_APP_UPDATER_BUILD: 1
        command:
          - './dev/ci/pnpm-install-with-retry.sh'
          - './dev/app/tauri-build.sh'
      - label: ':macos::tauri: (intel x86_64) Bundle and sign with Tauri'
        depends_on: 'mac-build-arm64-tauri-sourcegraph-app'
        key: 'mac-build-x86_64-tauri-sourcegraph-app'
        agents: { queue: macos }
        env:
          PLATFORM_OVERRIDE: "x86_64-apple-darwin"
          CODESIGNING: 1
          SRC_APP_UPDATER_BUILD: 1
        command:
          - './dev/ci/pnpm-install-with-retry.sh'
          - './dev/app/tauri-build.sh'
  - group: ":github: Create release and update manifest"
    depends_on: "tauri-bundles"
    steps:
      - label: ':github: Create GitHub release'
        agents: { queue: stateless }
        key: create-github-release
        command:
          - './dev/app/create-github-release.sh'
          - './dev/app/create-update-manifest.sh'
