env:
  ENTERPRISE: "1"
  DOCKER_BUILDKIT: "1"
  ENTERPRISE: "1"
  FORCE_COLOR: "1"
  GO111MODULE: "on"
  IMAGE: us.gcr.io/sourcegraph-dev/server:$TAG

steps:
- command:
  - yes | gcloud auth configure-docker
  - pushd enterprise
  - ./cmd/server/pre-build.sh
  - ./cmd/server/build.sh
  - popd
  - docker push "$IMAGE"
  env:
    PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
  label: ':docker:'

- wait

- artifact_paths: ./puppeteer/*.png;./web/e2e.mp4;./web/ffmpeg.log
  command:
    - yes | gcloud auth configure-docker
    - ./dev/ci/e2e.sh
  concurrency: 1
  concurrency_group: e2e
  label: ':chromium:'

- wait

- command: docker image rm -f "$IMAGE"
  label: ':sparkles:'
  soft_fail: true
