env:
  ENTERPRISE: "1"
  DOCKER_BUILDKIT: "1"
  ENTERPRISE: "1"
  FORCE_COLOR: "3"
  GO111MODULE: "on"
  IMAGE: "server_instrumented"
  TAG: "${BUILDKITE_BUILD_NUMBER}_${BUILDKITE_RETRY_COUNT}"
  COVERAGE_INSTRUMENT: "true"
  TEST_USER_PASSWORD: "SuperSecurePassword"

steps:
- artifact_paths: ./puppeteer/*.png;./web/e2e.mp4;./web/ffmpeg.log
  command:
    - pushd enterprise
    - ./cmd/server/pre-build.sh
    - ./cmd/server/build.sh
    - popd
    - ./dev/ci/e2e.sh
    - docker image rm -f "$IMAGE"
  timeout_in_minutes: 20
  label: ':docker::arrow_right::chromium:'
  agents:
    queue: 'baremetal'
