package codeowners_test

import (
	"reflect"
	"testing"

	"github.com/stretchr/testify/assert"

	"github.com/sourcegraph/sourcegraph/internal/own/codeowners"
	codeownerspb "github.com/sourcegraph/sourcegraph/internal/own/codeowners/v1"
)

type testCase struct {
	pattern string
	paths   []string
}

func TestFileOwnersMatch(t *testing.T) {
	cases := []testCase{
		{
			pattern: "filename",
			paths: []string{
				"/filename",
				"/prefix/filename",
			},
		},
		{
			pattern: "*.md",
			paths: []string{
				"/README.md",
				"/README.md.md",
				"/nested/index.md",
				"/weird/but/matching/.md",
			},
		},
		{
			// Regex components are interpreted literally.
			pattern: "[^a-z].md",
			paths: []string{
				"/[^a-z].md",
				"/nested/[^a-z].md",
			},
		},
		{
			pattern: "foo*bar*baz",
			paths: []string{
				"/foobarbaz",
				"/foo-bar-baz",
				"/foobarbazfoobarbazfoobarbaz",
			},
		},
		{
			pattern: "directory/path/",
			paths: []string{
				"/directory/path/file",
				"/directory/path/deeply/nested/file",
				"/prefix/directory/path/file",
				"/prefix/directory/path/deeply/nested/file",
			},
		},
		{
			pattern: "directory/path/**",
			paths: []string{
				"/directory/path/file",
				"/directory/path/deeply/nested/file",
				"/prefix/directory/path/file",
				"/prefix/directory/path/deeply/nested/file",
			},
		},
		{
			pattern: "directory/*",
			paths: []string{
				"/directory/file",
				"/prefix/directory/another_file",
			},
		},
		{
			pattern: "/toplevelfile",
			paths: []string{
				"/toplevelfile",
			},
		},
		{
			pattern: "/main/src/**/README.md",
			paths: []string{
				"/main/src/README.md",
				"/main/src/foo/bar/README.md",
			},
		},
	}
	for _, c := range cases {
		for _, path := range c.paths {
			pattern := c.pattern
			owner := []*codeownerspb.Owner{
				{Handle: "foo"},
			}
			file := codeowners.NewRuleset(&codeownerspb.File{
				Rule: []*codeownerspb.Rule{
					{Pattern: pattern, Owner: owner},
				},
			})
			got := file.FindOwners(path)
			if !reflect.DeepEqual(got, owner) {
				t.Errorf("want %q to match %q", pattern, path)
			}
		}
	}
}

func TestFileOwnersNoMatch(t *testing.T) {
	cases := []testCase{
		{
			pattern: "filename",
			paths: []string{
				"/prefix_filename_suffix",
				"/src/prefix_filename",
				"/finemale/nested",
			},
		},
		{
			pattern: "*.md",
			paths: []string{
				"/README.mdf",
				"/not/matching/without/the/dot/md",
			},
		},
		{
			// Regex components are interpreted literally.
			pattern: "[^a-z].md",
			paths: []string{
				"/-.md",
				"/nested/%.md",
			},
		},
		{
			pattern: "foo*bar*baz",
			paths: []string{
				"/foo-ba-baz",
				"/foobarbaz.md",
			},
		},
		{
			pattern: "directory/leaf/",
			paths: []string{
				// These do not match as the right-most directory name `leaf`
				// is just a prefix to the corresponding directory on the given path.
				"/directory/leaf_and_more/file",
				"/prefix/directory/leaf_and_more/file",
				// These do not match as the pattern matches anything within
				// the sub-directory tree, but not the directory itself.
				"/directory/leaf",
				"/prefix/directory/leaf",
			},
		},
		{
			pattern: "directory/leaf/**",
			paths: []string{
				// These do not match as the right-most directory name `leaf`
				// is just a prefix to the corresponding directory on the given path.
				"/directory/leaf_and_more/file",
				"/prefix/directory/leaf_and_more/file",
				// These do not match as the pattern matches anything within
				// the sub-directory tree, but not the directory itself.
				"/directory/leaf",
				"/prefix/directory/leaf",
			},
		},
		{
			pattern: "directory/*",
			paths: []string{
				"/directory/nested/file",
				"/directory/deeply/nested/file",
			},
		},
		{
			pattern: "/toplevelfile",
			paths: []string{
				"/toplevelfile/nested",
				"/notreally/toplevelfile",
			},
		},
		{
			pattern: "/main/src/**/README.md",
			paths: []string{
				"/main/src/README.mdf",
				"/main/src/README.md/looks-like-a-file-but-was-dir",
				"/main/src/foo/bar/README.mdf",
				"/nested/main/src/README.md",
				"/nested/main/src/foo/bar/README.md",
			},
		},
	}
	for _, c := range cases {
		for _, path := range c.paths {
			pattern := c.pattern
			owner := []*codeownerspb.Owner{
				{Handle: "foo"},
			}
			file := codeowners.NewRuleset(&codeownerspb.File{
				Rule: []*codeownerspb.Rule{
					{Pattern: pattern, Owner: owner},
				},
			})
			got := file.FindOwners(path)
			if got != nil {
				t.Errorf("want %q not to match %q", pattern, path)
			}
		}
	}
}

func TestFileOwnersOrder(t *testing.T) {
	wantOwner := []*codeownerspb.Owner{{Handle: "some-path-owner"}}
	file := codeowners.NewRuleset(&codeownerspb.File{
		Rule: []*codeownerspb.Rule{
			{
				Pattern: "/top-level-directory/",
				Owner:   []*codeownerspb.Owner{{Handle: "top-level-owner"}},
			},
			// The owner of the last matching pattern is being picked
			{
				Pattern: "some/path/*",
				Owner:   wantOwner,
			},
			{
				Pattern: "does/not/match",
				Owner:   []*codeownerspb.Owner{{Handle: "not-matching-owner"}},
			},
		},
	})
	got := file.FindOwners("/top-level-directory/some/path/main.go")
	assert.Equal(t, wantOwner, got)
}

func BenchmarkOwnersMatch(b *testing.B) {
	pattern := "/main/src/**/*README.md"
	paths := []string{
		"/main/src/README.md",
		"/main/src/foo/bar/README.md",
		"enterprise/internal/batches/BUILD.bazel",
		"enterprise/internal/batches/CODENOTIFY",
		"enterprise/internal/batches/background.go",
		"enterprise/internal/batches/doc.go",
		"enterprise/internal/batches/global/BUILD.bazel",
		"enterprise/internal/batches/global/global.go",
		"enterprise/internal/batches/global/global_test.go",
		"enterprise/internal/batches/graphql/BUILD.bazel",
		"enterprise/internal/batches/graphql/doc.go",
		"enterprise/internal/batches/graphql/ids.go",
		"enterprise/internal/batches/processor/BUILD.bazel",
		"enterprise/internal/batches/processor/bulk_processor.go",
		"enterprise/internal/batches/processor/bulk_processor_test.go",
		"enterprise/internal/batches/reconciler/BUILD.bazel",
		"enterprise/internal/batches/reconciler/executor.go",
		"enterprise/internal/batches/reconciler/executor_test.go",
		"enterprise/internal/batches/reconciler/fake_store_test.go",
		"enterprise/internal/batches/reconciler/main_test.go",
		"enterprise/internal/batches/reconciler/plan.go",
		"enterprise/internal/batches/reconciler/plan_test.go",
		"enterprise/internal/batches/reconciler/publication_state.go",
		"enterprise/internal/batches/reconciler/publication_state_test.go",
		"enterprise/internal/batches/reconciler/reconciler.go",
		"enterprise/internal/batches/reconciler/reconciler_test.go",
		"enterprise/internal/batches/rewirer/BUILD.bazel",
		"enterprise/internal/batches/rewirer/rewirer.go",
		"enterprise/internal/batches/rewirer/rewirer_test.go",
		"enterprise/internal/batches/scheduler/BUILD.bazel",
		"enterprise/internal/batches/scheduler/scheduler.go",
		"enterprise/internal/batches/scheduler/ticker.go",
		"enterprise/internal/batches/scheduler/ticker_test.go",
		"enterprise/internal/batches/search/BUILD.bazel",
		"enterprise/internal/batches/search/errors.go",
		"enterprise/internal/batches/search/syntax/BUILD.bazel",
		"enterprise/internal/batches/search/syntax/NOTICE",
		"enterprise/internal/batches/search/syntax/doc.go",
		"enterprise/internal/batches/search/syntax/parse_tree.go",
		"enterprise/internal/batches/search/syntax/parse_tree_test.go",
		"enterprise/internal/batches/search/syntax/parser.go",
		"enterprise/internal/batches/search/syntax/parser_test.go",
		"enterprise/internal/batches/search/syntax/scanner.go",
		"enterprise/internal/batches/search/syntax/scanner_test.go",
		"enterprise/internal/batches/search/syntax/tokentype_string.go",
		"enterprise/internal/batches/search/text.go",
		"enterprise/internal/batches/search/text_test.go",
		"enterprise/internal/batches/service/BUILD.bazel",
		"enterprise/internal/batches/service/mocks.go",
		"enterprise/internal/batches/service/service.go",
		"enterprise/internal/batches/service/service_apply_batch_change.go",
		"enterprise/internal/batches/service/service_apply_batch_change_test.go",
		"enterprise/internal/batches/service/service_test.go",
		"enterprise/internal/batches/service/ui_publication_states.go",
		"enterprise/internal/batches/service/ui_publication_states_test.go",
		"enterprise/internal/batches/service/workspace_resolver.go",
		"enterprise/internal/batches/service/workspace_resolver_test.go",
		"enterprise/internal/batches/sources/BUILD.bazel",
		"enterprise/internal/batches/sources/azuredevops.go",
		"enterprise/internal/batches/sources/azuredevops/types.go",
		"enterprise/internal/batches/sources/azuredevops_test.go",
		"enterprise/internal/batches/sources/bitbucketcloud.go",
		"enterprise/internal/batches/sources/bitbucketcloud/BUILD.bazel",
		"enterprise/internal/batches/sources/bitbucketcloud/types.go",
		"enterprise/internal/batches/sources/bitbucketcloud_test.go",
		"enterprise/internal/batches/sources/bitbucketserver.go",
		"enterprise/internal/batches/sources/bitbucketserver_test.go",
		"enterprise/internal/batches/sources/common.go",
		"enterprise/internal/batches/sources/github.go",
		"enterprise/internal/batches/sources/github_test.go",
		"enterprise/internal/batches/sources/gitlab.go",
		"enterprise/internal/batches/sources/gitlab_test.go",
		"enterprise/internal/batches/sources/main_test.go",
		"enterprise/internal/batches/sources/mocks_test.go",
		"enterprise/internal/batches/sources/sources.go",
		"enterprise/internal/batches/sources/sources_test.go",
		"enterprise/internal/batches/sources/testdata/golden/BitbucketServerSource_CloseChangeset_outdated",
		"enterprise/internal/batches/sources/testdata/golden/BitbucketServerSource_CloseChangeset_success",
		"enterprise/internal/batches/sources/testdata/golden/BitbucketServerSource_CreateChangeset_abbreviated_refs",
		"enterprise/internal/batches/sources/testdata/golden/BitbucketServerSource_CreateChangeset_already_exists",
		"enterprise/internal/batches/sources/testdata/golden/BitbucketServerSource_CreateChangeset_success",
		"enterprise/internal/batches/sources/testdata/golden/BitbucketServerSource_LoadChangeset_found",
		"enterprise/internal/batches/sources/testdata/golden/BitbucketServerSource_MergeChangeset_outdated",
		"enterprise/internal/batches/sources/testdata/golden/BitbucketServerSource_MergeChangeset_success",
		"enterprise/internal/batches/sources/testdata/golden/BitbucketServerSource_ReopenChangeset_outdated",
		"enterprise/internal/batches/sources/testdata/golden/BitbucketServerSource_ReopenChangeset_success",
		"enterprise/internal/batches/sources/testdata/golden/BitbucketServerSource_UpdateChangeset_outdated",
		"enterprise/internal/batches/sources/testdata/golden/BitbucketServerSource_UpdateChangeset_success",
		"enterprise/internal/batches/sources/testdata/golden/GithubSource_CloseChangeset_success",
		"enterprise/internal/batches/sources/testdata/golden/GithubSource_CreateChangeset_already_exists",
		"enterprise/internal/batches/sources/testdata/golden/GithubSource_CreateChangeset_success",
		"enterprise/internal/batches/sources/testdata/golden/GithubSource_GetFork_success_with_existing_changeset_and_existing_fork",
		"enterprise/internal/batches/sources/testdata/golden/GithubSource_GetFork_success_with_existing_changeset_and_new_fork",
		"enterprise/internal/batches/sources/testdata/golden/GithubSource_GetFork_success_with_new_changeset_and_existing_fork",
		"enterprise/internal/batches/sources/testdata/golden/GithubSource_GetFork_success_with_new_changeset_and_new_fork",
		"enterprise/internal/batches/sources/testdata/golden/GithubSource_LoadChangeset_found",
		"enterprise/internal/batches/sources/testdata/golden/GithubSource_ReopenChangeset_success",
		"enterprise/internal/batches/sources/testdata/golden/GithubSource_UpdateChangeset_success",
		"enterprise/internal/batches/sources/testdata/golden/GitlabSource_LoadChangeset_found",
		"enterprise/internal/batches/sources/testdata/golden/TestBitbucketServerSource_GetFork_success_with_existing_changeset_and_existing_fork",
		"enterprise/internal/batches/sources/testdata/golden/TestBitbucketServerSource_GetFork_success_with_existing_changeset_and_new_fork",
		"enterprise/internal/batches/sources/testdata/golden/TestBitbucketServerSource_GetFork_success_with_new_changeset_and_existing_fork",
		"enterprise/internal/batches/sources/testdata/golden/TestBitbucketServerSource_GetFork_success_with_new_changeset_and_new_fork",
		"enterprise/internal/batches/sources/testdata/sources/BitbucketServerSource_CloseChangeset_outdated.yaml",
		"enterprise/internal/batches/sources/testdata/sources/BitbucketServerSource_CloseChangeset_success.yaml",
		"enterprise/internal/batches/sources/testdata/sources/BitbucketServerSource_CreateChangeset_abbreviated_refs.yaml",
		"enterprise/internal/batches/sources/testdata/sources/BitbucketServerSource_CreateChangeset_already_exists.yaml",
		"enterprise/internal/batches/sources/testdata/sources/BitbucketServerSource_CreateChangeset_success.yaml",
		"enterprise/internal/batches/sources/testdata/sources/BitbucketServerSource_CreateComment_outdated.yaml",
		"enterprise/internal/batches/sources/testdata/sources/BitbucketServerSource_CreateComment_success.yaml",
		"enterprise/internal/batches/sources/testdata/sources/BitbucketServerSource_LoadChangeset_found.yaml",
		"enterprise/internal/batches/sources/testdata/sources/BitbucketServerSource_LoadChangeset_not-found.yaml",
		"enterprise/internal/batches/sources/testdata/sources/BitbucketServerSource_MergeChangeset_conflict.yaml",
		"enterprise/internal/batches/sources/testdata/sources/BitbucketServerSource_MergeChangeset_outdated.yaml",
		"enterprise/internal/batches/sources/testdata/sources/BitbucketServerSource_MergeChangeset_success.yaml",
		"enterprise/internal/batches/sources/testdata/sources/BitbucketServerSource_ReopenChangeset_outdated.yaml",
		"enterprise/internal/batches/sources/testdata/sources/BitbucketServerSource_ReopenChangeset_success.yaml",
		"enterprise/internal/batches/sources/testdata/sources/BitbucketServerSource_UpdateChangeset_outdated.yaml",
		"enterprise/internal/batches/sources/testdata/sources/BitbucketServerSource_UpdateChangeset_success.yaml",
		"enterprise/internal/batches/sources/testdata/sources/GithubSource_CloseChangeset_success.yaml",
		"enterprise/internal/batches/sources/testdata/sources/GithubSource_CreateChangeset_already-exists.yaml",
		"enterprise/internal/batches/sources/testdata/sources/GithubSource_CreateChangeset_already_exists.yaml",
		"enterprise/internal/batches/sources/testdata/sources/GithubSource_CreateChangeset_success.yaml",
		"enterprise/internal/batches/sources/testdata/sources/GithubSource_CreateComment_success.yaml",
		"enterprise/internal/batches/sources/testdata/sources/GithubSource_GetFork_not_a_fork.yaml",
		"enterprise/internal/batches/sources/testdata/sources/GithubSource_GetFork_success_with_existing_changeset_and_existing_fork.yaml",
		"enterprise/internal/batches/sources/testdata/sources/GithubSource_GetFork_success_with_existing_changeset_and_new_fork.yaml",
		"enterprise/internal/batches/sources/testdata/sources/GithubSource_GetFork_success_with_new_changeset_and_existing_fork.yaml",
		"enterprise/internal/batches/sources/testdata/sources/GithubSource_GetFork_success_with_new_changeset_and_new_fork.yaml",
		"enterprise/internal/batches/sources/testdata/sources/GithubSource_LoadChangeset_found.yaml",
		"enterprise/internal/batches/sources/testdata/sources/GithubSource_LoadChangeset_not-found.yaml",
		"enterprise/internal/batches/sources/testdata/sources/GithubSource_ReopenChangeset_success.yaml",
		"enterprise/internal/batches/sources/testdata/sources/GithubSource_UpdateChangeset_success.yaml",
		"enterprise/internal/batches/sources/testdata/sources/GitlabSource_CreateComment_success.yaml",
		"enterprise/internal/batches/sources/testdata/sources/GitlabSource_LoadChangeset_found.yaml",
		"enterprise/internal/batches/sources/testdata/sources/GitlabSource_LoadChangeset_not-found.yaml",
		"enterprise/internal/batches/sources/testdata/sources/GitlabSource_LoadChangeset_project-not-found.yaml",
		"enterprise/internal/batches/sources/testdata/sources/TestBitbucketServerSource_GetFork_bad_username.yaml",
		"enterprise/internal/batches/sources/testdata/sources/TestBitbucketServerSource_GetFork_not_a_fork.yaml",
		"enterprise/internal/batches/sources/testdata/sources/TestBitbucketServerSource_GetFork_not_forked_from_parent.yaml",
		"enterprise/internal/batches/sources/testdata/sources/TestBitbucketServerSource_GetFork_success_with_existing_changeset_and_existing_fork.yaml",
		"enterprise/internal/batches/sources/testdata/sources/TestBitbucketServerSource_GetFork_success_with_existing_changeset_and_new_fork.yaml",
		"enterprise/internal/batches/sources/testdata/sources/TestBitbucketServerSource_GetFork_success_with_new_changeset_and_existing_fork.yaml",
		"enterprise/internal/batches/sources/testdata/sources/TestBitbucketServerSource_GetFork_success_with_new_changeset_and_new_fork.yaml",
		"enterprise/internal/batches/sources/testdata/sources/TestDecorateMergeRequestData.yaml",
		"enterprise/internal/batches/sources/testdata/sources/TestDecorateMergeRequestData/fork.yaml",
		"enterprise/internal/batches/sources/testdata/sources/TestDecorateMergeRequestData/not_a_fork.yaml",
		"enterprise/internal/batches/sources/testing/BUILD.bazel",
		"enterprise/internal/batches/sources/testing/fake.go",
		"enterprise/internal/batches/sources/util.go",
		"enterprise/internal/batches/state/BUILD.bazel",
		"enterprise/internal/batches/state/changeset_events.go",
		"enterprise/internal/batches/state/changeset_history.go",
		"enterprise/internal/batches/state/counts.go",
		"enterprise/internal/batches/state/counts_test.go",
		"enterprise/internal/batches/state/main_test.go",
		"enterprise/internal/batches/state/state.go",
		"enterprise/internal/batches/state/state_test.go",
		"enterprise/internal/batches/store/BUILD.bazel",
		"enterprise/internal/batches/store/author/BUILD.bazel",
		"enterprise/internal/batches/store/author/author.go",
		"enterprise/internal/batches/store/author/author_test.go",
		"enterprise/internal/batches/store/batch_changes.go",
		"enterprise/internal/batches/store/batch_changes_test.go",
		"enterprise/internal/batches/store/batch_spec_execution_cache_entry.go",
		"enterprise/internal/batches/store/batch_spec_execution_cache_entry_test.go",
		"enterprise/internal/batches/store/batch_spec_resolution_jobs.go",
		"enterprise/internal/batches/store/batch_spec_resolution_jobs_test.go",
		"enterprise/internal/batches/store/batch_spec_workspace_execution_jobs.go",
		"enterprise/internal/batches/store/batch_spec_workspace_execution_jobs_test.go",
		"enterprise/internal/batches/store/batch_spec_workspace_files.go",
		"enterprise/internal/batches/store/batch_spec_workspace_files_test.go",
		"enterprise/internal/batches/store/batch_spec_workspaces.go",
		"enterprise/internal/batches/store/batch_spec_workspaces_test.go",
		"enterprise/internal/batches/store/batch_specs.go",
		"enterprise/internal/batches/store/batch_specs_test.go",
		"enterprise/internal/batches/store/bulk_operations.go",
		"enterprise/internal/batches/store/bulk_operations_test.go",
		"enterprise/internal/batches/store/changeset_events.go",
		"enterprise/internal/batches/store/changeset_events_test.go",
		"enterprise/internal/batches/store/changeset_jobs.go",
		"enterprise/internal/batches/store/changeset_jobs_test.go",
		"enterprise/internal/batches/store/changeset_specs.go",
		"enterprise/internal/batches/store/changeset_specs_test.go",
		"enterprise/internal/batches/store/changesets.go",
		"enterprise/internal/batches/store/changesets_test.go",
		"enterprise/internal/batches/store/codehost.go",
		"enterprise/internal/batches/store/codehost_test.go",
		"enterprise/internal/batches/store/integration_test.go",
		"enterprise/internal/batches/store/site_credentials.go",
		"enterprise/internal/batches/store/site_credentials_test.go",
		"enterprise/internal/batches/store/store.go",
		"enterprise/internal/batches/store/store_test.go",
		"enterprise/internal/batches/store/text_search.go",
		"enterprise/internal/batches/store/text_search_test.go",
		"enterprise/internal/batches/store/worker_batch_spec_resolution.go",
		"enterprise/internal/batches/store/worker_bulk_operations.go",
		"enterprise/internal/batches/store/worker_reconciler.go",
		"enterprise/internal/batches/store/worker_workspace_execution.go",
		"enterprise/internal/batches/store/worker_workspace_execution_test.go",
		"enterprise/internal/batches/syncer/BUILD.bazel",
		"enterprise/internal/batches/syncer/mocks_test.go",
		"enterprise/internal/batches/syncer/queue.go",
		"enterprise/internal/batches/syncer/queue_test.go",
		"enterprise/internal/batches/syncer/store.go",
		"enterprise/internal/batches/syncer/sync.go",
		"enterprise/internal/batches/syncer/sync_test.go",
		"enterprise/internal/batches/syncer/syncer.go",
		"enterprise/internal/batches/syncer/syncer_test.go",
		"enterprise/internal/batches/testing/BUILD.bazel",
		"enterprise/internal/batches/testing/batch_change.go",
		"enterprise/internal/batches/testing/batch_spec.go",
		"enterprise/internal/batches/testing/batch_spec_workspace_execution_jobs.go",
		"enterprise/internal/batches/testing/changeset.go",
		"enterprise/internal/batches/testing/changeset_spec.go",
		"enterprise/internal/batches/testing/clock.go",
		"enterprise/internal/batches/testing/config.go",
		"enterprise/internal/batches/testing/credentials.go",
		"enterprise/internal/batches/testing/db.go",
		"enterprise/internal/batches/testing/mock_repo_perms.go",
		"enterprise/internal/batches/testing/mock_sync_state.go",
		"enterprise/internal/batches/testing/org.go",
		"enterprise/internal/batches/testing/repos.go",
		"enterprise/internal/batches/testing/rsa.go",
		"enterprise/internal/batches/testing/specs.go",
		"enterprise/internal/batches/testing/user.go",
		"enterprise/internal/batches/types/BUILD.bazel",
		"enterprise/internal/batches/types/batch_change.go",
		"enterprise/internal/batches/types/batch_change_test.go",
		"enterprise/internal/batches/types/batch_spec.go",
		"enterprise/internal/batches/types/batch_spec_execution_cache_entry.go",
		"enterprise/internal/batches/types/batch_spec_resolution_job.go",
		"enterprise/internal/batches/types/batch_spec_test.go",
		"enterprise/internal/batches/types/batch_spec_workspace.go",
		"enterprise/internal/batches/types/batch_spec_workspace_execution_job.go",
		"enterprise/internal/batches/types/batch_spec_workspace_file.go",
		"enterprise/internal/batches/types/bulk_operation.go",
		"enterprise/internal/batches/types/changeset.go",
		"enterprise/internal/batches/types/changeset_event.go",
		"enterprise/internal/batches/types/changeset_event_test.go",
		"enterprise/internal/batches/types/changeset_job.go",
		"enterprise/internal/batches/types/changeset_spec.go",
		"enterprise/internal/batches/types/changeset_spec_test.go",
		"enterprise/internal/batches/types/changeset_test.go",
		"enterprise/internal/batches/types/code_host.go",
		"enterprise/internal/batches/types/reconciler.go",
		"enterprise/internal/batches/types/rewirer_mappings.go",
		"enterprise/internal/batches/types/scheduler/config/BUILD.bazel",
		"enterprise/internal/batches/types/scheduler/config/config.go",
		"enterprise/internal/batches/types/scheduler/config/config_test.go",
		"enterprise/internal/batches/types/scheduler/window/BUILD.bazel",
		"enterprise/internal/batches/types/scheduler/window/config.go",
		"enterprise/internal/batches/types/scheduler/window/config_test.go",
		"enterprise/internal/batches/types/scheduler/window/rate.go",
		"enterprise/internal/batches/types/scheduler/window/rate_test.go",
		"enterprise/internal/batches/types/scheduler/window/schedule.go",
		"enterprise/internal/batches/types/scheduler/window/schedule_test.go",
		"enterprise/internal/batches/types/scheduler/window/time.go",
		"enterprise/internal/batches/types/scheduler/window/time_test.go",
		"enterprise/internal/batches/types/scheduler/window/weekday.go",
		"enterprise/internal/batches/types/scheduler/window/weekday_test.go",
		"enterprise/internal/batches/types/scheduler/window/window.go",
		"enterprise/internal/batches/types/scheduler/window/window_test.go",
		"enterprise/internal/batches/types/site_credential.go",
		"enterprise/internal/batches/types/step_info.go",
		"enterprise/internal/batches/types/step_info_test.go",
		"enterprise/internal/batches/types/syncer.go",
		"enterprise/internal/batches/types/syncer_test.go",
		"enterprise/internal/batches/types/util.go",
		"enterprise/internal/batches/webhooks/BUILD.bazel",
		"enterprise/internal/batches/webhooks/batch_change.go",
		"enterprise/internal/batches/webhooks/batch_change_test.go",
		"enterprise/internal/batches/webhooks/changeset.go",
		"enterprise/internal/batches/webhooks/changeset_test.go",
		"enterprise/internal/batches/webhooks/event_types.go",
		"enterprise/internal/batches/webhooks/gql.go",
		"enterprise/internal/batches/webhooks/util.go",
		"enterprise/internal/batches/webhooks/webhooks.go",
	}
	owner := []*codeownerspb.Owner{
		{Handle: "foo"},
	}
	file := codeowners.NewRuleset(&codeownerspb.File{
		Rule: []*codeownerspb.Rule{
			{Pattern: pattern, Owner: owner},
			{Pattern: "/enterprise2/internal/batches/BUILD.bazel", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/CODENOTIFY", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/background.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/doc.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/global/BUILD.bazel", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/global/global.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/global/global_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/graphql/BUILD.bazel", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/graphql/doc.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/graphql/ids.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/processor/BUILD.bazel", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/processor/bulk_processor.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/processor/bulk_processor_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/reconciler/BUILD.bazel", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/reconciler/executor.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/reconciler/executor_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/reconciler/fake_store_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/reconciler/main_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/reconciler/plan.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/reconciler/plan_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/reconciler/publication_state.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/reconciler/publication_state_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/reconciler/reconciler.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/reconciler/reconciler_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/rewirer/BUILD.bazel", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/rewirer/rewirer.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/rewirer/rewirer_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/scheduler/BUILD.bazel", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/scheduler/scheduler.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/scheduler/ticker.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/scheduler/ticker_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/search/BUILD.bazel", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/search/errors.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/search/syntax/BUILD.bazel", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/search/syntax/NOTICE", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/search/syntax/doc.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/search/syntax/parse_tree.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/search/syntax/parse_tree_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/search/syntax/parser.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/search/syntax/parser_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/search/syntax/scanner.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/search/syntax/scanner_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/search/syntax/tokentype_string.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/search/text.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/search/text_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/service/BUILD.bazel", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/service/mocks.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/service/service.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/service/service_apply_batch_change.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/service/service_apply_batch_change_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/service/service_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/service/ui_publication_states.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/service/ui_publication_states_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/service/workspace_resolver.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/service/workspace_resolver_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/BUILD.bazel", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/azuredevops.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/azuredevops/types.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/azuredevops_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/bitbucketcloud.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/bitbucketcloud/BUILD.bazel", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/bitbucketcloud/types.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/bitbucketcloud_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/bitbucketserver.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/bitbucketserver_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/common.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/github.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/github_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/gitlab.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/gitlab_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/main_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/mocks_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/sources.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/sources_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/golden/BitbucketServerSource_CloseChangeset_outdated", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/golden/BitbucketServerSource_CloseChangeset_success", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/golden/BitbucketServerSource_CreateChangeset_abbreviated_refs", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/golden/BitbucketServerSource_CreateChangeset_already_exists", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/golden/BitbucketServerSource_CreateChangeset_success", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/golden/BitbucketServerSource_LoadChangeset_found", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/golden/BitbucketServerSource_MergeChangeset_outdated", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/golden/BitbucketServerSource_MergeChangeset_success", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/golden/BitbucketServerSource_ReopenChangeset_outdated", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/golden/BitbucketServerSource_ReopenChangeset_success", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/golden/BitbucketServerSource_UpdateChangeset_outdated", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/golden/BitbucketServerSource_UpdateChangeset_success", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/golden/GithubSource_CloseChangeset_success", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/golden/GithubSource_CreateChangeset_already_exists", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/golden/GithubSource_CreateChangeset_success", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/golden/GithubSource_GetFork_success_with_existing_changeset_and_existing_fork", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/golden/GithubSource_GetFork_success_with_existing_changeset_and_new_fork", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/golden/GithubSource_GetFork_success_with_new_changeset_and_existing_fork", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/golden/GithubSource_GetFork_success_with_new_changeset_and_new_fork", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/golden/GithubSource_LoadChangeset_found", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/golden/GithubSource_ReopenChangeset_success", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/golden/GithubSource_UpdateChangeset_success", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/golden/GitlabSource_LoadChangeset_found", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/golden/TestBitbucketServerSource_GetFork_success_with_existing_changeset_and_existing_fork", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/golden/TestBitbucketServerSource_GetFork_success_with_existing_changeset_and_new_fork", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/golden/TestBitbucketServerSource_GetFork_success_with_new_changeset_and_existing_fork", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/golden/TestBitbucketServerSource_GetFork_success_with_new_changeset_and_new_fork", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/BitbucketServerSource_CloseChangeset_outdated.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/BitbucketServerSource_CloseChangeset_success.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/BitbucketServerSource_CreateChangeset_abbreviated_refs.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/BitbucketServerSource_CreateChangeset_already_exists.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/BitbucketServerSource_CreateChangeset_success.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/BitbucketServerSource_CreateComment_outdated.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/BitbucketServerSource_CreateComment_success.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/BitbucketServerSource_LoadChangeset_found.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/BitbucketServerSource_LoadChangeset_not-found.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/BitbucketServerSource_MergeChangeset_conflict.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/BitbucketServerSource_MergeChangeset_outdated.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/BitbucketServerSource_MergeChangeset_success.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/BitbucketServerSource_ReopenChangeset_outdated.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/BitbucketServerSource_ReopenChangeset_success.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/BitbucketServerSource_UpdateChangeset_outdated.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/BitbucketServerSource_UpdateChangeset_success.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/GithubSource_CloseChangeset_success.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/GithubSource_CreateChangeset_already-exists.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/GithubSource_CreateChangeset_already_exists.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/GithubSource_CreateChangeset_success.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/GithubSource_CreateComment_success.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/GithubSource_GetFork_not_a_fork.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/GithubSource_GetFork_success_with_existing_changeset_and_existing_fork.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/GithubSource_GetFork_success_with_existing_changeset_and_new_fork.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/GithubSource_GetFork_success_with_new_changeset_and_existing_fork.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/GithubSource_GetFork_success_with_new_changeset_and_new_fork.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/GithubSource_LoadChangeset_found.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/GithubSource_LoadChangeset_not-found.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/GithubSource_ReopenChangeset_success.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/GithubSource_UpdateChangeset_success.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/GitlabSource_CreateComment_success.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/GitlabSource_LoadChangeset_found.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/GitlabSource_LoadChangeset_not-found.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/GitlabSource_LoadChangeset_project-not-found.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/TestBitbucketServerSource_GetFork_bad_username.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/TestBitbucketServerSource_GetFork_not_a_fork.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/TestBitbucketServerSource_GetFork_not_forked_from_parent.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/TestBitbucketServerSource_GetFork_success_with_existing_changeset_and_existing_fork.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/TestBitbucketServerSource_GetFork_success_with_existing_changeset_and_new_fork.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/TestBitbucketServerSource_GetFork_success_with_new_changeset_and_existing_fork.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/TestBitbucketServerSource_GetFork_success_with_new_changeset_and_new_fork.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/TestDecorateMergeRequestData.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/TestDecorateMergeRequestData/fork.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testdata/sources/TestDecorateMergeRequestData/not_a_fork.yaml", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testing/BUILD.bazel", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/testing/fake.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/sources/util.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/state/BUILD.bazel", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/state/changeset_events.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/state/changeset_history.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/state/counts.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/state/counts_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/state/main_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/state/state.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/state/state_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/BUILD.bazel", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/author/BUILD.bazel", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/author/author.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/author/author_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/batch_changes.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/batch_changes_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/batch_spec_execution_cache_entry.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/batch_spec_execution_cache_entry_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/batch_spec_resolution_jobs.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/batch_spec_resolution_jobs_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/batch_spec_workspace_execution_jobs.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/batch_spec_workspace_execution_jobs_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/batch_spec_workspace_files.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/batch_spec_workspace_files_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/batch_spec_workspaces.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/batch_spec_workspaces_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/batch_specs.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/batch_specs_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/bulk_operations.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/bulk_operations_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/changeset_events.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/changeset_events_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/changeset_jobs.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/changeset_jobs_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/changeset_specs.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/changeset_specs_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/changesets.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/changesets_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/codehost.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/codehost_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/integration_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/site_credentials.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/site_credentials_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/store.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/store_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/text_search.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/text_search_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/worker_batch_spec_resolution.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/worker_bulk_operations.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/worker_reconciler.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/worker_workspace_execution.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/store/worker_workspace_execution_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/syncer/BUILD.bazel", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/syncer/mocks_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/syncer/queue.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/syncer/queue_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/syncer/store.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/syncer/sync.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/syncer/sync_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/syncer/syncer.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/syncer/syncer_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/testing/BUILD.bazel", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/testing/batch_change.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/testing/batch_spec.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/testing/batch_spec_workspace_execution_jobs.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/testing/changeset.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/testing/changeset_spec.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/testing/clock.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/testing/config.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/testing/credentials.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/testing/db.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/testing/mock_repo_perms.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/testing/mock_sync_state.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/testing/org.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/testing/repos.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/testing/rsa.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/testing/specs.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/testing/user.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/BUILD.bazel", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/batch_change.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/batch_change_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/batch_spec.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/batch_spec_execution_cache_entry.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/batch_spec_resolution_job.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/batch_spec_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/batch_spec_workspace.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/batch_spec_workspace_execution_job.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/batch_spec_workspace_file.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/bulk_operation.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/changeset.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/changeset_event.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/changeset_event_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/changeset_job.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/changeset_spec.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/changeset_spec_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/changeset_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/code_host.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/reconciler.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/rewirer_mappings.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/scheduler/config/BUILD.bazel", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/scheduler/config/config.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/scheduler/config/config_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/scheduler/window/BUILD.bazel", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/scheduler/window/config.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/scheduler/window/config_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/scheduler/window/rate.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/scheduler/window/rate_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/scheduler/window/schedule.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/scheduler/window/schedule_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/scheduler/window/time.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/scheduler/window/time_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/scheduler/window/weekday.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/scheduler/window/weekday_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/scheduler/window/window.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/scheduler/window/window_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/site_credential.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/step_info.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/step_info_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/syncer.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/syncer_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/types/util.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/webhooks/BUILD.bazel", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/webhooks/batch_change.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/webhooks/batch_change_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/webhooks/changeset.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/webhooks/changeset_test.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/webhooks/event_types.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/webhooks/gql.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/webhooks/util.go", Owner: owner},
			{Pattern: "/enterprise2/internal/batches/webhooks/webhooks.go", Owner: owner},
		},
	})

	for _, path := range paths {
		// Warm cache.
		file.FindOwners(path)
	}

	for i := 0; i < b.N; i++ {
		for _, path := range paths {
			file.FindOwners(path)
		}
	}
}
