{
 "title": "GHE Feeder",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "percent done",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(ghe_feeder_processed)/ (sum(ghe_feeder_remaining_work) + sum(ghe_feeder_processed)) * 100"
    }
   ]
  },
  {
   "title": "failed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(ghe_feeder_failed)" }
   ]
  },
  {
   "title": "succeeded",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum (ghe_feeder_succeeded)" }
   ]
  },
  {
   "title": "remaining",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "ghe_feeder_remaining_work", "legendFormat": "remaining" }
   ]
  },
  {
   "title": "succeeded",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(ghe_feeder_succeeded[5m]))",
     "legendFormat": "succeeded"
    }
   ]
  },
  {
   "title": "failed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (err_type) (rate(ghe_feeder_failed[5m]))",
     "legendFormat": "failed {{err_type}}"
    }
   ]
  },
  {
   "title": "processed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(ghe_feeder_processed[5m]))",
     "legendFormat": "processed"
    }
   ]
  },
  {
   "title": "succeeded vs failed because of GHE",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (err_type) (rate(ghe_feeder_failed{err_type!=\"clone\"}[5m]))",
     "legendFormat": "failed {{err_type}}"
    },
    {
     "expr": "sum (rate(ghe_feeder_succeeded[5m]))",
     "legendFormat": "succeeded"
    }
   ]
  }
 ]
}