# Build docker images other than the main sourcegraph app.
# NOTE: It is expected to run this from the project root.

.PHONY: default gcloud xlang gitserver

default:
	@echo "Please select a target"

gcloud:
	echo ${GCLOUD_SERVICE_ACCOUNT} | base64 --decode > gcloud-service-account.json
	gcloud auth activate-service-account --key-file gcloud-service-account.json
	gcloud config set project sourcegraph-dev

xlang: gcloud
	cd xlang && $(MAKE)

gitserver: gcloud
	cd cmd/gitserver && ./build.sh
