const MAX_PROMPT_TOKEN_LENGTH = 7000
export const SOLUTION_TOKEN_LENGTH = 1000
export const MAX_HUMAN_INPUT_TOKENS = 1000
export const MAX_RECIPE_INPUT_TOKENS = 2000
export const MAX_CURRENT_FILE_TOKENS = 1000
export const MAX_RECIPE_SURROUNDING_TOKENS = 500
export const MAX_AVAILABLE_PROMPT_LENGTH = MAX_PROMPT_TOKEN_LENGTH - SOLUTION_TOKEN_LENGTH
export const CHARS_PER_TOKEN = 4
