#!/usr/bin/env bash

cd "$(dirname "${BASH_SOURCE[0]}")"

# $ROOT/cmd/symbols/.ctags.d
ctagsd=../../.ctags.d

cat "${ctagsd}"/*.ctags | awk '
BEGIN { print "// Code generated by gen.sh. DO NOT EDIT.\npackage ctags\nvar ctagsArgs = []string{" }
/^-/ { print "`" $0 "`,"}
END { print "}" }' > args.go

gofmt -w args.go
