DROP TRIGGER IF EXISTS codeintel_scip_documents_schema_versions_insert ON codeintel_scip_documents_schema_versions;
DROP FUNCTION IF EXISTS update_codeintel_scip_documents_schema_versions_insert();
DROP TABLE IF EXISTS codeintel_scip_documents_schema_versions;
