query FuzzyFinderQuery($query: String!) {
    search(query: $query) {
        results {
            results {
                ...FuzzyFinderSearchResult
            }
        }
    }
}

fragment FuzzyFinderSearchResult on SearchResult {
    ... on FileMatch {
        file {
            path
            url
            ...FileIcon_GitBlob
        }
        symbols {
            name
            kind
            location {
                url
            }
        }
        repository {
            name
            stars
        }
    }

    ... on Repository {
        name
        stars
    }
}
