# Melange-based replacement for https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/symbols/ctags-install-alpine.sh

package:
  name: ctags
  version: f95bb3497f53748c2b6afc7f298cff218103ab90
  epoch: 2
  description: "A maintained ctags implementation"
  target-architecture:
    - x86_64
  copyright:
    - paths:
      - "*"
      license: GPL-2.0
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - build-base
      - autoconf
      - automake
      - pkgconf
      - pkgconf-dev
      - busybox
      - ca-certificates-bundle
      - jansson-dev

pipeline:
  - uses: fetch
    with:
      uri: https://codeload.github.com/universal-ctags/ctags/tar.gz/${{package.version}}
      expected-sha256: 1cb9b090f5cefa7704032df4c6ea2aca09d0adf8b2739be0aa3d4aaa720d0079
  - name: Autogen
    runs: |
      ./autogen.sh
  - uses: autoconf/configure
    with:
      opts: |
        --program-prefix=universal- \
        --enable-json
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip
