# Melange-based replacement for https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/docker-images/syntax-highlighter/Dockerfile?L16

package:
  name: http-server-stabilizer
  version: 1.0.5
  epoch: 0
  description: "HTTP server stabilizer for unruly servers"
  target-architecture:
    - x86_64
  copyright:
    - paths:
      - "*"
      attestation: 'Copyright 2018 Sourcegraph, Inc.'
      license: 'Apache License 2.0'
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/sourcegraph/http-server-stabilizer/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha256: e568f2b407a09d288abfc41057e6b76a68d00f0cfe2d461d629263fa2fbba94e
  - uses: go/build
    with:
      packages: main.go
      prefix: /usr/local
      output: http-server-stabilizer
