package:
  name: p4cli
  version: 22.2
  epoch: 0
  description: "Command line interface for Perforce"
  target-architecture:
    - x86_64
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: http://cdist2.perforce.com/perforce/r${{package.version}}/bin.linux26x86_64/p4
      expected-sha256: 8bc10fca1c5a26262b4072deec76150a668581a9749d0504cd443084773d4fd0
      extract: false
  - runs: |
      chmod +x p4
      mkdir -p ${{targets.destdir}}/usr/local/bin/
      cp p4 ${{targets.destdir}}/usr/local/bin/p4
