package:
  name: s3proxy
  version: 2.0.0
  epoch: 6 # Independent from repo epoch
  description: 'Access other storage backends via the S3 API'
  target-architecture:
    - x86_64
  copyright:
    - paths:
        - '*'
      attestation: ''
      license: 'Apache License 2.0'
  dependencies:
    runtime:
      - openjdk-11
      - openjdk-11-default-jvm # Set Java 11 as default JVM

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - maven
      - openjdk-11
      - openjdk-11-default-jvm

pipeline:
  - uses: fetch
    with:
      # Package epoch is independent from repo epoch
      uri: https://github.com/sourcegraph/s3proxy/archive/refs/tags/s3proxy-${{package.version}}-3.tar.gz
      expected-sha256: 21583a5db1483ec89e1da0a2de3b1f9caaa79ce291dd0f7af5b9b1366567c515
      extract: true
  - runs: |
      JAVA_HOME=/usr/lib/jvm/java-11-openjdk/ mvn package -DskipTests
  - runs: |
      mkdir -p ${{targets.destdir}}/opt/
      chmod 755 target/s3proxy
      cp -r target/ ${{targets.destdir}}/opt/s3proxy
      cp src/main/resources/run-docker-container.sh ${{targets.destdir}}/opt/s3proxy
