sequenceDiagram
  Providers ->>+ LSIF provider: References(textDocument, position)

  loop
    LSIF provider  ->>+ GraphQL API: LSIF.References(position)
    GraphQL API   -->>- LSIF provider: references
    LSIF provider -->>- Providers: references
  end

  par
    Providers       ->>+ Search provider: References(textDocument, position)
    Search provider ->>+ GraphQL API: Regexp Search "repo:^repo$@commit"
    GraphQL API    -->>- Search provider: local references
  and
    Search provider ->>+ GraphQL API: Regexp Search "-repo:^repo$" index:true
    GraphQL API    -->>- Search provider: remote references
  end

  Search provider -->>- Providers: local references + remote references
