sequenceDiagram
  Executor          ->>+ Frontend: Dequeue()
  Frontend         -->>- Executor: job

  loop
    Executor          ->>+ Frontend: Heartbeat(self.id, [job.id])
    Frontend         -->>- Executor: Ok
  end

  loop
    Executor          ->>+ Frontend: AddExecutionLogEntry(job.id, exec output from each command)
    Frontend         -->>- Executor: Ok
  end

  Executor          ->>+ Frontend: GitClone(job.repo, job.commit)
  Frontend          ->>+ Gitserver: GitClone(job.repo, job.commit)
  Gitserver        -->>- Frontend: ...
  Frontend         -->>- Executor: ...

  Executor        ->>+ Firecracker: setupFirecracker()
  Firecracker    -->>- Executor: vm

  loop dockerStep in job.dockerSteps
    Executor      ->>+ Firecracker: exec(vm.id, dockerStep.image, dockerStep.command)
    Firecracker  -->>- Executor: exit code, output
  end

  loop dockerStep in job.srcCliSteps
    Executor      ->>+ Firecracker: exec(vm.id, srcCliStep.command)
    Firecracker  -->>- Executor: exit code, output
  end

  Executor        ->>+ Firecracker: teardownFirecracker(vm.id)
  Firecracker    -->>- Executor: Ok

  Executor          ->>+ Frontend: MarkComplete(job.id)
  Frontend         -->>- Executor: Ok
