package toprepos

var GoRepos = []Repo{
	{"github.com/docker/docker", "Docker - the open-source application container engine"},
	{"github.com/golang/go", "The Go programming language"},
	{"github.com/getlantern/lantern", ":izakaya_lantern: Open Internet for everyone. Lantern is a free application that delivers fast, reliable and secure access to the open Internet for users in censored regions. It uses a variety of techniques to stay unblocked, including domain fronting, p2p, and pluggable transports."},
	{"github.com/kubernetes/kubernetes", "Production-Grade Container Scheduling and Management"},
	{"github.com/gogits/gogs", "Gogs (Go Git Service) is a painless self-hosted Git service."},
	{"github.com/avelino/awesome-go", "A curated list of awesome Go frameworks, libraries and software"},
	{"github.com/syncthing/syncthing", "Open Source Continuous File Synchronization"},
	{"github.com/astaxie/build-web-application-with-golang", "A golang ebook intro how to build a web with golang"},
	{"github.com/grafana/grafana", "Gorgeous metric viz, dashboards & editors for Graphite, InfluxDB & OpenTSDB"},
	{"github.com/spf13/hugo", "A Fast and Flexible Static Site Generator built with love in GoLang"},
	{"github.com/coreos/etcd", "Distributed reliable key-value store for the most critical data of a distributed system"},
	{"github.com/github/hub", "hub helps you win at git."},
	{"github.com/influxdata/influxdb", "Scalable datastore for metrics, events, and real-time analytics"},
	{"github.com/go-martini/martini", "Classy web framework for Go"},
	{"github.com/cayleygraph/cayley", "An open-source graph database"},
	{"github.com/astaxie/beego", "beego is an open-source, high-performance web framework for the Go programming language."},
	{"github.com/inconshreveable/ngrok", "Introspected tunnels to localhost"},
	{"github.com/mholt/caddy", "Fast, cross-platform HTTP/2 web server with automatic HTTPS"},
	{"github.com/drone/drone", "Drone is a Continuous Delivery platform built on Docker, written in Go"},
	{"github.com/cockroachdb/cockroach", "A Scalable, Survivable, Strongly-Consistent SQL Database"},
	{"github.com/gin-gonic/gin", "Gin is a HTTP web framework written in Go (Golang). It features a Martini-like API with much better performance -- up to 40 times faster. If you need smashing performance, get yourself some Gin."},
	{"github.com/revel/revel", "A high productivity, full-stack web framework for the Go language."},
	{"github.com/nsqio/nsq", "A realtime distributed messaging platform"},
	{"github.com/hashicorp/consul", "Consul is a tool for service discovery, monitoring and configuration."},
	{"github.com/joewalnes/websocketd", "Turn any program that uses STDIN/STDOUT into a WebSocket server. Like inetd, but for WebSockets."},
	{"github.com/yudai/gotty", "Share your terminal as a web application"},
	{"github.com/buger/gor", "Gor is an open-source tool for capturing and replaying live HTTP traffic into a test environment in order to continuously test your system with real data. It can be used to increase confidence in code deployments, configuration changes and infrastructure changes."},
	{"github.com/coreos/rkt", "rkt is a container engine for Linux designed to be composable, secure, and built on standards"},
	{"github.com/prometheus/prometheus", "The Prometheus monitoring system and time series database."},
	{"github.com/junegunn/fzf", ":cherry_blossom: A command-line fuzzy finder written in Go"},
	{"github.com/mitchellh/packer", "Packer is a tool for creating identical machine images for multiple platforms from a single source configuration."},
	{"github.com/hashicorp/terraform", "Terraform is a tool for building, changing, and combining infrastructure safely and efficiently."},
	{"github.com/labstack/echo", "Fast and unfancy HTTP server framework for Go (Golang). Up to 10x faster than the rest."},
	{"github.com/hashicorp/vault", "A tool for managing secrets."},
	{"github.com/go-kit/kit", "A standard library for microservices."},
	{"github.com/gizak/termui", "Golang terminal dashboard"},
	{"github.com/kataras/iris", "The fastest web framework for Go in (THIS) Earth."},
	{"github.com/boltdb/bolt", "An embedded key/value database for Go."},
	{"github.com/flynn/flynn", "A next generation open source platform as a service (PaaS)"},
	{"github.com/golang/groupcache", "groupcache is a caching and cache-filling library, intended as a replacement for memcached in many cases."},
	{"github.com/rakyll/boom", "HTTP(S) load generator, ApacheBench (ab) replacement, written in Go"},
	{"github.com/CodisLabs/codis", "Proxy based Redis cluster solution supporting pipeline and scaling dynamically"},
	{"github.com/pingcap/tidb", "TiDB is a distributed NewSQL database compatible with MySQL protocol"},
	{"github.com/urfave/cli", "A simple, fast, and fun package for building command line apps in Go"},
	{"github.com/google/cadvisor", "Analyzes resource usage and performance characteristics of running containers."},
	{"github.com/schachmat/wego", "weather app for the terminal"},
	{"github.com/containous/traefik", "Træfɪk, a modern reverse proxy"},
	{"github.com/tylertreat/comcast", "Simulating shitty network connections so you can build better systems."},
	{"github.com/weaveworks/weave", "Simple, resilient multi-host Docker networking and more."},
	{"github.com/tsenart/vegeta", "HTTP load testing tool and library. It's over 9000!"},
	{"github.com/jinzhu/gorm", "The fantastic ORM library for Golang, aims to be developer friendly"},
	{"github.com/derekparker/delve", "Delve is a debugger for the Go programming language."},
	{"github.com/attic-labs/noms", "The versioned, forkable, syncable database"},
	{"github.com/cyfdecyf/cow", "HTTP proxy written in Go. COW can automatically identify blocked sites and use parent proxies to access."},
	{"github.com/gopherjs/gopherjs", "A compiler from Go to JavaScript for running Go code in a browser"},
	{"github.com/zyedidia/micro", "A modern and intuitive terminal-based text editor"},
	{"github.com/docker/swarm", "Swarm: a Docker-native clustering system"},
	{"github.com/minio/minio", "Minio is an object storage server compatible with Amazon S3 and licensed under Apache 2.0 License"},
	{"github.com/urfave/negroni", "Idiomatic HTTP Middleware for Golang"},
	{"github.com/tools/godep", "dependency tool for go"},
	{"github.com/github/git-lfs", "Git extension for versioning large files"},
	{"github.com/youtube/vitess", "vitess provides servers and tools which facilitate scaling of MySQL databases for large scale web services."},
	{"github.com/google/seesaw", "Seesaw v2 is a Linux Virtual Server (LVS) based load balancing platform."},
	{"github.com/hashicorp/serf", "Service orchestration and management tool."},
	{"github.com/julienschmidt/httprouter", "A high performance HTTP request router that scales well"},
	{"github.com/ncw/rclone", "\"rsync for cloud storage\" - Google Drive, Amazon Drive, S3, Dropbox, Backblaze B2, One Drive, Swift, Hubic, Cloudfiles, Google Cloud Storage, Yandex Files"},
	{"github.com/google/gxui", "An experimental Go cross platform UI library."},
	{"github.com/apex/apex", "Build, deploy, and manage AWS Lambda functions with ease (with Go support!)."},
	{"github.com/sosedoff/pgweb", "Cross-platform client for PostgreSQL databases"},
	{"github.com/docker/machine", "Machine management for a container-centric world"},
	{"github.com/Unknwon/the-way-to-go_ZH_CN", "《The Way to Go》中文译本，中文正式名《Go入门指南》"},
	{"github.com/dinedal/textql", "Execute SQL against structured text like CSV or TSV"},
	{"github.com/andlabs/ui", "Platform-native GUI library for Go."},
	{"github.com/nsf/gocode", "An autocompletion daemon for the Go programming language"},
	{"github.com/google/git-appraise", "Distributed code review system for Git repos"},
	{"github.com/Sirupsen/logrus", "Structured, pluggable logging for Go."},
	{"github.com/mozilla-services/heka", "DEPRECATED: Data collection and processing made easy."},
	{"github.com/sjwhitworth/golearn", "Machine Learning for Go"},
	{"github.com/elastic/beats", ":tropical_fish: Beats - Lightweight shippers for Elasticsearch & Logstash"},
	{"github.com/schollz/find", "High-precision indoor positioning framework for most wifi-enabled devices."},
	{"github.com/zenazn/goji", "Goji is a minimalistic web framework for Golang that's high in antioxidants."},
	{"github.com/peco/peco", "Simplistic interactive filtering tool"},
	{"github.com/valyala/fasthttp", "Fast HTTP package for Go. Tuned for high performance. Zero memory allocations in hot paths. Up to 10x faster than net/http"},
	{"github.com/dropbox/godropbox", "Common libraries for writing Go services/applications."},
	{"github.com/opencontainers/runc", "runc container cli tools"},
	{"github.com/kelseyhightower/confd", "Manage local application configuration files using templates and data from etcd or consul"},
	{"github.com/PuerkitoBio/goquery", "A little like that j-thing, only in Go."},
	{"github.com/burke/zeus", "Boot any rails app in under a second."},
	{"github.com/v2ray/v2ray-core", "A platform for building proxies to bypass network restrictions."},
	{"github.com/progrium/localtunnel", "Expose localhost servers to the Internet"},
	{"github.com/chrislusf/seaweedfs", "SeaweedFS is a simple and highly scalable distributed file system. There are two objectives:  to store billions of files! to serve the files fast! Instead of supporting full POSIX file system semantics, Seaweed-FS choose to implement only a key~file mapping. Similar to the word \"NoSQL\", you can call it as \"NoFS\"."},
	{"github.com/igrigorik/ga-beacon", "Google Analytics collector-as-a-service (using GA measurement protocol)."},
	{"github.com/blevesearch/bleve", "A modern text indexing library for go"},
	{"github.com/ha/doozerd", "A consistent distributed data store."},
	{"github.com/gorilla/mux", "A powerful URL router and dispatcher for golang."},
	{"github.com/hoisie/web", "The easiest way to create web applications with Go"},
	{"github.com/aws/aws-sdk-go", "AWS SDK for the Go programming language."},
	{"github.com/Masterminds/glide", "Package Management for Golang"},
	{"github.com/go-sql-driver/mysql", "Go MySQL Driver is a lightweight and fast MySQL driver for Go's (golang) database/sql package"},
	{"github.com/Workiva/go-datastructures", ""},
	{"github.com/fiorix/freegeoip", "IP geolocation web server"},
	{"github.com/spf13/cobra", "A Commander for modern Go CLI interactions"},
	{"github.com/rancher/os", "Tiny Linux distro that runs the entire OS as Docker containers"},
	{"github.com/shazow/ssh-chat", "Chat over SSH."},
	{"github.com/eBay/fabio", "A fast, modern, zero-conf load balancing HTTP(S) router for deploying microservices managed by consul."},
	{"github.com/tmrts/go-patterns", "A curated list of Go patterns and idioms"},
	{"github.com/gorilla/websocket", "A WebSocket implementation for Go."},
	{"github.com/docker/distribution", "The Docker toolset to pack, ship, store, and deliver content"},
	{"github.com/ant0ine/go-json-rest", "A quick and easy way to setup a RESTful JSON API"},
	{"github.com/gliderlabs/registrator", "Service registry bridge for Docker with pluggable adapters"},
	{"github.com/garyburd/redigo", "Go client for Redis"},
	{"github.com/mailgun/godebug", "A cross-platform debugger for Go."},
	{"github.com/micro/micro", "A microservice toolkit"},
	{"github.com/DisposaBoy/GoSublime", "A Golang plugin collection for SublimeText **3**, providing code completion and other IDE-like features."},
	{"github.com/fogleman/nes", "NES emulator written in Go."},
	{"github.com/facebookgo/grace", "Graceful restart & zero downtime deploy for Go servers."},
	{"github.com/robertkrimen/otto", "A JavaScript interpreter in Go (golang)"},
	{"github.com/nats-io/gnatsd", "High-Performance server for NATS, the cloud native messaging system."},
	{"github.com/mjibson/goread", "RSS reader in go on app engine"},
	{"github.com/nlf/dlite", "The simplest way to use Docker on OS X"},
	{"github.com/hybridgroup/gobot", "Golang framework for robotics, drones, and the Internet of Things (IoT)"},
	{"github.com/pksunkara/alpaca", "Given a web API, Generate client libraries in node, php, python, ruby"},
	{"github.com/lib/pq", "Pure Go Postgres driver for database/sql"},
	{"github.com/grpc/grpc-go", "The Go language implementation of gRPC. HTTP/2 based RPC"},
	{"github.com/coreos/fleet", "A Distributed init System"},
	{"github.com/karan/joe", ":running: A .gitignore magician in your command line"},
	{"github.com/stretchr/testify", "A sacred extension to the standard go testing package"},
	{"github.com/ipfs/go-ipfs", "IPFS implementation in go"},
	{"github.com/go-gorp/gorp", "Go Relational Persistence - an ORM-ish library for Go"},
	{"github.com/cortesi/devd", "A local webserver for developers"},
	{"github.com/FiloSottile/Heartbleed", "A checker (site and tool) for CVE-2014-0160"},
	{"github.com/itsabot/abot", "Abot makes it easy and fun to build your own digital assistant, and we include everything you need to get started."},
	{"github.com/ethereum/go-ethereum", "Official golang implementation of the Ethereum protocol"},
	{"github.com/jteeuwen/go-bindata", "A small utility which generates Go code from any file. Useful for embedding binary data in a Go program."},
	{"github.com/emirpasic/gods", "Go Data Structures. Containers, Sets, Lists, Stacks, Maps, BidiMaps, Trees, HashSet, TreeSet, ArrayList, SinglyLinkedList, DoublyLinkedList, LinkedListStack, ArrayStack, HashMap, TreeMap, HashBidiMap, TreeBidiMap, RedBlackTree, BTree, BinaryHeap, Comparator, Iterator, Enumerable, Sort"},
	{"github.com/vulcand/vulcand", "Programmatic load balancer backed by Etcd"},
	{"github.com/docker/libchan", "Like Go channels over the network"},
	{"github.com/gliderlabs/logspout", "Log routing for Docker container logs"},
	{"github.com/tsuru/tsuru", "Open source, extensible and Docker-based Platform as a Service (PaaS)."},
	{"github.com/flike/kingshard", "A high-performance MySQL proxy"},
	{"github.com/jmoiron/sqlx", "general purpose extensions to golang's database/sql"},
	{"github.com/Unknwon/go-fundamental-programming", "《Go编程基础》是一套针对 Google 出品的 Go 语言的视频语音教程，主要面向新手级别的学习者。"},
	{"github.com/russross/blackfriday", "Blackfriday: a markdown processor for Go"},
	{"github.com/future-architect/vuls", "Vulnerability scanner for Linux/FreeBSD, agentless, written in Go"},
	{"github.com/coreybutler/nvm-windows", "A node.js version management utility for Windows. Ironically written in Go."},
	{"github.com/spf13/viper", "Go configuration with fangs"},
	{"github.com/fatedier/frp", "A fast reverse proxy to help you expose a local server behind a NAT or firewall to the internet."},
	{"github.com/github/gh-ost", "GitHub's Online Schema Migrations for MySQL"},
	{"github.com/bosun-monitor/bosun", "Time Series Alerting Framework"},
	{"github.com/remind101/empire", "A PaaS built on top of Amazon EC2 Container Service (ECS)"},
	{"github.com/google/go-github", "Go library for accessing the GitHub API"},
	{"github.com/shadowsocks/shadowsocks-go", "go port of shadowsocks"},
	{"github.com/golang/mobile", "[mirror] Go on Mobile"},
	{"github.com/hashicorp/nomad", "A Distributed, Highly Available, Datacenter-Aware Scheduler"},
	{"github.com/jgrahamc/httpdiff", "Perform the same request against two HTTP servers and diff the results"},
	{"github.com/camlistore/camlistore", "Camlistore is your personal storage system for life: a way of storing, syncing, sharing, modelling and backing up content."},
	{"github.com/rqlite/rqlite", "Replicating SQLite using the Raft consensus protocol"},
	{"github.com/fogleman/ln", "3D line art engine."},
	{"github.com/phuslu/goproxy", "a go proxy"},
	{"github.com/direnv/direnv", "Unclutter your .profile"},
	{"github.com/influxdata/telegraf", "The plugin-driven server agent for collecting & reporting metrics."},
	{"github.com/ory-am/hydra", "Run your very own low-latency, api-only, cloud native OAuth2 and OpenID Connect provider within minutes. Integrates with existing authentication mechanisms. Written in Google Go."},
	{"github.com/emicklei/go-restful", "package for building REST-style Web Services using Google Go"},
	{"github.com/google/battery-historian", "Battery Historian is a tool to analyze battery consumers using Android \"bugreport\" files."},
	{"github.com/yahoo/gryffin", "Gryffin is a large scale web security scanning platform"},
	{"github.com/siddontang/ledisdb", "a high performance NoSQL powered by Go"},
	{"github.com/mitchellh/gox", "A dead simple, no frills Go cross compile tool"},
	{"github.com/xtaci/kcptun", "An extremely simple udp tunnel based on KCP."},
	{"github.com/dgraph-io/dgraph", "Scalable, Distributed, Low Latency Graph Database"},
	{"github.com/qor/qor", "QOR is a set of libraries written in Go that abstracts common features needed for business applications, CMSs, and E-commerce systems."},
	{"github.com/sourcegraph/thyme", "Automatically track which applications you use and for how long."},
	{"github.com/huichen/wukong", "高度可定制的全文搜索引擎"},
	{"github.com/constabulary/gb", "gb, the project based build tool for Go"},
	{"github.com/hashicorp/consul-template", "Generic template rendering and notifications with Consul"},
	{"github.com/go-qml/qml", "QML support for the Go language"},
	{"github.com/openshift/origin", "Enterprise-Ready Kubernetes for Developers"},
	{"github.com/miekg/dns", "DNS library in Go"},
	{"github.com/monochromegane/the_platinum_searcher", "A code search tool similar to ack and the_silver_searcher(ag). It supports multi platforms and multi encodings."},
	{"github.com/soundcloud/roshi", "Roshi is a large-scale CRDT set implementation for timestamped events."},
	{"github.com/zxh0/jvm.go", "A JVM written in Go"},
	{"github.com/bradfitz/http2", "old repo for HTTP/2 support for Go (see README for new home)"},
	{"github.com/astaxie/Go-in-Action", "Trying to complete over 100 projects in various categories in golang."},
	{"github.com/jwilder/docker-gen", "Generate files from docker container meta-data"},
	{"github.com/motemen/gore", "Yet another Go REPL that works nicely. Featured with line editing, code completion, and more."},
	{"github.com/davidlazar/vuvuzela", "Private messaging system that hides metadata"},
	{"github.com/elastic/logstash-forwarder", "An experiment to cut logs in preparation for processing elsewhere. Replaced by Filebeat: https://github.com/elastic/beats/tree/master/filebeat"},
	{"github.com/gernest/utron", "A lightweight MVC framework for Go(Golang)"},
	{"github.com/HouzuoGuo/tiedot", "Your NoSQL database powered by Golang"},
	{"github.com/nsf/termbox-go", "Pure Go termbox implementation"},
	{"github.com/redspread/spread", "Docker to Kubernetes in one command"},
	{"github.com/coreos/flannel", "flannel is an etcd backed network fabric for containers"},
	{"github.com/polaris1119/The-Golang-Standard-Library-by-Example", "Golang标准库。对于程序员而言，标准库与语言本身同样重要，它好比一个百宝箱，能为各种常见的任务提供完美的解决方案。以示例驱动的方式讲解Golang的标准库。"},
	{"github.com/codegangsta/gin", "Live reload utility for Go web servers"},
	{"github.com/variadico/noti", "Trigger notifications when a process completes."},
	{"github.com/cloudflare/cfssl", "CFSSL: CloudFlare's PKI and TLS toolkit"},
	{"github.com/tidwall/tile38", "Tile38 is a geolocation data store, spatial index, and realtime geofence. It supports a variety of object types including lat/lon points, bounding boxes, XYZ tiles, Geohashes, and GeoJSON."},
	{"github.com/elves/elvish", "A novel Unix shell"},
	{"github.com/getqujing/qtunnel", "A secure socket tunnel works on getqujing.com"},
	{"github.com/dvyukov/go-fuzz", "Randomized testing for Go"},
	{"github.com/NVIDIA/nvidia-docker", "Build and run Docker containers leveraging NVIDIA GPUs"},
	{"github.com/NYTimes/gizmo", "A Microservice Toolkit from The New York Times"},
	{"github.com/bitly/oauth2_proxy", "A reverse proxy that provides authentication with Google, Github or other provider"},
	{"github.com/rcrowley/goagain", "Zero-downtime restarts in Go"},
	{"github.com/benmanns/goworker", "goworker is a Go-based background worker that runs 10 to 100,000* times faster than Ruby-based workers."},
	{"github.com/dgrijalva/jwt-go", "Golang implementation of JSON Web Tokens (JWT)"},
	{"github.com/golang/lint", "This is a linter for Go source code."},
	{"github.com/pquerna/ffjson", "faster JSON serialization for Go"},
	{"github.com/henrylee2cn/pholcus", "[Crawler for Golang] Pholcus is a distributed, high concurrency and powerful web crawler software."},
	{"github.com/jingweno/ccat", "Colorizing `cat`"},
	{"github.com/uber/go-torch", "Stochastic flame graph profiler for Go programs"},
	{"github.com/xenolf/lego", "Let's Encrypt client and ACME library written in Go"},
	{"github.com/bitly/go-simplejson", "a Go package to interact with arbitrary JSON"},
	{"github.com/sourcegraph/checkup", "Distributed, lock-free, self-hosted health checks and status pages"},
	{"github.com/rapidloop/rtop", "rtop is an interactive, remote system monitoring tool based on SSH"},
	{"github.com/lxn/walk", "A Windows GUI toolkit for the Go Programming Language"},
	{"github.com/goraft/raft", "UNMAINTAINED: A Go implementation of the Raft distributed consensus protocol."},
	{"github.com/zquestz/s", "Open a web search in your terminal."},
	{"github.com/skynetservices/skynet", "Skynet is a framework for distributed services in Go."},
	{"github.com/go-xorm/xorm", "Simple and Powerful ORM for Go, support mysql,postgres,tidb,sqlite3,mssql,oracle"},
	{"github.com/TykTechnologies/tyk", "Tyk Open Source API Gateway written in Go"},
	{"github.com/kabukky/journey", "A blog engine written in Go, compatible with Ghost themes."},
	{"github.com/mperham/inspeqtor", "Monitor your application infrastructure!"},
	{"github.com/ardanlabs/gotraining", "Go Training Class Material :"},
	{"github.com/coreos/clair", "Vulnerability Static Analysis for Containers"},
	{"github.com/astaxie/bat", "Go implement CLI, cURL-like tool for humans"},
	{"github.com/prasmussen/gdrive", "Google Drive CLI Client"},
	{"github.com/Shopify/toxiproxy", ":alarm_clock: :fire: A proxy to simulate network and system conditions"},
	{"github.com/googollee/go-socket.io", "socket.io library for golang, a realtime application framework."},
	{"github.com/gocircuit/circuit", "Circuit: Dynamic cloud orchestration http://gocircuit.org"},
	{"github.com/coreos/torus", "Torus Distributed Storage"},
	{"github.com/letsencrypt/boulder", "An ACME-based CA, written in Go."},
	{"github.com/uber-common/cpustat", "high frequency performance measurements for Linux"},
	{"github.com/go-bootstrap/go-bootstrap", "Generates a lean and mean Go web project."},
	{"github.com/Terry-Mao/gopush-cluster", "Golang push server cluster"},
	{"github.com/laher/goxc", "a build tool for Go, with a focus on cross-compiling, packaging and deployment"},
	{"github.com/rcrowley/go-metrics", "Go port of Coda Hale's Metrics library"},
	{"github.com/yuin/gopher-lua", "GopherLua: VM and compiler for Lua in Go"},
	{"github.com/anacrolix/torrent", "Full-featured BitTorrent client package and utilities"},
	{"github.com/elazarl/goproxy", "An HTTP proxy library for Go"},
	{"github.com/goadesign/goa", "Design-based microservices in Go"},
	{"github.com/convox/rack", "Open-source Platform for AWS"},
	{"github.com/maruel/panicparse", "Crash your app in style (Golang)"},
	{"github.com/nanopack/yoke", "Postgres high-availability cluster with auto-failover and automated cluster recovery."},
	{"github.com/howeyc/fsnotify", "File system notification for Go"},
	{"github.com/nytlabs/streamtools", "tools for working with streams of data"},
	{"github.com/kubernetes/minikube", "Run Kubernetes locally"},
	{"github.com/pachyderm/pachyderm", "Containerized Data Analytics"},
	{"github.com/asaskevich/govalidator", "[Go] Package of validators and sanitizers for strings, numerics, slices and structs"},
	{"github.com/sideshow/apns2", "⚡ HTTP/2 Apple Push Notification Service (APNs) push provider for Go — Send push notifications to iOS, tvOS, and OSX apps, using the new APNs HTTP/2 protocol."},
	{"github.com/Shopify/sarama", "Sarama is a Go library for Apache Kafka 0.8, 0.9, and 0.10."},
	{"github.com/pressly/sup", "Super simple deployment tool - just Unix - think of it like 'make' for a network of servers"},
	{"github.com/syndtr/goleveldb", "LevelDB key/value database in Go."},
	{"github.com/go-macaron/macaron", "Package macaron is a high productive and modular web framework in Go."},
	{"github.com/google/novm", "Experimental KVM-based VMM, written in Go."},
	{"github.com/cdarwin/go-koans", "koans for go"},
	{"github.com/shirou/gopsutil", "psutil for golang"},
	{"github.com/tealeg/xlsx", "Google Go (golang) library for reading and writing XLSX files."},
	{"github.com/golang/protobuf", "Go support for Google's protocol buffers"},
	{"github.com/koding/kite", "Micro-service framework in Go"},
	{"github.com/centrifugal/centrifugo", "Real-time messaging (Websockets or SockJS) server in Go"},
	{"github.com/iamduo/workq", "Job server in Go"},
	{"github.com/fogleman/pt", "A path tracer written in Go."},
	{"github.com/nwidger/nintengo", "An NES emulator written in Go"},
	{"github.com/vmware/harbor", "An enterprise-class container registry server based on Docker Distribution"},
	{"github.com/uber-go/zap", "Fast, structured, leveled logging in Go"},
	{"github.com/tombh/texttop", "A fully interactive X Linux desktop rendered in TTY and streamable over SSH"},
	{"github.com/onsi/ginkgo", "BDD Testing Framework for Go"},
	{"github.com/nfnt/resize", "Pure golang image resizing"},
	{"github.com/rakyll/coop", "Cheat sheet for some of the common concurrent flows in Go"},
	{"github.com/ansible-semaphore/semaphore", "Open Source Alternative to Ansible Tower"},
	{"github.com/chrislusf/glow", "Glow is an easy-to-use distributed computation system written in Go, similar to Hadoop Map Reduce, Spark, Flink, Storm, etc."},
	{"github.com/mattn/gom", "Go Manager - bundle for go"},
	{"github.com/mailhog/MailHog", "Web and API based SMTP testing"},
	{"github.com/rakyll/gom", "A visual interface to work with runtime profiling data for Go"},
	{"github.com/ChimeraCoder/gojson", "Automatically generate golang struct definitions from example JSON"},
	{"github.com/FiloSottile/whosthere", "A ssh server that knows who you are. $ ssh whoami.filippo.io"},
	{"github.com/whyrusleeping/gx", "A package management tool"},
	{"github.com/anthonynsimon/bild", "A collection of parallel image processing algorithms in pure Go"},
	{"github.com/alecthomas/gometalinter", "Concurrently run Go lint tools and normalise their output"},
	{"github.com/gocraft/web", "Go Router + Middleware. Your Contexts."},
	{"github.com/smira/aptly", "aptly - Debian repository management tool"},
	{"github.com/gpmgo/gopm", "Go Package Manager (gopm) is a package manager and build tool for Go."},
	{"github.com/micro/go-micro", "A pluggable RPC microservice framework"},
	{"github.com/Terry-Mao/goim", "goim"},
	{"github.com/coocood/freecache", "A cache library for Go with zero GC overhead."},
	{"github.com/hyperhq/hyperd", "HyperContainer Daemon"},
	{"github.com/visualfc/goqt", "Golang bindings to the Qt cross-platform application framework."},
	{"github.com/lxc/lxd", "Daemon based on liblxc offering a REST API to manage containers"},
	{"github.com/golang/glog", "Leveled execution logs for Go"},
	{"github.com/fatih/color", "Color package for Go (golang)"},
	{"github.com/go-redis/redis", "Redis client for Golang"},
	{"github.com/ravenac95/sudolikeaboss", "Get 1password access from iterm2"},
	{"github.com/pierrre/imageserver", "Image server toolkit in Go"},
	{"github.com/Yelp/dockersh", "A shell which places users into individual docker containers"},
	{"github.com/tidwall/buntdb", "BuntDB is a fast, embeddable, in-memory key/value database for Go with custom indexing and geospatial support"},
	{"github.com/zachlatta/sshtron", "Play Tron over SSH"},
	{"github.com/hyperledger-archives/fabric", "THIS IS A READ-ONLY historic repository. Current development is at https://gerrit.hyperledger.org/r/#/admin/projects/fabric . pull requests not accepted"},
	{"github.com/fsnotify/fsnotify", "File system notifications for Go."},
	{"github.com/dancannon/gorethink", "Go language driver for RethinkDB"},
	{"github.com/PuerkitoBio/gocrawl", "Polite, slim and concurrent web crawler."},
	{"github.com/fvbock/endless", "Zero downtime restarts for go servers (Drop in replacement for http.ListenAndServe)"},
	{"github.com/gravitational/teleport", "SSH infrastructure for clusters and teams. Want to chat/see a demo? mailto:info@gravitational.com"},
	{"github.com/davecgh/go-spew", "Implements a deep pretty printer for Go data structures to aid in debugging"},
	{"github.com/crosbymichael/skydock", "Service discovery via DNS for docker"},
	{"github.com/BurntSushi/toml", "TOML parser for Golang with reflection."},
	{"github.com/arachnys/athenapdf", "Drop-in replacement for wkhtmltopdf built on Go, Electron and Docker"},
	{"github.com/fatih/structs", "Utilities for Go structs"},
	{"github.com/svent/sift", "A fast and powerful alternative to grep"},
	{"github.com/thewhitetulip/web-dev-golang-anti-textbook", "Learn how to write webapps without a framework in Go."},
	{"github.com/kardianos/govendor", "Go vendor tool that works with the standard vendor file."},
	{"github.com/robfig/cron", "a cron library for go"},
	{"github.com/pkg/errors", "Simple error handling primitives"},
	{"github.com/RichardKnop/machinery", "Machinery is an asynchronous task queue/job queue based on distributed message passing."},
	{"github.com/justinas/alice", "Painless middleware chaining for Go"},
	{"github.com/appc/spec", "App Container Specification and Tooling"},
	{"github.com/rach/pome", "A Postgres Metrics Dashboard"},
	{"github.com/cloudflare/redoctober", "Go server for two-man rule style file encryption and decryption."},
	{"github.com/bmizerany/pat", "ul"},
	{"github.com/golang/tools", "[mirror] Go Tools"},
	{"github.com/go-gomail/gomail", "The best way to send emails in Go."},
	{"github.com/jwilder/docker-squash", "Squash docker images to make them smaller"},
	{"github.com/go-mgo/mgo", "The MongoDB driver for Go. See http://labix.org/mgo for details."},
	{"github.com/tianon/gosu", "Simple Go-based setuid+setgid+setgroups+exec"},
	{"github.com/RangelReale/osin", "Golang OAuth2 server library"},
	{"github.com/hlandau/acme", ":lock: acmetool, an automatic certificate acquisition tool for ACME (Let's Encrypt)"},
	{"github.com/haxpax/gosms", ":mailbox_closed: Your own local SMS gateway in Go"},
	{"github.com/rcrowley/go-tigertonic", "A Go framework for building JSON web services inspired by Dropwizard"},
	{"github.com/streadway/amqp", "Go client for AMQP 0.9.1"},
	{"github.com/go-mangos/mangos", "package mangos is an implementation in pure Go of the SP (\"Scalable Protocols\") protocols."},
	{"github.com/intelsdi-x/snap", "The open telemetry framework"},
	{"github.com/arnauddri/algorithms", "Algorithms & Data Structures in Go"},
	{"github.com/btcsuite/btcd", "An alternative full node bitcoin implementation written in Go (golang)"},
	{"github.com/yhat/scrape", "A simple, higher level interface for Go web scraping."},
	{"github.com/xiam/hyperfox", "HTTP/HTTPs MITM proxy and traffic recorder with on-the-fly TLS cert generation."},
	{"github.com/docker/swarmkit", "A toolkit for orchestrating distributed systems at any scale. It includes primitives for node discovery, raft-based consensus, task scheduling and more."},
	{"github.com/mehrdadrad/mylg", "Network Diagnostic Tool"},
	{"github.com/docker/libcontainer", "PROJECT MOVED TO RUNC"},
	{"github.com/gravitational/teleconsole", "Command line tool to share your UNIX terminal and forward local TCP ports to people you trust."},
	{"github.com/ddollar/forego", "Foreman in Go"},
	{"github.com/go-zoo/bone", "Lightning Fast HTTP Multiplexer"},
	{"github.com/concourse/concourse", "BOSH Release"},
	{"github.com/src-d/go-git", "A low level and highly extensible git client library"},
	{"github.com/go-yaml/yaml", "YAML support for the Go language."},
	{"github.com/gtank/cryptopasta", "copy & paste-friendly golang crypto"},
	{"github.com/antonholmquist/jason", "Easy-to-use JSON Library for Go"},
	{"github.com/coreos/dex", "OpenID Connect Identity (OIDC) and OAuth 2.0 Provider with Pluggable Connectors"},
	{"github.com/influxdata/surgemq", "High-Performance MQTT Server and Client Libraries"},
	{"github.com/Masterminds/squirrel", "Fluent SQL generation for golang"},
	{"github.com/josephyzhou/github-trending", "Tracking the most popular Github repos, updated daily"},
	{"github.com/google/stenographer", "Stenographer is a packet capture solution which aims to quickly spool all packets to disk, then provide simple, fast access to subsets of those packets.  Discussion/announcements at stenographer@googlegroups.com"},
	{"github.com/yahoo/webseclab", "set of web security test cases and a toolkit to construct new ones"},
	{"github.com/disintegration/imaging", "Simple Go image processing package"},
	{"github.com/facette/facette", "Time series data visualization and graphing software"},
	{"github.com/tobyhede/go-underscore", "Helpfully Functional Go -  A useful collection of Go utilities. Designed for programmer happiness."},
	{"github.com/pravj/geopattern", "Create beautiful generative image patterns from a string in golang."},
	{"github.com/emc-advanced-dev/unik", "The Unikernel Compilation and Deployment Platform"},
	{"github.com/libgit2/git2go", "Git to Go. Like McDonald's but tastier."},
	{"github.com/uniqush/uniqush-push", "Uniqush is a free and open source software system which provides a unified push service for server side notification to apps on mobile devices."},
	{"github.com/bradfitz/goimports", "(old repo) Tool to fix (add, remove) your Go imports automatically."},
	{"github.com/digitalocean/doctl", "A command line tool for DigitalOcean services"},
	{"github.com/sourcegraph/srclib", "srclib is a polyglot code analysis library, built for hackability. It consists of language analysis toolchains (currently for Go and Java, with Python, JavaScript, and Ruby in beta) with a common output format, and a CLI tool for running the analysis."},
	{"github.com/ajvb/kala", "Modern Job Scheduler"},
	{"github.com/leveros/leveros", "Serverless + Microservices = ♥"},
	{"github.com/fsouza/go-dockerclient", "Go client for the Docker remote API."},
	{"github.com/codetainerapp/codetainer", "A Docker container in your browser."},
	{"github.com/mattn/go-gtk", "Go binding for GTK"},
	{"github.com/restic/restic", "restic backup program"},
	{"github.com/goadapp/goad", "Goad is an AWS Lambda powered, highly distributed, load testing tool"},
	{"github.com/michaelmacinnis/oh", "A surprisingly powerful Unix shell"},
	{"github.com/cloudson/gitql", "A git query language"},
	{"github.com/h2non/imaginary", "Fast HTTP microservice for high-level image processing. Perfectly fitted for Docker and Heroku."},
	{"github.com/google/codesearch", "Fast, indexed regexp search over large file trees"},
	{"github.com/golang/oauth2", "Go OAuth2"},
	{"github.com/divan/expvarmon", "TermUI based monitor for Go apps using expvars (/debug/vars). Quickest way to monitor your Go app(s)."},
	{"github.com/nats-io/nats", "Golang client for NATS, the cloud native messaging system."},
	{"github.com/gosuri/uiprogress", "A go library to render progress bars in terminal applications"},
	{"github.com/ahmetalpbalkan/go-linq", ".NET LINQ-like query methods for Go"},
	{"github.com/markbates/goth", "Package goth provides a simple, clean, and idiomatic way to write authentication packages for Go web applications."},
	{"github.com/olivere/elastic", "Elasticsearch client for Go."},
	{"github.com/parnurzeal/gorequest", "GoRequest -- Simplified HTTP client ( inspired by nodejs SuperAgent )"},
	{"github.com/euphoria-io/heim", "A real-time community platform."},
	{"github.com/nanobox-io/nanobox", "Local Development Done Right"},
	{"github.com/mindreframer/golang-stuff", "interesting go libs"},
	{"github.com/GoesToEleven/GolangTraining", "Training for Golang (go language)"},
	{"github.com/disintegration/gift", "Go Image Filtering Toolkit"},
	{"github.com/osrg/gobgp", "BGP implemented in the Go Programming Language"},
	{"github.com/agl/pond", "Pond"},
	{"github.com/grpc-ecosystem/grpc-gateway", "gRPC to JSON proxy generator"},
	{"github.com/hoisie/mustache", "The mustache template language in Go"},
	{"github.com/weaveworks/scope", "Monitoring, visualisation & management for Docker & Kubernetes"},
	{"github.com/adrianco/spigo", "Simulate Protocol Interactions in Go"},
	{"github.com/golang/example", "Go example projects"},
	{"github.com/kubernetes/heapster", "Compute Resource Usage Analysis and Monitoring of Container Clusters"},
	{"github.com/mattbaird/elastigo", "A Go (golang) based Elasticsearch client library."},
	{"github.com/flosch/pongo2", "Django-syntax like template-engine for Go"},
	{"github.com/gitchain/gitchain", "Decentralized, peer-to-peer Git repositories aka \"Git meets Bitcoin\""},
	{"github.com/cheggaaa/pb", "Console progress bar for Golang"},
	{"github.com/name5566/leaf", "A game server framework in Go (golang)"},
	{"github.com/GeertJohan/go.rice", "go.rice is a Go package that makes working with resources such as html,js,css,images,templates, etc very easy."},
	{"github.com/laurent22/massren", "massren - easily rename multiple files using your text editor"},
	{"github.com/victorcoder/dkron", "Dkron - Distributed, fault tolerant job scheduling system http://dkron.io"},
	{"github.com/youtube/doorman", "Doorman: Global Distributed Client Side Rate Limiting."},
	{"github.com/tylerb/graceful", "Graceful is a Go package enabling graceful shutdown of an http.Handler server."},
	{"github.com/oikomi/FishChatServer", "鱼传尺素--纯golang编写的分布式可伸缩IM服务器(兼备智能硬件管理)"},
	{"github.com/oleiade/trousseau", "Networked and encrypted key-value database"},
	{"github.com/allegro/bigcache", "Efficient cache for gigabytes of data written in Go."},
	{"github.com/cloudfoundry-attic/lattice-release", "Lattice"},
	{"github.com/jroimartin/gocui", "Minimalist Go package aimed at creating Console User Interfaces."},
	{"github.com/pengwynn/flint", "Check your project for common sources of contributor friction."},
	{"github.com/pilu/fresh", "[ABANDONED] Build and (re)start go web apps after saving/creating/deleting source files."},
	{"github.com/hashicorp/raft", "Golang implementation of the Raft consensus protocol"},
	{"github.com/gocql/gocql", "Package gocql implements a fast and robust Cassandra client for the Go programming language."},
	{"github.com/jrallison/go-workers", "Sidekiq compatible background workers in golang"},
	{"github.com/Unknwon/go-web-foundation", "《Go Web基础》是一套针对 Google 出品的 Go 语言的视频语音教程，主要面向完成《Go编程基础》教程后希望进一步了解有关 Go Web 开发的学习者。"},
	{"github.com/mozilla/mig", "Distributed & real time digital forensics at the speed of the cloud"},
	{"github.com/heroku/hk", "DEPRECATED: see"},
	{"github.com/ajstarks/svgo", "Go Language Library for SVG generation"},
	{"github.com/looterz/grimd", ":zap: fast dns proxy that can run anywhere, built to black-hole internet advertisements and malware servers"},
	{"github.com/nitrous-io/goop", "A simple dependency manager for Go (golang), inspired by Bundler."},
	{"github.com/vulcand/oxy", "Go middlewares for HTTP servers & proxies"},
	{"github.com/go-llvm/llgo", "LLVM-based compiler for Go"},
	{"github.com/adonovan/gopl.io", "Example programs from \"The Go Programming Language\""},
	{"github.com/google/gopacket", "Provides packet processing capabilities for Go"},
	{"github.com/julienschmidt/go-http-routing-benchmark", "Go HTTP request router and web framework benchmark"},
	{"github.com/dustin/go-humanize", "Go Humans! (formatters for units to human friendly sizes)"},
	{"github.com/google/google-api-go-client", "Auto-generated Google APIs for Go"},
	{"github.com/kidoman/embd", "Embedded Programming Framework in Go"},
	{"github.com/opencontainers/runtime-spec", "OCI Runtime Specification"},
	{"github.com/jondot/groundcontrol", "Manage and monitor your Raspberry Pi with ease"},
	{"github.com/Shopify/go-lua", "A Lua VM in Go"},
	{"github.com/s3git/s3git", "s3git: git for Cloud Storage. Distributed Version Control for Data. Create decentralized and versioned repos that scale infinitely to 100s of millions of files. Clone huge PB-scale repos on your local SSD to make changes, commit and push back. Oh yeah, it dedupes too and offers directory versioning."},
	{"github.com/SummitRoute/osxlockdown", "[No longer maintained] Apple OS X tool to audit for, and remediate, security configuration settings."},
	{"github.com/mattes/migrate", "Database migration handling in Golang"},
	{"github.com/rsms/gotalk", "Async peer communication protocol & library"},
	{"github.com/barnybug/cli53", "Command line tool for Amazon Route 53"},
	{"github.com/keybase/client", "Keybase Go Library, Client, Service, OS X, iOS, Android, Electron"},
	{"github.com/levigross/grequests", "A Go \"clone\" of the great and famous Requests library"},
	{"github.com/hashicorp/hcl", "HCL is the HashiCorp configuration language."},
	{"github.com/docker/libnetwork", "Docker Networking"},
	{"github.com/jingweno/gh", "Fast GitHub command line client (deprecated). gh has been merged into https://github.com/github/hub, see https://github.com/github/hub/issues/475 for more info"},
	{"github.com/sensu/uchiwa", "Uchiwa is a simple dashboard for the Sensu monitoring framework."},
	{"github.com/jamescun/switcher", "Run SSH and HTTP(S) on the same port"},
	{"github.com/chanxuehong/wechat.v2", "weixin/wechat/微信公众平台/微信企业号/微信商户平台/微信支付 go/golang sdk"},
	{"github.com/alecthomas/kingpin", "A Go (golang) command line and flag parser"},
	{"github.com/cihub/seelog", "Seelog is a native Go logging library that provides flexible asynchronous dispatching, filtering, and formatting."},
	{"github.com/gocircuit/escher", "Escher: A language for programming in metaphors http://escher.io"},
	{"github.com/jpillora/overseer", "Monitorable, gracefully restarting, self-upgrading binaries in Go (golang)"},
	{"github.com/rlmcpherson/s3gof3r", "Fast, concurrent, streaming access to Amazon S3, including gof3r, a CLI. http://godoc.org/github.com/rlmcpherson/s3gof3r"},
	{"github.com/tylertreat/BoomFilters", "Probabilistic data structures for processing continuous, unbounded streams."},
	{"github.com/unrolled/render", "Go package for easily rendering JSON, XML, binary data, and HTML templates responses."},
	{"github.com/amyhaber/cnki-downloader", "知网(CNKI)文献下载工具"},
	{"github.com/clipperhouse/gen", "Type-driven code generation for Go"},
	{"github.com/docopt/docopt.go", "A command-line arguments parser that will make you smile."},
	{"github.com/hu17889/go_spider", "[爬虫框架 (golang)] An awesome Go concurrent Crawler(spider) framework. The crawler is flexible and modular. It can be expanded to an Individualized crawler easily or you can use the default crawl components only."},
	{"github.com/jondot/blade", "Better asset workflow for iOS developers. Generate Xcode image catalogs for iOS / OSX app icons, universal images, and more."},
	{"github.com/yinghuocho/firefly-proxy", "A proxy software to help circumventing the Great Firewall."},
	{"github.com/go-authboss/authboss", "The boss of http auth."},
	{"github.com/skizzehq/skizze", "A probabilistic data structure service and storage"},
	{"github.com/knq/xo", "Command line tool to generate idiomatic Go code for SQL databases supporting PostgreSQL, MySQL, SQLite, Oracle, and Microsoft SQL Server"},
	{"github.com/celrenheit/lion", "Lion is a fast HTTP router for building modern scalable modular REST APIs in Go"},
	{"github.com/jwilder/dockerize", "Utility to simplify running applications in docker containers"},
	{"github.com/docker/notary", "Notary is a Docker project that allows anyone to have trust over arbitrary collections of data"},
	{"github.com/vektorlab/slackcat", "CLI utility to post files and command output to slack"},
	{"github.com/ehazlett/interlock", "Docker Event Driven Plugin System"},
	{"github.com/vektra/templar", "A HTTP proxy to improve usage of HTTP APIs"},
	{"github.com/xtaci/gonet", "A game server skeleton in golang."},
	{"github.com/oniony/TMSU", "TMSU lets you tags your files and then access them through a nifty virtual filesystem from any other application."},
	{"github.com/jordan-wright/email", "Robust and flexible email library for Go"},
	{"github.com/ssllabs/ssllabs-scan", "A command-line reference-implementation client for SSL Labs APIs, designed for automated and/or bulk testing."},
	{"github.com/sourcegraph/webloop", "WebLoop: Scriptable, headless WebKit with a Go API. Like PhantomJS, but for Go."},
	{"github.com/AsynkronIT/gam", "Go Actor Model framework - Ultra fast distributed actors for Golang"},
	{"github.com/quarnster/completion", "This project aims to implement an editor and language agnostic backend"},
	{"github.com/matryer/silk", "Markdown based document-driven RESTful API testing."},
	{"github.com/op/go-logging", "Golang logging library"},
	{"github.com/jinzhu/now", "Now is a time toolkit for golang"},
	{"github.com/mitchellh/mapstructure", "Go library for decoding generic map values into native Go structures."},
	{"github.com/jackc/pgx", "PostgreSQL client library for Go"},
	{"github.com/spf13/afero", "A FileSystem Abstraction System for Go"},
	{"github.com/shurcooL/Go-Package-Store", "An app that displays updates for the Go packages in your GOPATH."},
	{"github.com/ksimka/go-is-not-good", "A curated list of articles complaining that go (golang) isn't good enough"},
	{"github.com/QubitProducts/bamboo", "HAProxy auto configuration and auto service discovery for Mesos Marathon"},
	{"github.com/go-swagger/go-swagger", "Swagger 2.0 implementation for go"},
	{"github.com/nlopes/slack", "Slack API in Go"},
	{"github.com/cznic/ql", "Package ql is a pure Go embedded SQL database."},
	{"github.com/justinas/nosurf", "CSRF protection middleware for Go."},
	{"github.com/michaelsauter/crane", "Crane - Lift containers with ease"},
	{"github.com/go-playground/validator", ":100:Go Struct and Field validation, including Cross Field, Cross Struct, Map, Slice and Array diving"},
	{"github.com/tdewolff/minify", "Go minifiers for web formats"},
	{"github.com/tockins/realize", "Go build system with file watchers, live reload and output streams. Run, build and watch file changes with custom paths"},
	{"github.com/shiyanhui/dht", "BitTorrent DHT Protocol && DHT Spider"},
	{"github.com/abh/geodns", "DNS server with per-client targeted responses"},
	{"github.com/lgtmco/lgtm", "LGTM is a simple pull request approval system"},
	{"github.com/ugorji/go", "idiomatic codec and rpc lib for msgpack, cbor, json, etc. msgpack.org[Go]"},
	{"github.com/Unknwon/build-web-application-with-golang_EN", "Someone stole my work and violated license, shame on him."},
	{"github.com/tidwall/gjson", "Get JSON values very quickly in Go"},
	{"github.com/reconquest/orgalorg", "Parallel SSH commands executioner and file synchronization tool"},
	{"github.com/JoelOtter/termloop", "Terminal-based game engine for Go, built on top of Termbox"},
	{"github.com/kisielk/errcheck", "errcheck checks that you checked errors."},
	{"github.com/dghubble/gologin", "Chainable Go login handlers for authentication providers (OAuth1, OAuth2)"},
	{"github.com/joushou/sshmuxd", "sshmux frontend"},
	{"github.com/bradfitz/gomemcache", "Go Memcached client library #golang"},
	{"github.com/aws/amazon-ecs-agent", "Amazon EC2 Container Service Agent"},
	{"github.com/eaigner/hood", "Database agnostic ORM for Go"},
	{"github.com/motemen/ghq", "Remote repository management made easy"},
	{"github.com/kardianos/service", "Run go programs as a service on major platforms."},
	{"github.com/cloudfoundry/cli", "The official command line client for Cloud Foundry"},
	{"github.com/trustmaster/goflow", "Flow-based and dataflow programming library for Go programming language"},
	{"github.com/zachlatta/postman", "Command-line utility for batch-sending email."},
	{"github.com/nsqio/go-nsq", "The official Go package for NSQ"},
	{"github.com/google/btree", "ul"},
	{"github.com/chzyer/readline", "Readline is a pure go(golang) implementation for GNU-Readline kind library"},
	{"github.com/fogleman/gg", "Go Graphics - 2D rendering in Go with a simple API."},
	{"github.com/vzex/dog-tunnel", "p2p tunnel,(udp mode work with kcp,https://github.com/skywind3000/kcp)"},
	{"github.com/ory-am/fosite", "Extensible security first OAuth2 and OpenID Connect framework for Google's Go Language."},
	{"github.com/eknkc/amber", "Amber is an elegant templating engine for Go Programming Language, inspired from HAML and Jade"},
	{"github.com/mitchellh/goamz", "Golang Amazon Library"},
	{"github.com/hellogcc/100-gdb-tips", "A collection of gdb tips. 100 maybe just mean many here."},
	{"github.com/huichen/sego", "Go中文分词"},
	{"github.com/codahale/sneaker", "A tool for securely storing secrets on S3 using Amazon KMS."},
	{"github.com/mop-tracker/mop", "Stock market tracker for hackers"},
	{"github.com/satori/go.uuid", "UUID package for Go"},
	{"github.com/montanaflynn/stats", "A statistics package with common functions that are missing from the Golang standard library."},
	{"github.com/remogatto/mandala", "A Go framework for writing native Android applications"},
	{"github.com/golang/gddo", "Go Doc Dot Org"},
	{"github.com/hashicorp/envconsul", "Read and set environmental variables for processes from Consul."},
	{"github.com/nitrous-io/tug", "Docker development workflow"},
	{"github.com/getgauge/gauge", "Light weight cross-platform test automation"},
	{"github.com/jessevdk/go-flags", "go command line option parser"},
	{"github.com/dougblack/sleepy", "rest for go"},
	{"github.com/azer/boxcars", "Easy-to-configure Static Web & Reverse Proxy Server in Go"},
	{"github.com/sanathp/statusok", "Monitor your Website and APIs from your Computer. Get Notified through Slack, E-mail when your server is down or response time is more than expected."},
	{"github.com/influxdata/kapacitor", "Open source framework for processing, monitoring, and alerting on time series data"},
	{"github.com/astaxie/beedb", "beedb is a go ORM,support database/sql interface，pq/mysql/sqlite"},
	{"github.com/bradfitz/talk-yapc-asia-2015", "talk-yapc-asia-2015"},
	{"github.com/jgrahamc/webwatch", "Small program to download a web page, see if a string appears in it and send email if it does"},
	{"github.com/knadh/niltalk", "A multi-room disposable chat service written in Go that uses WebSockets for live communication."},
	{"github.com/jfrazelle/binctr", "Fully static, unprivileged, self-contained, containers as executable binaries."},
	{"github.com/jimmykuu/gopher", "Golang-China(golangtc.com) Website"},
	{"github.com/astaxie/gopkg", "example for the go pkg's function"},
	{"github.com/benjojo/totp-ssh-fluxer", "Take security by obscurity to the next level (You must be insane to run this)"},
	{"github.com/braintree/manners", "A polite Go HTTP server that shuts down gracefully."},
	{"github.com/shell909090/goproxy", "基于go写的隧道代理服务器，主要用于翻墙。"},
	{"github.com/golang/net", "[mirror] Go supplementary network libraries"},
	{"github.com/patrickmn/go-cache", "An in-memory key:value store/cache (similar to Memcached) library for Go, suitable for single-machine applications."},
	{"github.com/docker-slim/docker-slim", "DockerSlim (docker-slim): Optimize and secure your Docker containers (free and open source)"},
	{"github.com/marmelab/gaudi", "Gaudi allows to share multi-component applications, based on Docker, Go, and YAML."},
	{"github.com/tidwall/redcon", "Fast Redis compatible server framework for Go"},
	{"github.com/outbrain/orchestrator", "MySQL replication topology manager/visualizer"},
	{"github.com/leo-stone/hack-petya", "search key to restore petya encrypted mft"},
	{"github.com/inconshreveable/go-update", "Build self-updating Golang programs"},
	{"github.com/davecheney/gcvis", "Visualise Go program GC trace data in real time"},
	{"github.com/helm/helm-classic", "Helm Classic - The Kubernetes Package Manager"},
	{"github.com/hpcloud/tail", "Go package for reading from continously updated files (tail -f)"},
	{"github.com/joushou/serve2d", "Protocol detecting server"},
	{"github.com/sourcegraph/appdash", "Application tracing system for Go, based on Google's Dapper."},
	{"github.com/mailru/easyjson", "Fast JSON serializer for golang."},
	{"github.com/ChimeraCoder/anaconda", "A Go client library for the Twitter 1.1 API"},
	{"github.com/sausheong/polyglot", "Polyglot is a distributed web framework that allows programmers to create web applications in multiple programming languages"},
	{"github.com/HewlettPackard/gas", "Go AST Scanner"},
	{"github.com/puma/puma-dev", "A tool to manage rack apps in development with puma"},
	{"github.com/gengo/goship", "A simple tool for deploying code to servers."},
	{"github.com/stretchr/goweb", "A lightweight RESTful web framework for Go"},
	{"github.com/irfansharif/cfilter", "Cuckoo Filter implementation in Go, better than Bloom Filters"},
	{"github.com/reborndb/reborn", "Distributed database fully compatible with redis protocol"},
	{"github.com/funny/link", "Go语言网络层脚手架"},
	{"github.com/gavv/httpexpect", "End-to-end HTTP and REST API testing for Go."},
	{"github.com/coreos/coreos-kubernetes", "CoreOS+Kubernetes documentation, Vagrant & AWS installers"},
	{"github.com/dullgiulio/pingo", "Plugins for Go"},
	{"github.com/martinkirsche/wired-logic", "Wired Logic - a pixel based logic simulator"},
	{"github.com/moul/advanced-ssh-config", ":computer: assh: ssh wrapper using ProxyCommand that adds regex, aliases, gateways, includes, dynamic hostnames to SSH and ssh-config"},
	{"github.com/gocraft/dbr", "Additions to Go's database/sql for super fast performance and convenience."},
	{"github.com/tcnksm/gcli", "The easy way to build Golang command-line application."},
	{"github.com/apcera/libretto", "Libretto is a Golang library to create Virtual Machines (VMs) on any cloud and Virtual Machine hosting platforms such as AWS, Azure, OpenStack, vSphere, or VirtualBox."},
	{"github.com/justone/dockviz", "Visualizing docker data"},
	{"github.com/buger/jsonparser", "Alternative JSON parser for Go that does not require schema (so far fastest)"},
	{"github.com/gogo/protobuf", "Protocol Buffers for Go with Gadgets"},
	{"github.com/kovetskiy/manul", ":smirk_cat: The madness vendoring utility for Golang programs"},
	{"github.com/netvarun/docket", "Docket - Custom docker registry that allows for lightning fast deploys through bittorrent"},
	{"github.com/mkaz/working-with-go", "A set of example golang code to start learning Go"},
	{"github.com/Jeffail/gabs", "For parsing, creating and editing unknown or dynamic JSON in golang"},
	{"github.com/graphql-go/graphql", "An implementation of GraphQL for Go / Golang"},
	{"github.com/monochromegane/go_design_pattern", "Design patterns in Golang."},
	{"github.com/scottferg/Fergulator", "NES emulator, written in Go"},
	{"github.com/willnorris/imageproxy", "A caching, resizing image proxy written in Go"},
	{"github.com/thejerf/suture", "Supervisor trees for Go."},
	{"github.com/sipin/gorazor", "Razor view engine for Golang"},
	{"github.com/square/go-jose", "An implementation of JOSE standards in Golang."},
	{"github.com/robpike/ivy", "ivy, an APL-like calculator"},
	{"github.com/yields/phony", "tiny command line fake data generator"},
	{"github.com/Unknwon/go-rock-libraries-showcases", "《Go名库讲解》是一套针对 Google 出品的 Go 语言的第三方库进行评测讲解的集博客、示例与语音视频为一体的综合教程，适合完成学习完成《Go编程基础》教程的学习者。"},
	{"github.com/kahing/goofys", "a Filey System for Amazon S3 written in Go"},
	{"github.com/mefellows/muxy", "Simulating real-world distributed system failures"},
	{"github.com/hanwen/go-fuse", "FUSE bindings for Go"},
	{"github.com/ark-lang/ark", "A compiled systems programming language written in Go using the LLVM framework"},
	{"github.com/aelsabbahy/goss", "Quick and Easy server testing/validation"},
	{"github.com/docker/containerd", "A daemon to control OCI container runtimes"},
	{"github.com/tinylib/msgp", "A Go code generator for MessagePack / msgpack.org[Go]"},
	{"github.com/wcharczuk/go-chart", "go chart is a basic charting library in native golang."},
	{"github.com/ConradIrwin/aws-name-server", "DNS server that lets you look up ec2 instances by instance name"},
	{"github.com/jackpal/Taipei-Torrent", "A(nother) Bittorrent client written in the go programming language"},
	{"github.com/aktau/github-release", "Commandline app to create and edit releases on Github (and upload artifacts)"},
	{"github.com/skynetservices/skydns1", "DNS for skynet or any other service discovery"},
	{"github.com/tomnomnom/gron", "Make JSON greppable!"},
	{"github.com/mattn/goreman", "foreman clone written in go language"},
	{"github.com/cortesi/modd", "A flexible tool for responding to filesystem changes"},
	{"github.com/arschles/go-in-5-minutes", "Code for Go in 5 Minutes Screencasts"},
	{"github.com/dshearer/jobber", "A replacement for cron, with sophisticated status-reporting and error-handling."},
	{"github.com/valyala/quicktemplate", "Fast, powerful, yet easy to use template engine for Go. Optimized for speed, zero memory allocations in hot paths. Up to 20x faster than html/template"},
	{"github.com/advancedlogic/go-freeling", "Golang Natural Language Processing"},
	{"github.com/zakjan/cert-chain-resolver", "SSL certificate chain resolver"},
	{"github.com/thoas/picfit", "An image resizing server written in Go"},
	{"github.com/ha/doozer", "Go client driver for doozerd, a consistent, distributed data store"},
	{"github.com/cdipaolo/goml", "On-line Machine Learning in Go (and so much more)"},
	{"github.com/SpectoLabs/hoverfly", "lightweight & fantastic service virtualization/API simulation tool, aims to be developer/tester friendly"},
	{"github.com/hoisie/redis", "A simple, powerful Redis client for Go"},
	{"github.com/ziutek/mymysql", "MySQL Client API written entirely in Go"},
	{"github.com/BurntSushi/wingo", "A fully-featured window manager written in Go."},
	{"github.com/google/badwolf", "Temporal graph store abstraction layer."},
	{"github.com/FiloSottile/gvt", "gvt is the go vendoring tool for the GO15VENDOREXPERIMENT, based on gb-vendor"},
	{"github.com/mholt/binding", "Reflectionless data binding for Go's net/http (not yet a stable 1.0, but not likely to change much either)"},
	{"github.com/brutella/hc", "HomeControl is an implementation of the HomeKit Accessory Protocol (HAP) in Go."},
	{"github.com/domodwyer/cryptic", "A sensible secret management toolkit (and Go library) for admins and programmers"},
	{"github.com/franela/goreq", "Minimal and simple request library for Go language"},
	{"github.com/mindreframer/golang-devops-stuff", ""},
	{"github.com/yosssi/ace", "HTML template engine for Go"},
	{"github.com/project-iris/iris", "Decentralized cloud messaging"},
	{"github.com/inconshreveable/log15", "Structured, composable logging for Go"},
	{"github.com/zond/god", "A Go database"},
	{"github.com/facebookgo/inject", "Package inject provides a reflect based injector."},
	{"github.com/alexflint/go-restructure", "Match regular expressions into struct fields"},
	{"github.com/rubenv/sql-migrate", "SQL schema migration tool for Go."},
	{"github.com/libp2p/go-libp2p", "libp2p implementation in Go"},
	{"github.com/go-pg/pg", "Fast PostgreSQL client and ORM for Golang"},
	{"github.com/zimbatm/socketmaster", "Zero downtime restarts for your apps"},
	{"github.com/timeglass/glass", "Automated time tracking for Git repositories"},
	{"github.com/argusdusty/Ferret", "An optimized substring search engine written in Go"},
	{"github.com/juju/juju", "juju is devops distilled"},
	{"github.com/ginuerzh/gost", "GO Simple Tunnel - a simple tunnel written in golang"},
	{"github.com/wendal/gor", "Golang编写的静态博客引擎"},
	{"github.com/adnanh/webhook", "webhook is a lightweight configurable tool written in Go, that allows you to easily create HTTP endpoints (hooks) on your server, which you can use to execute configured commands."},
	{"github.com/GoogleChrome/simplehttp2server", "A simple HTTP/2 server for development"},
	{"github.com/bazil/fuse", "FUSE library for Go.   go get bazil.org/fuse"},
	{"github.com/kubernetes/contrib", "This is a place for various components in the Kubernetes ecosystem that aren't part of the Kubernetes core. Consider creating a new repo instead."},
	{"github.com/samuel/go-zookeeper", "Native ZooKeeper client for Go"},
	{"github.com/joyent/containerpilot", "A service for autodiscovery and configuration of applications running in containers"},
	{"github.com/aacanakin/qb", "The database toolkit for go"},
	{"github.com/pilu/traffic", "Sinatra inspired regexp/pattern mux and web framework for Go"},
	{"github.com/go-validator/validator", "Package validator implements struct field validations"},
	{"github.com/tleyden/open-ocr", "Run your own OCR-as-a-Service using Tesseract and Docker"},
	{"github.com/upper/db", "Magic-free ORM-like package for Go."},
	{"github.com/mvdan/interfacer", "A linter that suggests interface types"},
	{"github.com/siddontang/mixer", "a MySQL proxy powered by Go"},
	{"github.com/purpleidea/mgmt", "A next generation config management prototype!"},
	{"github.com/mmcdole/gofeed", "Parse RSS and Atom feeds in Go"},
	{"github.com/gopherds/gophernotes", "It's time to use Go in notebooks."},
	{"github.com/jstemmer/gotags", "ctags-compatible tag generator for Go"},
	{"github.com/dcoker/biscuit", "Biscuit is a multi-region HA key-value store for your AWS infrastructure secrets."},
	{"github.com/kelseyhightower/envconfig", "Golang library for managing configuration data from environment variables"},
	{"github.com/linkedin/Burrow", "Kafka Consumer Lag Checking"},
	{"github.com/kobolog/gorb", "Go Routing and Balancing"},
	{"github.com/codegangsta/inject", "Dependency injection for go"},
	{"github.com/takama/daemon", "A daemon package for use with Go (golang) services with no dependencies"},
	{"github.com/kelseyhightower/kube-cert-manager", "Manage Lets Encrypt certificates for a Kubernetes cluster."},
	{"github.com/rancher/convoy", "A Docker volume plugin, managing persistent container volumes."},
	{"github.com/stargrave/govpn", "Simple secure free software VPN daemon (mirror of http://git.cypherpunks.ru/cgit.cgi/govpn.git/)"},
	{"github.com/Netflix/rend", "A memcached proxy that manages data chunking and L1 / L2 caches"},
	{"github.com/AcalephStorage/consul-alerts", "A simple daemon to send notifications based on Consul health checks"},
	{"github.com/trivago/gollum", "A n:m message multiplexer written in Go"},
	{"github.com/olahol/melody", ":notes: Minimalist websocket framework for Go"},
	{"github.com/CenturyLinkLabs/watchtower", "Automatically update running Docker containers"},
	{"github.com/jehiah/json2csv", "command line tool to convert json to csv"},
	{"github.com/grammarly/rocker", "Rocker breaks the limits of Dockerfile."},
	{"github.com/gographics/imagick", "naive Go binding to ImageMagick's MagickWand C API"},
	{"github.com/gosuri/uilive", "uilive is a go library for updating terminal output in realtime"},
	{"github.com/campoy/todo", "A task manager written in Go using TDD techniques, each commit should represent a step in the application development."},
	{"github.com/nanopack/mist", "A distributed, tag-based pub-sub service for modern web applications and container-driven cloud."},
	{"github.com/lunny/tango", "Micro & pluggable web framework for Go"},
	{"github.com/throttled/throttled", "Package throttled implements rate limiting access to resources such as HTTP endpoints."},
	{"github.com/fatih/pool", "Connection pool for Go's net.Conn interface"},
	{"github.com/moovweb/gokogiri", "A light libxml wrapper for Go"},
	{"github.com/tus/tusd", "The official server implementation of the tus resumable upload protocol."},
	{"github.com/square/certstrap", "Tools to bootstrap CAs, certificate requests, and signed certificates."},
	{"github.com/afex/hystrix-go", "Netflix's Hystrix latency and fault tolerance library, for Go"},
	{"github.com/PuerkitoBio/fetchbot", "A simple and flexible web crawler that follows the robots.txt policies and crawl delays."},
	{"github.com/EagerIO/Stout", "A reliable static website deploy tool"},
	{"github.com/microcosm-cc/bluemonday", "bluemonday: a fast golang HTML sanitizer (inspired by the OWASP Java HTML Sanitizer) to scrub user generated content of XSS"},
	{"github.com/gorilla/sessions", "Package gorilla/sessions provides cookie and filesystem sessions and infrastructure for custom session backends."},
	{"github.com/unrolled/secure", "HTTP middleware for Go that facilitates some quick security wins."},
	{"github.com/mcuadros/go-candyjs", "fully transparent bridge between Go and the JavaScript"},
	{"github.com/stripe/stripe-go", "Go client for the Stripe API"},
	{"github.com/ngmoco/falcore", "Modular HTTP server framework for Go"},
	{"github.com/harbur/captain", "Captain - Convert your Git workflow to Docker :whale: containers"},
	{"github.com/mitchellh/cli", "A Go library for implementing command-line interfaces."},
	{"github.com/GoogleCloudPlatform/google-cloud-go", "Google Cloud APIs Go Client Library"},
	{"github.com/Terry-Mao/bfs", "distributed file system(small file storage) writen by golang."},
	{"github.com/hashicorp/memberlist", "Golang package for gossip based membership and failure detection"},
	{"github.com/3ofcoins/jetpack", "**PROTOTYPE** FreeBSD Jail/ZFS based implementation of the Application Container Specification"},
	{"github.com/pressly/chi", "lightweight, idiomatic and composable router for building Go 1.7+ HTTP services"},
	{"github.com/benbjohnson/megajson", "A JSON parser generator for high performance encoding and decoding in Go."},
	{"github.com/shurcooL/markdownfmt", "Like gofmt, but for Markdown."},
	{"github.com/lazywei/go-opencv", "Go bindings for OpenCV / 2.x API in gocv / 1.x API in opencv"},
	{"github.com/klauspost/compress", "Optimized compression packages"},
	{"github.com/pinterest/knox", "Knox is a secret management service"},
	{"github.com/davyxu/cellnet", "简单,方便,高效的Go语言的游戏服务器底层"},
	{"github.com/rif/spark", "Emergency web server"},
	{"github.com/hashicorp/go-plugin", "Golang plugin system over RPC."},
	{"github.com/bogdanovich/siberite", "Siberite is a simple, lightweight, leveldb backed message queue written in Go."},
	{"github.com/vole/vole", "Vole is a social, peer-to-peer web app for sharing words, pictures and videos."},
	{"github.com/titanous/heartbleeder", "OpenSSL CVE-2014-0160 Heartbleed vulnerability test"},
	{"github.com/bitly/statsdaemon", "an implementation of Etsy's statsd in Go"},
	{"github.com/roylee0704/gron", "gron, Cron Jobs in Go."},
	{"github.com/lukasmartinelli/pgfutter", "Import CSV and JSON into PostgreSQL the easy way"},
	{"github.com/yinqiwen/gscan", "一个Go语言实现的HTTPS IP可用性扫描工具， 主要作用于Google IP"},
	{"github.com/jasonmoo/smlr", "Re-encode jpeg images with no perceivable quality loss."},
	{"github.com/natefinch/pie", "a toolkit for creating plugins for Go applications"},
	{"github.com/Shopify/ejson", "EJSON is a small library to manage encrypted secrets using asymmetric encryption."},
	{"github.com/bouk/staticfiles", "staticfiles compiles a directory of files into an embeddable .go file"},
	{"github.com/dchest/captcha", "Go package captcha implements generation and verification of image and audio CAPTCHAs."},
	{"github.com/olekukonko/tablewriter", "ASCII table in golang"},
	{"github.com/chihaya/chihaya", "A customizible, multi-protocol BitTorrent Tracker"},
	{"github.com/blackbeans/kiteq", "kiteq is a distributed mq framework"},
	{"github.com/compose/transporter", "Sync data between persistence engines, like ETL only not stodgy"},
	{"github.com/facebookgo/httpcontrol", "Package httpcontrol allows for HTTP transport level control around timeouts and retries."},
	{"github.com/hashicorp/yamux", "Golang connection multiplexing library"},
	{"github.com/openshift/geard", "geard is no longer maintained - see OpenShift 3 and Kubernetes"},
	{"github.com/alexandres/lexvec", "This is an implementation of the LexVec word embedding model (similar to word2vec and GloVe) that achieves state of the art results in multiple NLP tasks"},
	{"github.com/veandco/go-sdl2", "SDL2 binding for Go"},
	{"github.com/cenk/backoff", "The exponential backoff algorithm in Go (Golang)."},
	{"github.com/htcat/htcat", "Parallel and Pipelined HTTP GET Utility"},
	{"github.com/ruedap/alfred-font-awesome-workflow", ":tophat: Font Awesome Workflow for Alfred 2 & 3"},
	{"github.com/ewgRa/de_faq", "Полезная информация о жизни в Германии"},
	{"github.com/axw/gocov", "Coverage testing tool for The Go Programming Language"},
	{"github.com/pebbe/zmq4", "A Go interface to ZeroMQ version 4"},
	{"github.com/alecthomas/gozmq", "Go (golang) bindings for the 0mq (zmq, zeromq) C API"},
	{"github.com/gliderlabs/connectable", "Magic proxy for internal services"},
	{"github.com/goinaction/code", "Source Code for Go In Action examples"},
	{"github.com/hashicorp/go-memdb", "Golang in-memory database built on immutable radix trees"},
	{"github.com/jpillora/cloud-torrent", "☁️ Cloud Torrent: a self-hosted remote torrent client"},
	{"github.com/sbinet/go-python", "naive go bindings to the CPython C-API"},
	{"github.com/cespare/reflex", "Run a command when files change"},
	{"github.com/s-rah/onionscan", "Scan Onion Services for Security Issues"},
	{"github.com/coocood/qbs", "QBS stands for Query By Struct. A Go ORM."},
	{"github.com/klauspost/reedsolomon", "Reed-Solomon Erasure Coding in Go"},
	{"github.com/igrigorik/hackernews-button", "Embeddable Hacker News button + vote counter for your site"},
	{"github.com/ichinaski/pxl", "Display images in the terminal"},
	{"github.com/didip/tollbooth", "Simple middleware to rate-limit HTTP requests."},
	{"github.com/crufter/borg", "A terminal based search engine for bash commands"},
	{"github.com/EricLagergren/go-coreutils", "A cross-platform port of GNU's coreutils to Go"},
	{"github.com/Code-Hex/pget", "Parallel file download client"},
	{"github.com/deckarep/golang-set", "A simple set type for the Go language."},
	{"github.com/xeipuuv/gojsonschema", "An implementation of JSON Schema, draft v4 - Go language"},
	{"github.com/conformal/gotk3", "Go bindings for GTK3"},
	{"github.com/mikespook/gorbac", "goRBAC provides a lightweight role-based access control (RBAC) implementation in Golang."},
	{"github.com/AdRoll/hologram", "Easy, painless AWS credentials on developer laptops."},
	{"github.com/aykamko/tag", "Instantly jump to your ag matches."},
	{"github.com/gyuho/learn", "learn"},
	{"github.com/ekanite/ekanite", "The Syslog server with built-in search"},
	{"github.com/go-python/gopy", "gopy generates a CPython extension module from a go package."},
	{"github.com/mjibson/go-dsp", "Digital Signal Processing for Go"},
	{"github.com/wercker/wercker", "The Wercker CLI can be used to execute pipelines locally for both local development and easy introspection."},
	{"github.com/hlandau/service", ":zap: Easily write daemonizable services in Go"},
	{"github.com/jaytaylor/shipbuilder", "The Open-source self-hosted Platform-as-a-Service written in Go"},
	{"github.com/socketplane/socketplane", "SocketPlane - Multi-Host Container Networking"},
	{"github.com/stretchr/gomniauth", "Authentication framework for Go applications."},
	{"github.com/golang/leveldb", "The LevelDB key-value database in the Go programming language."},
	{"github.com/lucas-clemente/quic-go", "A QUIC server implementation in pure go"},
	{"github.com/emccode/rexray", "REX-Ray provides a vendor agnostic storage orchestration engine."},
	{"github.com/sanbornm/go-selfupdate", "Enable your Golang applications to self update"},
	{"github.com/eapache/go-resiliency", "Resiliency patterns for golang"},
	{"github.com/rakyll/drive", "Pull or push Google Drive files"},
	{"github.com/denisenkom/go-mssqldb", "Microsoft SQL server driver written in go language"},
	{"github.com/kubernetes/helm", "The Kubernetes Package Manager"},
	{"github.com/google/kati", "An experimental GNU make clone"},
	{"github.com/rakyll/go-hardware", "A directory of hardware related libs, tools, and tutorials for Go"},
	{"github.com/snapcore/snapd", "The snapd and snap tools enable systems to work with .snap files."},
	{"github.com/coocood/jas", "A simple and powerful REST API framework for Go"},
	{"github.com/ryanbressler/CloudForest", "Ensembles of decision trees in go/golang."},
	{"github.com/dborzov/lsp", "lsp is like ls command but more human-friendly"},
	{"github.com/hanwen/go-mtpfs", "Mount MTP devices over FUSE"},
	{"github.com/zchee/docker-machine-driver-xhyve", "Docker Machine driver plugin for xhyve (native OSX hypervisor)"},
	{"github.com/onsi/gomega", "Ginkgo's Preferred Matcher Library"},
	{"github.com/AdRoll/goamz", "Fork of the GOAMZ version developed within Canonical with additional functionality with DynamoDB"},
	{"github.com/peterbourgon/diskv", "A disk-backed key-value store."},
	{"github.com/dogestry/dogestry", "Use Amazon S3 as your Docker registry"},
	{"github.com/paypal/gatt", "Gatt is a Go package for building Bluetooth Low Energy peripherals"},
	{"github.com/madari/go-socket.io", "A Socket.IO backend implementation written in Go"},
	{"github.com/go-reform/reform", "A better ORM for Go, based on non-empty interfaces and code generation."},
	{"github.com/likexian/stathub-go", "A smart Hub for holding server Stat"},
	{"github.com/alecthomas/go_serialization_benchmarks", "Benchmarks of Go serialization methods"},
	{"github.com/dustin/seriesly", "A time series database."},
	{"github.com/nictuku/dht", "Kademlia/Mainline DHT node in Go."},
	{"github.com/packetzoom/logzoom", "A lightweight replacement for logstash indexer in Go"},
	{"github.com/stianeikeland/go-rpio", ":electric_plug: Raspberry Pi GPIO library for go-lang"},
	{"github.com/lukasmartinelli/pipecat", "Connect UNIX pipes and message queues"},
	{"github.com/tarm/serial", ""},
	{"github.com/rsc/grind", "Grind polishes Go programs."},
	{"github.com/RobotsAndPencils/buford", "A push notification delivery engine for the new HTTP/2 APNS service."},
	{"github.com/fluffle/goirc", "Event-based stateful IRC client framework for Go."},
	{"github.com/siddontang/go-mysql-elasticsearch", "Sync MySQL data into elasticsearch"},
	{"github.com/jsix/go2o", "Golang基于DDD的o2o的业务模型及基础, 界面:http://github.com/jsix/go2o-web"},
	{"github.com/jsix/go2o", "Golang基于DDD的o2o的业务模型及基础, 界面:http://github.com/jsix/go2o-web"},
	{"github.com/fatih/set", "Set data structure for Go"},
	{"github.com/rackspace/gophercloud", "A Go SDK for OpenStack. IN FEATURE FREEZE. See Issue #592"},
	{"github.com/codeskyblue/go-sh", "like python-sh, for easy call shell with golang."},
	{"github.com/manyminds/api2go", "JSONAPI.org Implementation for Go"},
	{"github.com/golang/mock", "GoMock is a mocking framework for the Go programming language."},
	{"github.com/aws/amazon-ecs-cli", "A custom Amazon ECS CLI that eases up the cluster setup process, enables users to run their applications locally or on ECS using the same Docker Compose file format and familiar Compose commands."},
	{"github.com/sorintlab/stolon", "PostgreSQL cloud native High Availability"},
	{"github.com/google/zoekt", "Fast trigram based code search"},
	{"github.com/Coccodrillo/apns", "A Golang package for sending Apple Push Notifications and using the Feedback Service."},
	{"github.com/mozilla/masche", "MIG Memory Forensic library"},
	{"github.com/mesosphere/mesos-dns", "DNS-based service discovery for Mesos."},
	{"github.com/cpuguy83/docker-volumes", "Docker Volume Manager"},
	{"github.com/hirokidaichi/goviz", "a visualization tool for golang project dependency"},
	{"github.com/renstrom/shortuuid", ":mushroom: A generator library for concise, unambiguous and URL-safe UUIDs"},
	{"github.com/jeansfish/RFC6749.zh-cn", "A translation of simplified chinese for RFC 6749-The OAuth 2.0 Authorization Framework. RFC 6749 - OAuth 2.0授权框架简体中文翻译。"},
	{"github.com/kr/pretty", "Pretty printing for Go values"},
	{"github.com/ibuildthecloud/systemd-docker", "Wrapper for \"docker run\" to handle systemd quirks"},
	{"github.com/yvasiyarov/gorelic", "New Relic agent for Go lang"},
	{"github.com/dghubble/sling", "A Go HTTP client library for creating and sending API requests"},
	{"github.com/walter-cd/walter", "Tiny deployment pipeline"},
	{"github.com/alfredxing/calc", "A simple, fast command-line calculator written in Go"},
	{"github.com/google/martian", "Martian is a library for building custom HTTP/S proxies"},
	{"github.com/Jeffail/tunny", "A goroutine pool for golang"},
	{"github.com/trustpath/sequence", "High performance sequential log analyzer and parser"},
	{"github.com/nsf/godit", "A very religious text editor"},
	{"github.com/crosbymichael/slex", "SSH multiplex"},
	{"github.com/kellydunn/golang-geo", "Geographical calculations in Go."},
	{"github.com/jawher/mow.cli", "A versatile library for building CLI applications in Go"},
	{"github.com/go-gl-legacy/gl", "Go bindings for OpenGL"},
	{"github.com/meshbird/meshbird", "Distributed private networking"},
	{"github.com/petar/GoLLRB", "A Left-Leaning Red-Black (LLRB) implementation of balanced binary search trees for Google Go"},
	{"github.com/vulcand/vulcan", "[DEPRECATING] Development has moved to https://github.com/mailgun/oxy"},
	{"github.com/google/skicka", "Command-line utility for working with Google Drive. Join the mailing list at https://groups.google.com/forum/#!forum/skicka-users."},
	{"github.com/thoas/stats", "A Go middleware that stores various information about your web application (response time, status code count, etc.)"},
	{"github.com/gocraft/work", "Process background jobs in Go"},
	{"github.com/rs/cors", "Go net/http configurable handler to handle CORS requests"},
	{"github.com/jbrukh/bayesian", "Naive Bayesian Classification for Golang."},
	{"github.com/jmoiron/modl", "golang database modelling library"},
	{"github.com/alexflint/go-arg", "Struct-based argument parsing in Go"},
	{"github.com/FlashBoys/go-finance", "Flexible, simple financial markets data in Go."},
	{"github.com/bndr/gopencils", "Easily consume REST APIs with Go (golang)"},
	{"github.com/ooyala/atlantis", "Open Source PaaS Built on Docker"},
	{"github.com/vdobler/chart", "Provide basic charts in go"},
	{"github.com/tj/robo", "Simple Go / YAML-based task runner for the team."},
	{"github.com/beego/wetalk", "An open source project for Gopher community."},
	{"github.com/exercism/cli", "A Go based command line tool for exercism.io."},
	{"github.com/go-godo/godo", "golang build tool in the spirt of rake, gulp"},
	{"github.com/go-ini/ini", "Package ini provides INI file read and write functionality in Go."},
	{"github.com/djherbis/buffer", "Composable Buffers for Go #golang"},
	{"github.com/m3ng9i/ran", "a simple static web server written in Go"},
	{"github.com/inconshreveable/muxado", "Stream multiplexing for Go"},
	{"github.com/mercari/gaurun", "General push notification server in Go"},
	{"github.com/mesos/mesos-go", "Go language bindings for Apache Mesos"},
	{"github.com/digitalocean/godo", "DigitalOcean Go API client"},
	{"github.com/yosssi/gcss", "Pure Go CSS Preprocessor"},
	{"github.com/mitchellh/ioprogress", "Go (golang) package for progress bars around io.Reader/Writers."},
	{"github.com/juju/ratelimit", "Efficient token-bucket-based rate limiter package."},
	{"github.com/google/syzkaller", "syzkaller is a distributed, unsupervised, coverage-guided Linux syscall fuzzer"},
	{"github.com/NebulousLabs/Sia", "Blockchain-based marketplace for file storage"},
	{"github.com/albrow/jobs", "A persistent and flexible background jobs library for go."},
	{"github.com/joho/godotenv", "A Go port of Ruby's dotenv library (Loads environment variables from `.env`.)"},
	{"github.com/mgutz/dat", "Go Postgres Data Access Toolkit"},
	{"github.com/rubyist/circuitbreaker", "Circuit Breakers in Go"},
	{"github.com/shaoshing/train", "Asset Management for web app using Golang."},
	{"github.com/josephspurrier/gowebapp", "Basic MVC Web Application in Go"},
	{"github.com/docker/libcompose", "An experimental go library providing Compose-like functionality"},
	{"github.com/xordataexchange/crypt", "Store and retrieve encrypted configs from etcd or consul"},
	{"github.com/adammck/terraform-inventory", "Terraform State → Ansible Dynamic Inventory"},
	{"github.com/driskell/log-courier", "Log Courier, a lightweight log shipper with Logstash integration."},
	{"github.com/9seconds/ah", "A better history"},
	{"github.com/splitsh/lite", "Split your monorepo into many repos"},
	{"github.com/divan/gobenchui", "UI for overview of your Golang package benchmarks progress."},
	{"github.com/gonum/plot", "A repository for plotting and visualizing data"},
	{"github.com/google/go-querystring", "go-querystring is Go library for encoding structs into URL query parameters."},
	{"github.com/smallnest/rpcx", "rpcx is a distributed RPC service framework based on net/rpc like  alibaba Dubbo and weibo Motan. One of best performance RPC frameworks."},
	{"github.com/rafikk/halfshell", "A proxy server for processing images on the fly."},
	{"github.com/gosuri/uitable", "A go library to improve readability in terminal apps using tabular data"},
	{"github.com/natefinch/lumberjack", "lumberjack is a rolling logger for Go"},
	{"github.com/lukasmartinelli/nigit", "Web server that wraps around programs and shell scripts and exposes them as API"},
	{"github.com/nishanths/license", "Command-line license generator in Go"},
	{"github.com/grammarly/rocker-compose", "Docker composition tool with idempotency features for deploying apps composed of multiple containers."},
	{"github.com/xlab/android-go", "The android-go project provides a platform for writing native Android apps in Go programming language."},
	{"github.com/oskca/sciter", "Golang bindings of Sciter: the Embeddable HTML/CSS/script engine for modern UI development"},
	{"github.com/divan/depscheck", "Dependency checker for Golang (Go) packages. Prints stats and suggests to remove small LeftPad-like imports if any."},
	{"github.com/GameXG/TcpRoute2", "TcpRoute , TCP 层的路由器。对于 TCP 连接自动从多个线路(允许任意嵌套)、多个域名解析结果中选择最优线路。"},
	{"github.com/codahale/metrics", "This is not the Java library."},
	{"github.com/ejcx/passgo", "Simple golang password manager."},
	{"github.com/huandu/xstrings", "xstrings: A collection of useful string functions for Go."},
	{"github.com/stathat/consistent", "Consistent hash package for Go."},
	{"github.com/rs/rest-layer", "REST Layer, Go (golang) REST API framework"},
	{"github.com/sunfmin/fanout", "Fanout - make writing parallel code even easier"},
	{"github.com/huandu/facebook", "A Facebook Graph API SDK Library For Golang"},
	{"github.com/rsc/c2go", "C to Go translation tool supporting Go toolchain migration"},
	{"github.com/teh-cmc/mmm", "[Go] mmm - manual memory management library."},
	{"github.com/golang/crypto", "[mirror] Go supplementary cryptography libraries"},
	{"github.com/dominikh/go-unused", "Check Go programs for unused identifiers"},
	{"github.com/ajhager/engi", "A multi-platform 2D game library for Go."},
	{"github.com/qor/qor-example", "An example application showcasing the QOR SDK"},
	{"github.com/monsti/monsti", "Simple and resource efficient CMS for small sites"},
	{"github.com/vishvananda/wormhole", "A smart proxy to connect docker containers."},
	{"github.com/fzzy/radix", "Redis client for Go"},
	{"github.com/xjdrew/gotunnel", "tcp tunnel"},
	{"github.com/reconquest/shadowd", "Secure login distribution service"},
	{"github.com/VividCortex/siesta", "Composable framework for writing HTTP handlers in Go."},
	{"github.com/jcla1/gisp", "Simple LISP in Go"},
	{"github.com/subosito/iglo", "API blueprint's formatter"},
	{"github.com/akhenakh/statgo", "Access OS metrics from Golang,"},
	{"github.com/corylanou/tns-restful-json-api", "This is the code repository that goes along with the \"TheNewStack\" article for RESTful JSON API post"},
	{"github.com/sevlyar/go-daemon", "A library for writing system daemons in golang."},
	{"github.com/beeker1121/goque", "Persistent stacks, queues, and priority queues for Go backed by LevelDB"},
	{"github.com/ipfs/specs", "This repository contains the specs for the IPFS Protocol and associated subsystems."},
	{"github.com/hashicorp/golang-lru", "Golang LRU cache"},
	{"github.com/k0kubun/pp", "Colored pretty printer for Go language"},
	{"github.com/aacebedo/dnsdock", "DNS service discovery for Docker containers"},
	{"github.com/cznic/kv", "Package kv implements a simple and easy to use persistent key/value (KV) store."},
	{"github.com/inconshreveable/srvdir", "Expose any folder as an HTTPS fileserver"},
	{"github.com/pkg/profile", "Simple profiling for Go"},
	{"github.com/goffee/goffee", "Global uptime monitoring via Tor"},
	{"github.com/mongodb/mongo-tools", ""},
	{"github.com/matryer/goblueprints", "Source code for Go Programming Blueprints"},
	{"github.com/glycerine/zygomys", "Java has Clojure, Go has zygo. A 100% Golang, easy-to-use Lisp."},
	{"github.com/rakyll/statik", "Embed static files into a Go executable"},
	{"github.com/igm/sockjs-go", "WebSocket emulation - Go server library"},
	{"github.com/minio/mc", "Minio Client is a replacement for ls, cp, mkdir, diff and rsync commands for filesystems and object storage."},
	{"github.com/flashmob/go-guerrilla", "Mini SMTP server written in golang"},
	{"github.com/huydx/hget", "rocket fast, interruptable, resumable download accelerator written in golang"},
	{"github.com/qiniu/qlang", "Q Language (Q语言) - A script language for Go"},
	{"github.com/mattn/go-xmpp", "go xmpp library (original was written by russ cox  )"},
	{"github.com/tj/go-debug", "Conditional debug logging for Golang libraries & applications"},
	{"github.com/bradrydzewski/go.auth", "authentication API for Go web applications"},
	{"github.com/git-lfs/lfs-test-server", "Standalone Git LFS server"},
	{"github.com/peterh/liner", "Pure Go line editor with history, inspired by linenoise"},
	{"github.com/jung-kurt/gofpdf", "A PDF document generator with high level support for text, drawing and images"},
	{"github.com/strangeloop/StrangeLoop2013", "Strange Loop 2013"},
	{"github.com/alphazero/Go-Redis", "Google Go Client and Connectors for Redis"},
	{"github.com/jqs7/Jqs7Bot", "Telegram 中文群组列表机器人"},
	{"github.com/Luxurioust/excelize", "Golang library for reading and writing XLSX files."},
	{"github.com/miketheprogrammer/go-thrust", "Cross Platform UI Kit powered by Blink/V8/Chromium Content Lib"},
	{"github.com/shopspring/decimal", "Arbitrary-precision fixed-point decimal numbers in go"},
	{"github.com/miekg/coredns", "CoreDNS is a DNS server that runs middleware"},
	{"github.com/boot2docker/boot2docker-cli", "boot2docker management utility"},
	{"github.com/gdamore/tcell", "Tcell is an alternate terminal package, similar in some ways to termbox, but better in others."},
	{"github.com/adjust/redismq", "a durable message queue system for go based on redis, see also https://github.com/adjust/rmq"},
	{"github.com/SimonWaldherr/golang-examples", "Go(lang) examples - (explain the basics of golang)"},
	{"github.com/go-resty/resty", "Simple HTTP and REST client for Go inspired by Ruby rest-client"},
	{"github.com/eleme/banshee", "Anomalies detection system for periodic metrics."},
	{"github.com/xlvector/hector", "Golang machine learning lib"},
	{"github.com/coreos/go-etcd", "DEPRECATED - please use the official client at https://github.com/coreos/etcd/tree/master/client"},
	{"github.com/coreos/go-systemd", "Go bindings to systemd socket activation, journal, D-Bus, and unit files"},
	{"github.com/AppliedTrust/traildash", "AWS CloudTrail Dashboard"},
	{"github.com/sourcegraph/thesrc", "Example of a 3-layer (frontend, API, datastore) Go web app (based on the code that powers https://sourcegraph.com)"},
	{"github.com/ryanskidmore/GoWork", "Go Library for distributing work to workers"},
	{"github.com/tardisgo/tardisgo", "Golang->Haxe->CPP/CSharp/Java/JavaScript transpiler"},
	{"github.com/ReshNesh/pixlserv", "Go server for processing and serving of images"},
	{"github.com/fuxiaohei/GoBlog", "personal site engine with goink framework"},
	{"github.com/gocraft/health", "Instrument your web apps with logging and metrics"},
	{"github.com/ellotheth/pipethis", "Replace your `curl | sh` installers"},
	{"github.com/cloud66/habitus", "A Build Flow Tool for Docker"},
	{"github.com/nytlabs/hive", "A platform for backing crowdsourcing websites, built in golang for elasticsearch"},
	{"github.com/jfrazelle/bane", "Custom AppArmor profile generator for docker containers"},
	{"github.com/franela/goblin", "Minimal and Beautiful Go testing framework"},
	{"github.com/CloudyKit/jet", "Jet  template engine"},
	{"github.com/jmoiron/jsonq", "simple json field access for golang"},
	{"github.com/jadekler/git-go-websiteskeleton", "A go skeleton for websites."},
	{"github.com/pointlander/peg", "Peg, Parsing Expression Grammar, is an implementation of a Packrat parser generator."},
	{"github.com/cloudfoundry/gorouter", "CF Router"},
	{"github.com/hprose/hprose-go", "Hprose for Golang"},
	{"github.com/progrium/go-extpoints", "Make Go packages extensible"},
	{"github.com/secondbit/wendy", "A pure Go implementation of the Pastry Distributed Hash Table"},
	{"github.com/coreos/coreos-cloudinit", "an implementation of cloud-config written in Go"},
	{"github.com/agl/xmpp-client", "An XMPP client with OTR support"},
	{"github.com/cesanta/docker_auth", "Authentication server for Docker Registry 2"},
	{"github.com/t3rm1n4l/megacmd", "A command-line client for mega.co.nz storage service"},
	{"github.com/deckarep/gosx-notifier", "gosx-notifier is a Go framework for sending desktop notifications to OSX 10.8 or higher"},
	{"github.com/smartystreets/go-disruptor", "A port of the LMAX Disruptor to the Go language."},
	{"github.com/jfrazelle/weather", "Weather via the command line."},
	{"github.com/vmware/govmomi", "Go library for the VMware vSphere API"},
	{"github.com/cupcake/sigil", "Identicon generator"},
	{"github.com/headzoo/surf", "Stateful programmatic web browsing in Go."},
	{"github.com/muesli/smartcrop", "smartcrop implementation in Go"},
	{"github.com/graphite-ng/graphite-api-experiment", "EXPERIMENTAL graphite api server TOY PROJECT NOT FOR PRODUCTION"},
	{"github.com/paulbellamy/mango", "Mango is a modular web-application framework for Go, inspired by Rack, and PEP333."},
	{"github.com/atmanos/atmanos", "Build Go programs that run directly on the Xen hypervisor"},
	{"github.com/go-playground/lars", ":rotating_light: Is a lightweight, fast and extensible zero allocation HTTP router for Go used to create customizable frameworks."},
	{"github.com/AllenDang/w32", "A wrapper of windows apis for the Go Programming Language."},
	{"github.com/mitchellh/go-mruby", "Go (golang) bindings to mruby."},
	{"github.com/otoolep/hraftd", "A reference use of Hashicorp's Raft implementation"},
	{"github.com/alexanderGugel/wsd", ":facepunch: cURL for WebSocket Servers"},
	{"github.com/hmarr/codecube", "Docker-powered runnable code snippets"},
	{"github.com/siddontang/go-mysql", "a powerful mysql toolset with Go"},
	{"github.com/lucasb-eyer/go-colorful", "A library for playing with colors in go (golang)."},
	{"github.com/digitalocean/vulcan", "Vulcan is an API-compatible extension to Prometheus."},
	{"github.com/Scalingo/go-graceful-restart-example", "Example of server with graceful restart enable"},
	{"github.com/golang/snappy", "The Snappy compression format in the Go programming language."},
	{"github.com/h2non/gentleman", "Full-featured, plugin-oriented, composable HTTP client toolkit for Go (golang) (͡° ͜ʖ ͡°)"},
	{"github.com/tobert/pcstat", "Page Cache stat: get page cache stats for files on Linux"},
	{"github.com/gonum/matrix", "Matrix packages for the Go language."},
	{"github.com/vektra/vega", "A distributed mailbox system"},
	{"github.com/nu7hatch/gouuid", "Go binding for libuuid"},
}
