#import './FileDiffHunks.gql'

fragment FileDiff_Diff on FileDiff {
    newPath
    oldPath
    mostRelevantFile {
        canonicalURL # key field
        url
    }
    newFile {
        canonicalURL # key field
        binary
    }
    stat {
        added
        deleted
    }
    hunks {
        ...FileDiffHunks_Hunk
    }
}
