# TODO: Experimental cAdvisor Dockerfile. Entirely untested, and may require additional libraries

# NOTE: Check the README before updating
# hadolint ignore=DL3007
FROM us.gcr.io/sourcegraph-dev/wolfi-sourcegraph-base:latest
LABEL com.sourcegraph.cadvisor.version=v0.47.0

ARG COMMIT_SHA="unknown"
ARG DATE="unknown"
ARG VERSION="unknown"

LABEL org.opencontainers.image.revision=${COMMIT_SHA}
LABEL org.opencontainers.image.created=${DATE}
LABEL org.opencontainers.image.version=${VERSION}

# Reflects cAdvisor Dockerfile at https://github.com/google/cadvisor/blob/v0.45.0/deploy/Dockerfile
# alongside additional Sourcegraph defaults.
ENTRYPOINT ["/usr/bin/cadvisor", "-logtostderr", \
    # sourcegraph cAdvisor custom port
    "-port=48080", \
    # For metrics categories, see:
    # https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md#prometheus-container-metrics
    # and cross-reference with search in the codebase to decide which categories we need
    "-enable_metrics=cpu,diskIO,memory,network", \
    # Aligned 1:1 with Kubelet defaults:
    # https://sourcegraph.com/github.com/google/cadvisor@v0.45.0/-/blob/deploy/kubernetes/overlays/examples/cadvisor-args.yaml
    "-docker_only", \
    "-housekeeping_interval=10s", \
    "-max_housekeeping_interval=15s", \
    "-event_storage_event_limit=default=0", \
    "-event_storage_age_limit=default=0"]
