// generated by "npm run generate"
// tslint:disable

export const base: string;
export const vars: string;
export const colors: string;
export const typography: string;
export const media_xs: string;
export const media_sm: string;
export const media_ns: string;
export const navbarHeight: string;
export const navbarZIndex: string;
export const logomark: string;
export const spin: string;
export const channel: string;
export const channel_closed: string;
export const channel_connected: string;
export const channel_connecting: string;
export const channel_error: string;
export const icon: string;
export const icon_check: string;
export const icon_ellipsis: string;
export const not_small_only: string;
export const small_only: string;

