package filter

import (
	"strings"

	"github.com/sourcegraph/sourcegraph/lib/errors"
)

const (
	Commit     = "commit"
	Content    = "content"
	File       = "file"
	Repository = "repo"
	Symbol     = "symbol"
)

// SelectPath represents a parsed and validated select value
type SelectPath []string

func (sp SelectPath) String() string {
	return strings.Join(sp, ".")
}

// Root is the top-level result type that is being selected.
// Returns an empty string if SelectPath is empty
func (sp SelectPath) Root() string {
	if len(sp) > 0 {
		return sp[0]
	}
	return ""
}

type object map[string]object

var validSelectors = object{
	Commit: object{
		"diff": object{
			"added":   nil,
			"removed": nil,
		},
	},
	Content: nil,
	File: {
		"directory": nil,
		"path":      nil,
	},
	Repository: nil,
	Symbol: object{
		"Constructor":           nil,
		"Exception":             nil,
		"File":                  nil,
		"L1Header":              nil,
		"L2Header":              nil,
		"L3Header":              nil,
		"L4Header":              nil,
		"L5Header":              nil,
		"L6Header":              nil,
		"NAME":                  nil,
		"RecordField":           nil,
		"accelerators":          nil,
		"accessor":              nil,
		"activeBindingFunc":     nil,
		"alias":                 nil,
		"altstep":               nil,
		"anchor":                nil,
		"annotation":            nil,
		"anon":                  nil,
		"anonMember":            nil,
		"antfile":               nil,
		"architecture":          nil,
		"arg":                   nil,
		"array":                 nil,
		"article":               nil,
		"artifactId":            nil,
		"assembly":              nil,
		"assert":                nil,
		"attribute":             nil,
		"augroup":               nil,
		"autovar":               nil,
		"benchmark":             nil,
		"bibitem":               nil,
		"bitmap":                nil,
		"block":                 nil,
		"blockData":             nil,
		"book":                  nil,
		"booklet":               nil,
		"boolean":               nil,
		"build":                 nil,
		"callback":              nil,
		"category":              nil,
		"ccflag":                nil,
		"cell":                  nil,
		"chapter":               nil,
		"checker":               nil,
		"choice":                nil,
		"chunklabel":            nil,
		"citation":              nil,
		"class":                 nil,
		"clocking":              nil,
		"combo":                 nil,
		"command":               nil,
		"common":                nil,
		"component":             nil,
		"cond":                  nil,
		"condition":             nil,
		"conference":            nil,
		"config":                nil,
		"const":                 nil,
		"constant":              nil,
		"constraint":            nil,
		"constructor":           nil,
		"context":               nil,
		"counter":               nil,
		"covergroup":            nil,
		"cursor":                nil,
		"custom":                nil,
		"data":                  nil,
		"database":              nil,
		"dataframe":             nil,
		"def":                   nil,
		"define":                nil,
		"definition":            nil,
		"delegate":              nil,
		"deletedFile":           nil,
		"derivedMode":           nil,
		"describe":              nil,
		"dialog":                nil,
		"directory":             nil,
		"division":              nil,
		"document":              nil,
		"domain":                nil,
		"edesc":                 nil,
		"element":               nil,
		"entity":                nil,
		"entry":                 nil,
		"entryspec":             nil,
		"enum":                  nil,
		"enumConstant":          nil,
		"enumerator":            nil,
		"environment":           nil,
		"error":                 nil,
		"event":                 nil,
		"exception":             nil,
		"externvar":             nil,
		"face":                  nil,
		"fd":                    nil,
		"feature":               nil,
		"field":                 nil,
		"filename":              nil,
		"font":                  nil,
		"footnote":              nil,
		"formal":                nil,
		"format":                nil,
		"fragment":              nil,
		"framesubtitle":         nil,
		"frametitle":            nil,
		"fun":                   nil,
		"func":                  nil,
		"function":              nil,
		"functionVar":           nil,
		"functor":               nil,
		"gem":                   nil,
		"generator":             nil,
		"generic":               nil,
		"getter":                nil,
		"global":                nil,
		"globalVar":             nil,
		"grammar":               nil,
		"group":                 nil,
		"groupId":               nil,
		"guard":                 nil,
		"handler":               nil,
		"header":                nil,
		"heading1":              nil,
		"heading2":              nil,
		"heading3":              nil,
		"heredoc":               nil,
		"hunk":                  nil,
		"icon":                  nil,
		"id":                    nil,
		"identifier":            nil,
		"ifclass":               nil,
		"implementation":        nil,
		"import":                nil,
		"inbook":                nil,
		"incollection":          nil,
		"index":                 nil,
		"infoitem":              nil,
		"inline":                nil,
		"inproceedings":         nil,
		"inputSection":          nil,
		"instance":              nil,
		"integer":               nil,
		"interface":             nil,
		"iparam":                nil,
		"it":                    nil,
		"kconfig":               nil,
		"key":                   nil,
		"keyword":               nil,
		"kind":                  nil,
		"l4subsection":          nil,
		"l5subsection":          nil,
		"label":                 nil,
		"langdef":               nil,
		"langstr":               nil,
		"library":               nil,
		"list":                  nil,
		"literal":               nil,
		"local":                 nil,
		"localVariable":         nil,
		"localvar":              nil,
		"loggerSection":         nil,
		"ltlibrary":             nil,
		"macro":                 nil,
		"macroParameter":        nil,
		"macrofile":             nil,
		"macroparam":            nil,
		"mainMenu":              nil,
		"makefile":              nil,
		"man":                   nil,
		"manual":                nil,
		"map":                   nil,
		"mastersthesis":         nil,
		"matchedTemplate":       nil,
		"member":                nil,
		"menu":                  nil,
		"message":               nil,
		"method":                nil,
		"methodSpec":            nil,
		"minorMode":             nil,
		"misc":                  nil,
		"mixin":                 nil,
		"mlconn":                nil,
		"mlprop":                nil,
		"mltable":               nil,
		"modifiedFile":          nil,
		"modport":               nil,
		"module":                nil,
		"modulepar":             nil,
		"multitask":             nil,
		"mxtag":                 nil,
		"name":                  nil,
		"nameattr":              nil,
		"namedPattern":          nil,
		"namedTemplate":         nil,
		"namelist":              nil,
		"namespace":             nil,
		"net":                   nil,
		"nettype":               nil,
		"newFile":               nil,
		"node":                  nil,
		"notation":              nil,
		"nsprefix":              nil,
		"null":                  nil,
		"number":                nil,
		"object":                nil,
		"oneof":                 nil,
		"oparam":                nil,
		"operator":              nil,
		"optenable":             nil,
		"option":                nil,
		"optwith":               nil,
		"package":               nil,
		"packageName":           nil,
		"packspec":              nil,
		"paragraph":             nil,
		"param":                 nil,
		"parameter":             nil,
		"parameterEntity":       nil,
		"part":                  nil,
		"patch":                 nil,
		"path":                  nil,
		"pattern":               nil,
		"phandler":              nil,
		"phdthesis":             nil,
		"pkg":                   nil,
		"placeholder":           nil,
		"play":                  nil,
		"port":                  nil,
		"probe":                 nil,
		"procedure":             nil,
		"proceedings":           nil,
		"process":               nil,
		"program":               nil,
		"project":               nil,
		"property":              nil,
		"protected":             nil,
		"protectspec":           nil,
		"protocol":              nil,
		"protodef":              nil,
		"prototype":             nil,
		"publication":           nil,
		"qmp":                   nil,
		"qualname":              nil,
		"receiver":              nil,
		"record":                nil,
		"regex":                 nil,
		"region":                nil,
		"register":              nil,
		"reopen":                nil,
		"repoid":                nil,
		"repositoryId":          nil,
		"repr":                  nil,
		"resource":              nil,
		"response":              nil,
		"role":                  nil,
		"root":                  nil,
		"rpc":                   nil,
		"rule":                  nil,
		"run":                   nil,
		"schema":                nil,
		"script":                nil,
		"section":               nil,
		"sectionGroup":          nil,
		"selector":              nil,
		"sequence":              nil,
		"server":                nil,
		"service":               nil,
		"set":                   nil,
		"setter":                nil,
		"signal":                nil,
		"signature":             nil,
		"singletonMethod":       nil,
		"slot":                  nil,
		"source":                nil,
		"sourcefile":            nil,
		"step":                  nil,
		"string":                nil,
		"struct":                nil,
		"structure":             nil,
		"stylesheet":            nil,
		"subdir":                nil,
		"submethod":             nil,
		"submodule":             nil,
		"subparagraph":          nil,
		"subprogram":            nil,
		"subprogspec":           nil,
		"subroutine":            nil,
		"subroutineDeclaration": nil,
		"subsection":            nil,
		"subspec":               nil,
		"subst":                 nil,
		"substdef":              nil,
		"subsubsection":         nil,
		"subtitle":              nil,
		"subtype":               nil,
		"symbol":                nil,
		"synonym":               nil,
		"table":                 nil,
		"tag":                   nil,
		"talias":                nil,
		"target":                nil,
		"task":                  nil,
		"taskspec":              nil,
		"techreport":            nil,
		"template":              nil,
		"test":                  nil,
		"testcase":              nil,
		"theme":                 nil,
		"theorem":               nil,
		"thriftFile":            nil,
		"throwsparam":           nil,
		"timer":                 nil,
		"title":                 nil,
		"token":                 nil,
		"toplevelVariable":      nil,
		"tparam":                nil,
		"trait":                 nil,
		"trigger":               nil,
		"type":                  nil,
		"typealias":             nil,
		"typedef":               nil,
		"typespec":              nil,
		"union":                 nil,
		"unit":                  nil,
		"unknown":               nil,
		"unpublished":           nil,
		"username":              nil,
		"using":                 nil,
		"val":                   nil,
		"value":                 nil,
		"var":                   nil,
		"varalias":              nil,
		"variable":              nil,
		"varspec":               nil,
		"vector":                nil,
		"version":               nil,
		"view":                  nil,
		"virtual":               nil,
		"vresource":             nil,
		"wrapper":               nil,
		"xinput":                nil,
		"xtask":                 nil,
	},
}

func SelectPathFromString(s string) (SelectPath, error) {
	fields := strings.Split(s, ".")
	cur := validSelectors
	for _, field := range fields {
		child, ok := cur[field]
		if !ok {
			return SelectPath{}, errors.Errorf("invalid field %q on select path %q", field, s)
		}
		cur = child
	}
	return SelectPath(fields), nil
}
