query Init {
    currentUser {
        ...AuthenticatedUser
    }

    viewerSettings {
        final
    }

    evaluatedFeatureFlags {
        ...FeatureFlag
    }
}

query EvaluatedFeatureFlagsQuery {
    evaluatedFeatureFlags {
        ...FeatureFlag
    }
}

query GlobalAlertsSiteFlags {
    site {
        ...GlobalNotifications
    }
}

fragment FeatureFlag on EvaluatedFeatureFlag {
    name
    value
}

fragment AuthenticatedUser on User {
    ...Header_User
    ...SearchInput_AuthenticatedUser
}
