query Init {
    currentUser {
        ...AuthenticatedUser
    }

    viewerSettings {
        final
    }

    evaluatedFeatureFlags {
        ...FeatureFlag
    }
}

query EvaluatedFeatureFlagsQuery {
    evaluatedFeatureFlags {
        ...FeatureFlag
    }
}

query GlobalAlertsSiteFlags {
    site {
        ...GlobalNotifications
    }
}

mutation DisableSveltePrototype($userID: ID!) {
    overrideWebNext: createFeatureFlagOverride(namespace: $userID, flagName: "web-next", value: false) {
        __typename
    }
    overrideRollout: createFeatureFlagOverride(namespace: $userID, flagName: "web-next-rollout", value: false) {
        __typename
    }
}

fragment FeatureFlag on EvaluatedFeatureFlag {
    name
    value
}

fragment AuthenticatedUser on User {
    ...GlobalNavigation_User
    ...SearchInput_AuthenticatedUser
}

mutation EditSettings($subject: ID!, $lastID: Int, $edit: SettingsEdit!) {
    settingsMutation(input: { subject: $subject, lastID: $lastID }) {
        editSettings(edit: $edit) {
            empty {
                alwaysNil
            }
        }
    }
}

query LatestSettingsQuery {
    viewerSettings {
        subjects {
            id
            latestSettings {
                id
            }
        }
    }
}
