// +build !dist

//go:generate go-bindata -modtime=1362009600 -mode=436 -tags=!dev -ignore=.*\.go$DOLLAR -pkg=tmpl -prefix=tmpl -o tmpl/data.go tmpl/...
//go:generate go-bindata -modtime=1362009600 -mode=436 -dev -tags=dev -ignore=.*\.go$DOLLAR -pkg=tmpl -prefix=tmpl -o tmpl/data_src.go tmpl/...

//go:generate go-bindata -modtime=1362009600 -mode=436 -tags=!dev -ignore=.*\.go$DOLLAR -pkg=assets -prefix=assets -o assets/data.go assets/...
//go:generate go-bindata -modtime=1362009600 -mode=436 -dev -tags=dev -ignore=.*\.go$DOLLAR -pkg=assets -prefix=assets -o assets/data_src.go assets/...

//go:generate go fmt ./...

package devdoc
