query RepoPopoverQuery($repoName: String!) {
    repository(name: $repoName) {
        ...RepoPopoverFragment
    }
}

fragment RepoPopoverFragment on Repository {
    name
    description
    stars
    isPrivate
    topics
    externalRepository {
        serviceType
    }

    commit(rev: "HEAD") {
        id
        oid
        subject
        canonicalURL
        author {
            date
            person {
                ...Avatar_Person
            }
        }
    }
}
