query AllBranchesPage_BranchesQuery(
    $repoName: String!
    $first: Int!
    $withBehindAhead: Boolean!
    $revspec: String = ""
) {
    repository(name: $repoName) {
        id
        branches(first: $first, orderBy: AUTHORED_OR_COMMITTED_AT) {
            ...GitBranchesConnection
        }
    }
}

fragment GitBranchesConnection on GitRefConnection {
    nodes {
        id
        ...GitReference_Ref
    }
    totalCount
}
