# hadolint ignore=DL3007
FROM us.gcr.io/sourcegraph-dev/wolfi-opentelemetry-collector-base:latest

ARG COMMIT_SHA="unknown"
ARG DATE="unknown"
ARG VERSION="unknown"

LABEL org.opencontainers.image.revision=${COMMIT_SHA}
LABEL org.opencontainers.image.created=${DATE}
LABEL org.opencontainers.image.version=${VERSION}

# TODO: Alpine image runs as root - required?

# Set up bundled configuration - see README
COPY ./configs /etc/otel-collector/configs

ENTRYPOINT [ "/bin/otelcol-sourcegraph" ]
