#!/usr/bin/env bash

# shellcheck disable=SC1090,SC1091
source "$HOME/.profile"

# due to how the repostiory is cloned with --depth=100 (see aspect terraform docs), we need to fetch the tags manually
# we don't want to fetch all the tags, so here:
# 1. Get a list of tags from the remote
# 2. Srt them
# 3. Get the last 20 tags
# 4. Parse them so that we only get the tag
# 5. Then loop through every tag and fetch it
echo "--- :git: Fetching last 20 tags"
git ls-remote --tags origin | sort -t '/' -k 3 -V | tail -n 20 | awk -F'/' '{gsub(/\^\{\}$/, "", $3); print $3}' | while read -r tag; do
  git -v fetch origin tag "$tag"
done

# Link command wrapper scripts so we can have more readable steps in the buildkite UI
ln -s "$(pwd)/dev/ci/scripts/annotated-command.sh" an 2>/dev/null || true

# Provides secrets to the client integration tests target.
echo -e "build --action_env=GH_TOKEN=$GH_TOKEN\nbuild --action_env=PERCY_TOKEN=$PERCY_TOKEN" >.aspect/bazelrc/ci.generated.bazelrc
