#!/usr/bin/env bash

# shellcheck disable=SC1090
source "$HOME/.profile"

# Fetch the latest origin/main to accurately determine the set of changed
# files on this branch.
echo "Running git fetch..."
git fetch
echo "Running git fetch... done"

## -- START: ADD git lfs
REQUIRED_PKG="git-lfs"
PKG_OK=$(dpkg-query -W --showformat='${Status}\n' $REQUIRED_PKG|grep "install ok installed")
echo "Checking for $REQUIRED_PKG: $PKG_OK"
if [ "" = $PKG_OK ]; then
  echo "No $REQUIRED_PKG. Setting up $REQUIRED_PKG."
  echo "Installing Git LFS..."

  curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
  sudo apt install git-lfs
  git-lfs install

  echo "Git LFS installed"

  echo "Fetching files from Git LFS..."
  git-lfs fetch
  echo "Fetched files from Git LFS"
fi
## -- END: ADD git lfs

# Link command wrapper scripts so we can have more readable steps in the buildkite UI
ln -s "$(pwd)/enterprise/dev/ci/scripts/trace-command.sh" tr 2>/dev/null || true
ln -s "$(pwd)/enterprise/dev/ci/scripts/annotated-command.sh" an 2>/dev/null || true
