#!/usr/bin/env bash

# shellcheck disable=SC1090,SC1091
source "$HOME/.profile"

# Fetch the latest origin/main to accurately determine the set of changed
# files on this branch.
echo "Running git fetch..."
git fetch
echo "Running git fetch... done"

# Link command wrapper scripts so we can have more readable steps in the buildkite UI
ln -s "$(pwd)/enterprise/dev/ci/scripts/annotated-command.sh" an 2>/dev/null || true
