#!/usr/bin/env bash

echo "STEP_START=$STEP_START"
echo "BUILD_START_TIME=$BUILD_START_TIME"

(
    echo "--- Sending stuff to HoneyComb"
    echo "build_id=$BUILDKITE_BUILD_ID step_id=$BUILDKITE_STEP_ID step_start=$STEP_START step_key=$BUILDKITE_STEP_KEY"

    exit_code="$BUILDKITE_COMMAND_EXIT_STATUS"
    BUILDEVENT_APIKEY=$CI_BUILDEVENT_API_KEY
    BUILDEVENT_DATASET="$CI_BUILDEVENT_DATASET"
    export BUILDEVENT_DATASET
    export BUILDEVENT_APIKEY

    buildevents step "$BUILDKITE_BUILD_ID" "$BUILDKITE_STEP_ID" "$STEP_START" "$BUILDKITE_STEP_KEY"

    # We want to report only if we're getting a non zero exit code that is not a soft failure code.
    # Turn the string of exit codes "1 2 3 4" into an array of strings
    IFS=' ' read -ra codes <<<"$SOFT_FAIL_EXIT_CODES 0" # append exit code 0 for the test below.
    for code in "${codes[@]}"; do
        if [ "$code" == "$exit_code" ]; then
            # If the Buildkite exit code is a soft fail, do nothing either.
            exit "$code"
        fi
    done

    # None of the exit codes were 0 or soft fails, report the failure then.
    buildevents build "$BUILDKITE_BUILD_ID" "$BUILD_START_TIME" failure

    # Return the original exit code
    exit "$exit_code"
)
