#!/usr/bin/env bash

(
  BUILDEVENT_APIKEY=$CI_BUILDEVENT_API_KEY
  BUILDEVENT_DATASET=buildkite 
  export BUILDEVENT_APIKEY
  export BUILDEVENT_DATASET
  

  ./buildevents build $BUILDKITE_BUILD_ID 1641318633 failure
)
  if [ $BUILDKITE_COMMAND_EXIT_STATUS -ne 0 ]; then
    ./buildevents build $BUILDKITE_BUILD_ID $BUILD_START_TIME failure
  fi
)
