#!/usr/bin/env bash

set -eu

# Honeycomb's buildevent plumbing.
# -------------------------------

echo "~~~ Setting up Honeycomb tracing for the build"

# Record start time if we need to exit
BUILD_START_TIME=$(curl -H "Authorization: Bearer $BUILDKITE_API_TOKEN" "https://api.buildkite.com/v2/organizations/$BUILDKITE_ORGANIZATION_SLUG/pipelines/$BUILDKITE_PIPELINE_SLUG/builds/$BUILDKITE_BUILD_NUMBER/" | jq -r .started_at)

# Convert to UTC & Epoch
BUILD_START_TIME=$(TZ=UTC date -d "$BUILD_START_TIME" +'%s')
export BUILD_START_TIME

# Init the step
STEP_START=$(date +'%s')
export STEP_START

# Create the folder for annotations
mkdir -p ./annotations/

# asdf setup
# ----------
./dev/ci/asdf-install.sh
