#!/usr/bin/env bash

# About $SOFT_FAIL_EXIT_CODES (example value: "1 2 3 4"):
# It's a quick hack to circumvent the problem describe in
# https://github.com/sourcegraph/sourcegraph/issues/27264.

set -e # Not -u because $SOFT_FAIL_EXIT_CODES may not be bound

if [[ "$BUILDKITE_PIPELINE_NAME" != "sourcegraph" ]]; then
  exit 0
fi

if [ "$BUILDKITE_BRANCH" == "main" ]; then
  # Turn the string of exit codes "1 2 3 4" into an array of strings
  IFS=' ' read -ra codes <<<"$SOFT_FAIL_EXIT_CODES"
  for code in "${codes[@]}"; do
    if [ "$code" == "$BUILDKITE_COMMAND_EXIT_STATUS" ]; then
      # Buildkite exit code is a soft fail
      OVERWRITE_STATE="soft-failed" ./enterprise/dev/ci/scripts/upload-build-logs.sh
    fi
  done

  # Non-zero exit code and not a soft fail: upload the logs.
  if [ "$BUILDKITE_COMMAND_EXIT_STATUS" -eq 0 ]; then
    OVERWRITE_STATE="passed" ./enterprise/dev/ci/scripts/upload-build-logs.sh
  else
    OVERWRITE_STATE="failed" ./enterprise/dev/ci/scripts/upload-build-logs.sh
  fi
fi
