import { CustomIcon } from "@sourcegraph/wildcard/src/components/Icon";
import {
    SiC,
    SiCplusplus,
    SiCsharp,
    SiCssmodules,
    SiDocker,
    SiGit,
    SiGo,
    SiGraphql,
    SiHtml5,
    SiJavascript,
    SiJson,
    SiKotlin,
    SiLua,
    SiMarkdown,
    SiNixos,
    SiNpm,
    SiPerl,
    SiPhp,
    SiPython,
    SiR,
    SiReact,
    SiRuby,
    SiRust,
    SiScala,
    SiSvg,
    SiTypescript,
    SiZig
} from "react-icons/si";
import styles from "./RepoRevisionSidebarFileTree.module.scss"
import { GoDatabase, GoTerminal } from "react-icons/go";
import { FaJava, FaSass } from "react-icons/fa";
import { CiSettings, CiTextAlignLeft } from "react-icons/ci";
import { MdOutlineScience } from "react-icons/md";

export const LogsPageTabs = {
    COMMANDS: 0,
    SYNCLOGS: 1,
} as const

export enum CodeHostType {
    GITHUB = 'github',
    BITBUCKETCLOUD = 'bitbucketCloud',
    BITBUCKETSERVER = 'bitbucketServer',
    GITLAB = 'gitlab',
    GITOLITE = 'gitolite',
    AWSCODECOMMIT = 'awsCodeCommit',
    AZUREDEVOPS = 'azureDevOps',
    OTHER = 'other',
}

export enum Language {
    BASH = 'sh',
    C = 'c',
    CPP = 'cc',
    CSHARP = 'cs',
    CSS = 'css',
    DOCKERIGNORE = 'dockerignore',
    GITIGNORE = 'gitignore',
    GITATTRIBUTES = 'gitattributes',
    GO = 'go',
    GRAPHQL = 'graphql',
    HTML = 'html',
    JAVA = 'java',
    JAVASCRIPT = 'js',
    JSON = 'json',
    JSX = 'jsx',
    KOTLIN = 'kt',
    LOCKFILE = 'lock',
    LUA = 'lua',
    MARKDOWN = 'md',
    NCL = 'ncl',
    NIX = 'nix',
    NPM = 'npmrc',
    PHP = 'php',
    PERL = 'pl',
    PYTHON = 'py',
    R = 'r',
    RUBY = 'rb',
    RUST = 'rs',
    SCALA = 'scala',
    SASS = 'scss',
    SQL = 'sql',
    SVG = 'svg',
    TEST = 'test',
    TYPESCRIPT = 'ts',
    TSX = 'tsx',
    TEXT = 'txt',
    YAML = 'yaml',
    YML = 'yml',
    ZIG = 'zig',
}

export const FILE_ICONS: Map<Language, { icon: CustomIcon; iconClass: string; }> = new Map([
    [Language.BASH, { icon: GoTerminal, iconClass: styles.defaultIcon }],
    [Language.C, { icon: SiC, iconClass: styles.blue }],
    [Language.CPP, { icon: SiCplusplus, iconClass: styles.blue }],
    [Language.CSHARP, { icon: SiCsharp, iconClass: styles.blue }],
    [Language.CSS, { icon: SiCssmodules, iconClass: styles.blue }],
    [Language.DOCKERIGNORE, { icon: SiDocker, iconClass: styles.blue }],
    [Language.GITIGNORE, { icon: SiGit, iconClass: styles.red }],
    [Language.GITATTRIBUTES, { icon: SiGit, iconClass: styles.red }],
    [Language.GO, { icon: SiGo, iconClass: styles.blue }],
    [Language.GRAPHQL, { icon: SiGraphql, iconClass: styles.pink }],
    [Language.HTML, { icon: SiHtml5, iconClass: styles.blue }],
    [Language.JAVA, { icon: FaJava, iconClass: styles.defaultIcon }],
    [Language.JAVASCRIPT, { icon: SiJavascript, iconClass: styles.yellow }],
    [Language.JSX, { icon: SiReact, iconClass: styles.yellow }],
    [Language.JSON, { icon: SiJson, iconClass: styles.defaultIcon }],
    [Language.KOTLIN, { icon: SiKotlin, iconClass: styles.green }],
    [Language.LOCKFILE, { icon: SiJson, iconClass: styles.defaultIcon }],
    [Language.LUA, { icon: SiLua, iconClass: styles.blue }],
    [Language.MARKDOWN, { icon: SiMarkdown, iconClass: styles.blue }],
    [Language.NCL, { icon: CiSettings, iconClass: styles.gray }],
    [Language.NIX, { icon: SiNixos, iconClass: styles.gray }],
    [Language.NPM, { icon: SiNpm, iconClass: styles.red }],
    [Language.PHP, { icon: SiPhp, iconClass: styles.defaultIcon }],
    [Language.PERL, { icon: SiPerl, iconClass: styles.defaultIcon }],
    [Language.PYTHON, { icon: SiPython, iconClass: styles.yellow }],
    [Language.R, { icon: SiR, iconClass: styles.red }],
    [Language.RUBY, { icon: SiRuby, iconClass: styles.red }],
    [Language.RUST, { icon: SiRust, iconClass: styles.defaultIcon }],
    [Language.SCALA, { icon: SiScala, iconClass: styles.red }],
    [Language.SASS, { icon: FaSass, iconClass: styles.pink }],
    [Language.SQL, { icon: GoDatabase, iconClass: styles.blue }],
    [Language.SVG, { icon: SiSvg, iconClass: styles.blue }],
    [Language.TEST, { icon: MdOutlineScience, iconClass: styles.defaultIcon }],
    [Language.TYPESCRIPT, { icon: SiTypescript, iconClass: styles.blue }],
    [Language.TSX, { icon: SiReact, iconClass: styles.blue }],
    [Language.TEXT, { icon: CiTextAlignLeft, iconClass: styles.defaultIcon }],
    [Language.YAML, { icon: CiSettings, iconClass: styles.gray }],
    [Language.YML, { icon: CiSettings, iconClass: styles.gray }],
    [Language.ZIG, { icon: SiZig, iconClass: styles.yellow }]
]);
