import {
    mdiBash,
    mdiCodeJson,
    mdiDocker,
    mdiFileCode,
    mdiFileGifBox,
    mdiFileJpgBox,
    mdiFilePngBox,
    mdiGit,
    mdiGraphql,
    mdiLanguageC,
    mdiLanguageCpp,
    mdiLanguageCsharp,
    mdiLanguageCss3,
    mdiLanguageFortran,
    mdiLanguageGo,
    mdiLanguageHaskell,
    mdiLanguageHtml5,
    mdiLanguageJava,
    mdiLanguageJavascript,
    mdiLanguageKotlin,
    mdiLanguageLua,
    mdiLanguageMarkdown,
    mdiLanguageMarkdownOutline,
    mdiLanguagePhp,
    mdiLanguagePython,
    mdiLanguageR,
    mdiLanguageRuby,
    mdiLanguageRust,
    mdiLanguageSwift,
    mdiLanguageTypescript,
    mdiNpm,
    mdiReact,
    mdiSvg,
    mdiText,
} from '@mdi/js'

export enum FileExtension {
    ASSEMBLY = 'asm',
    BASH = 'sh',
    BASIC = 'vb',
    C = 'c',
    CLOJURE_CLJ = 'clj',
    CLOJURE_CLJS = 'cljs',
    CLOJURE_CLJR = 'cljr',
    CLOJURE_CLJC = 'cljc',
    CLOJURE_EDN = 'edn',
    COFFEE = 'coffee',
    CPP = 'cc',
    CSHARP = 'cs',
    CSS = 'css',
    DART = 'dart',
    DEFAULT = 'default',
    DOCKERFILE = 'Dockerfile',
    DOCKERIGNORE = 'dockerignore',
    FORTRAN_F = 'f',
    FORTRAN_FOR = 'for',
    FORTRAN_FTN = 'ftn',
    FSHARP = 'fs',
    FSI = 'fsi',
    FSX = 'fsx',
    GIF = 'gif',
    GIFF = 'giff',
    GITIGNORE = 'gitignore',
    GITATTRIBUTES = 'gitattributes',
    GO = 'go',
    GOMOD = 'mod',
    GOSUM = 'sum',
    GRAPHQL = 'graphql',
    GROOVY = 'groovy',
    HASKELL = 'hs',
    HTML = 'html',
    JAVA = 'java',
    JAVASCRIPT = 'js',
    JPG = 'jpg',
    JPEG = 'jpeg',
    JSON = 'json',
    JSX = 'jsx',
    JULIA = 'jl',
    KOTLIN = 'kt',
    LOCKFILE = 'lock',
    LUA = 'lua',
    MARKDOWN = 'md',
    MDX = 'mdx',
    NCL = 'ncl',
    NIX = 'nix',
    NPM = 'npmrc',
    OCAML = 'ml',
    PHP = 'php',
    PERL = 'pl',
    PERL_PM = 'pm',
    PNG = 'png',
    POWERSHELL_PS1 = 'ps1',
    POWERSHELL_PSM1 = 'psm1',
    PYTHON = 'py',
    R = 'r',
    R_CAP = 'R',
    RUBY = 'rb',
    RUST = 'rs',
    SCALA = 'scala',
    SASS = 'scss',
    SQL = 'sql',
    SVELTE = 'svelte',
    SVG = 'svg',
    SWIFT = 'swift',
    TEST = 'test',
    TYPESCRIPT = 'ts',
    TSX = 'tsx',
    TEXT = 'txt',
    YAML = 'yaml',
    YML = 'yml',
    ZIG = 'zig',
}

export interface IconInfoSvelte {
    svgPath: string
    iconClass: string
}

export const FILE_ICONS: Map<FileExtension, IconInfoSvelte> = new Map([
    [FileExtension.ASSEMBLY, { svgPath: mdiFileCode, iconClass: 'default-icon' }],
    [FileExtension.BASH, { svgPath: mdiBash, iconClass: 'default-icon' }],
    [FileExtension.BASIC, { svgPath: mdiFileCode, iconClass: 'default-icon' }],
    [FileExtension.C, { svgPath: mdiLanguageC, iconClass: 'blue' }],
    [FileExtension.CLOJURE_CLJ, { svgPath: mdiFileCode, iconClass: 'blue' }],
    [FileExtension.CLOJURE_CLJC, { svgPath: mdiFileCode, iconClass: 'blue' }],
    [FileExtension.CLOJURE_CLJR, { svgPath: mdiFileCode, iconClass: 'blue' }],
    [FileExtension.CLOJURE_CLJS, { svgPath: mdiFileCode, iconClass: 'blue' }],
    [FileExtension.CLOJURE_EDN, { svgPath: mdiFileCode, iconClass: 'blue' }],
    [FileExtension.COFFEE, { svgPath: mdiFileCode, iconClass: 'default-icon' }],
    [FileExtension.CPP, { svgPath: mdiLanguageCpp, iconClass: 'blue' }],
    [FileExtension.CSHARP, { svgPath: mdiLanguageCsharp, iconClass: 'blue' }],
    [FileExtension.CSS, { svgPath: mdiLanguageCss3, iconClass: 'blue' }],
    [FileExtension.DART, { svgPath: mdiFileCode, iconClass: 'blue' }],
    [FileExtension.DEFAULT, { svgPath: mdiFileCode, iconClass: 'gray' }],
    [FileExtension.DOCKERFILE, { svgPath: mdiDocker, iconClass: 'blue' }],
    [FileExtension.DOCKERIGNORE, { svgPath: mdiDocker, iconClass: 'blue' }],
    [FileExtension.FORTRAN_F, { svgPath: mdiLanguageFortran, iconClass: 'default-icon' }],
    [FileExtension.FORTRAN_FOR, { svgPath: mdiLanguageFortran, iconClass: 'default-icon' }],
    [FileExtension.FORTRAN_FTN, { svgPath: mdiLanguageFortran, iconClass: 'default-icon' }],
    [FileExtension.FSHARP, { svgPath: mdiFileCode, iconClass: 'blue' }],
    [FileExtension.FSI, { svgPath: mdiFileCode, iconClass: 'blue' }],
    [FileExtension.FSX, { svgPath: mdiFileCode, iconClass: 'blue' }],
    [FileExtension.GIF, { svgPath: mdiFileGifBox, iconClass: 'default-icon' }],
    [FileExtension.GIFF, { svgPath: mdiFileGifBox, iconClass: 'default-icon' }],
    [FileExtension.GITIGNORE, { svgPath: mdiGit, iconClass: 'red' }],
    [FileExtension.GITATTRIBUTES, { svgPath: mdiGit, iconClass: 'red' }],
    [FileExtension.GO, { svgPath: mdiLanguageGo, iconClass: 'blue' }],
    [FileExtension.GOMOD, { svgPath: mdiLanguageGo, iconClass: 'pink' }],
    [FileExtension.GOSUM, { svgPath: mdiLanguageGo, iconClass: 'pink' }],
    [FileExtension.GROOVY, { svgPath: mdiFileCode, iconClass: 'blue' }],
    [FileExtension.GRAPHQL, { svgPath: mdiGraphql, iconClass: 'pink' }],
    [FileExtension.HASKELL, { svgPath: mdiLanguageHaskell, iconClass: 'blue' }],
    [FileExtension.HTML, { svgPath: mdiLanguageHtml5, iconClass: 'blue' }],
    [FileExtension.JAVA, { svgPath: mdiLanguageJava, iconClass: 'default-icon' }],
    [FileExtension.JAVASCRIPT, { svgPath: mdiLanguageJavascript, iconClass: 'yellow' }],
    [FileExtension.JPG, { svgPath: mdiFileJpgBox, iconClass: 'yellow' }],
    [FileExtension.JPEG, { svgPath: mdiFileJpgBox, iconClass: 'yellow' }],
    [FileExtension.JSX, { svgPath: mdiReact, iconClass: 'yellow' }],
    [FileExtension.JSON, { svgPath: mdiCodeJson, iconClass: 'default-icon' }],
    [FileExtension.JULIA, { svgPath: mdiFileCode, iconClass: 'default-icon' }],
    [FileExtension.KOTLIN, { svgPath: mdiLanguageKotlin, iconClass: 'green' }],
    [FileExtension.LOCKFILE, { svgPath: mdiCodeJson, iconClass: 'default-icon' }],
    [FileExtension.LUA, { svgPath: mdiLanguageLua, iconClass: 'blue' }],
    [FileExtension.MARKDOWN, { svgPath: mdiLanguageMarkdown, iconClass: 'blue' }],
    [FileExtension.MDX, { svgPath: mdiLanguageMarkdownOutline, iconClass: 'blue' }],
    [FileExtension.NCL, { svgPath: mdiFileCode, iconClass: 'default-icon' }],
    [FileExtension.NIX, { svgPath: mdiFileCode, iconClass: 'gray' }],
    [FileExtension.NPM, { svgPath: mdiNpm, iconClass: 'red' }],
    [FileExtension.OCAML, { svgPath: mdiFileCode, iconClass: 'yellow' }],
    [FileExtension.PHP, { svgPath: mdiLanguagePhp, iconClass: 'cyan' }],
    [FileExtension.PERL, { svgPath: mdiFileCode, iconClass: 'default-icon' }],
    [FileExtension.PERL_PM, { svgPath: mdiFileCode, iconClass: 'default-icon' }],
    [FileExtension.PNG, { svgPath: mdiFilePngBox, iconClass: 'default-icon' }],
    [FileExtension.POWERSHELL_PS1, { svgPath: mdiBash, iconClass: 'default-icon' }],
    [FileExtension.POWERSHELL_PSM1, { svgPath: mdiBash, iconClass: 'default-icon' }],
    [FileExtension.PYTHON, { svgPath: mdiLanguagePython, iconClass: 'blue' }],
    [FileExtension.R, { svgPath: mdiLanguageR, iconClass: 'red' }],
    [FileExtension.R_CAP, { svgPath: mdiLanguageR, iconClass: 'red' }],
    [FileExtension.RUBY, { svgPath: mdiLanguageRuby, iconClass: 'red' }],
    [FileExtension.RUST, { svgPath: mdiLanguageRust, iconClass: 'default-icon' }],
    [FileExtension.SCALA, { svgPath: mdiFileCode, iconClass: 'red' }],
    [FileExtension.SASS, { svgPath: mdiFileCode, iconClass: 'pink' }],
    [FileExtension.SQL, { svgPath: mdiFileCode, iconClass: 'blue' }],
    [FileExtension.SVELTE, { svgPath: mdiFileCode, iconClass: 'red' }],
    [FileExtension.SVG, { svgPath: mdiSvg, iconClass: 'blue' }],
    [FileExtension.SWIFT, { svgPath: mdiLanguageSwift, iconClass: 'blue' }],
    [FileExtension.TYPESCRIPT, { svgPath: mdiLanguageTypescript, iconClass: 'blue' }],
    [FileExtension.TSX, { svgPath: mdiReact, iconClass: 'blue' }],
    [FileExtension.TEXT, { svgPath: mdiText, iconClass: 'default-icon' }],
    [FileExtension.YAML, { svgPath: mdiFileCode, iconClass: 'default-icon' }],
    [FileExtension.YML, { svgPath: mdiFileCode, iconClass: 'default-icon' }],
    [FileExtension.ZIG, { svgPath: mdiFileCode, iconClass: 'yellow' }],
])
