fragment HistoryPanel_HistoryConnection on GitCommitConnection {
    nodes {
        id
        oid
        abbreviatedOID
        subject
        author {
            date
            person {
                displayName
                ...Avatar_Person
            }
        }
        canonicalURL
    }
    pageInfo {
        hasNextPage
        endCursor
    }
}
