fragment HistoryPanel_HistoryConnection on GitCommitConnection {
    nodes {
        id
        abbreviatedOID
        subject
        author {
            date
            person {
                avatarURL
                name
                displayName
            }
        }
        canonicalURL
    }
    pageInfo {
        hasNextPage
        endCursor
    }
}
