user: User {
    shape: person
}
vscode: VS Code {
    code: Local code
    io: IO
    git: Git cli
}
web: Web
cody: Cody
embed: Embedding\nService
extsvc: Code hosts
source: Source\nCode graph
codesearch: Code\nSearch
plugins: Plugins {
    confluence: Confluence\nPlugin
    git: Git\nPlugin
    excalidraw: Excalidraw\nPlugin
}
confluence_plugin_server: Confluence\nPlugin Server
confluence: Confluence\nWiki

source -> extsvc
source <- embed
source <- codesearch

user -> vscode
user -> web
cody <- vscode
cody <- web
cody -> embed
cody -> codesearch
cody <-> plugins

plugins.confluence -> confluence_plugin_server
confluence_plugin_server -> confluence
