# shape: sequence_diagram
direction: up
plugin_api: Cody Plugins {
    runtime: Plugins Runtime
    sdk_api: Plugins API {
        data_providers: data source\nproviders {
            style {
                multiple: true
            }
        }
        commands {
            style {
                multiple: true
            }
        }
    }

    runtime <- sdk_api.data_providers
    runtime <- sdk_api.commands
}
sg: Sourcegraph instance {
    embeddings: Embeddings Service
    code_search: Code Search Service
}
user: User {
    shape: person
}
cody_clients: Cody Clients {
    cody: VS Code Cody
    web: Sourcegraph Web Cody
    intellij: IntelliJ Cody
}
cody: Cody
confluence_plugin: Confluence Plugin {
    shape: package
}
conflence_instance: Confluence Instance {
    shape: cloud
}
confluence_embeddedings: Confluence\nEmbeddedings Service {
    shape: cylinder
}
slack_plugin: Slack Plugin {
    shape: package
    style {
        fill: "#e6e6e6"
        stroke-width: 0
    }
}
sentry_plugin: Sentry Plugin {
    shape: package
    style {
        fill: "#e6e6e6"
        stroke-width: 0
    }
}
github_plugin: GH Issues/PRs Plugin {
    shape: package
    style {
        fill: "#e6e6e6"
        stroke-width: 0
    }
}
confluence_embeddedings <-> conflence_instance: sync and embed periodically

user <-> cody_clients.cody: 1. write a message
cody_clients.cody <-> cody: \n2. send context\n& message
cody <-> sg.embeddings: 3.1 get embedded repo context
cody <-> sg.code_search: 3.2 get keyword\nindexed repo context
plugin_api.runtime -> cody : 3.3 add,\nupdate context

confluence_plugin -> plugin_api.sdk_api.data_providers: search_by_content,\nsearch_by_title,\nsearch_by_query,
confluence_plugin -> plugin_api.sdk_api.commands: create_page,\ncreate_comment, etc.
confluence_plugin <-> confluence_embeddedings
confluence_plugin <-> conflence_instance: use directly confluence API

plugin_api.runtime -> cody: 4.1 add/update response\ne.g visualization
cody -> cody_clients.cody: 5.3 send response
cody_clients.cody -> user: 6.1 show response

slack_plugin <-> plugin_api.sdk_api
sentry_plugin <-> plugin_api.sdk_api
github_plugin <-> plugin_api.sdk_api

