FROM sourcegraph/alpine-3.14:180512_2022-10-31_84d1e240bb40@sha256:179ad53ab463ebc804f93de967113739fa73efc2cea6d9c53a9106be45f79d5e

ARG COMMIT_SHA="unknown"
ARG DATE="unknown"
ARG VERSION="unknown"

LABEL org.opencontainers.image.revision=${COMMIT_SHA}
LABEL org.opencontainers.image.created=${DATE}
LABEL org.opencontainers.image.version=${VERSION}
LABEL com.sourcegraph.github.url=https://github.com/sourcegraph/sourcegraph/commit/${COMMIT_SHA}

RUN apk add --no-cache \
    bash

RUN mkdir -p /data && chown -R sourcegraph:sourcegraph /data
USER sourcegraph

EXPOSE 9000
WORKDIR /
ENTRYPOINT ["/sbin/tini", "--", "/usr/local/bin/blobstore"]
COPY blobstore /usr/local/bin/
