export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN";

export const FETCHED_AUTH_INFO = "FETCHED_AUTH_INFO";

export const RESOLVED_REV = "RESOLVED_REV";

export const FETCHED_SRCLIB_DATA_VERSION = "FETCHED_SRCLIB_DATA_VERSION";

export const FETCHED_DEF = "FETCHED_DEF";

export const WANT_DEFS = "WANT_DEFS";
export const FETCHED_DEFS = "FETCHED_DEFS";

export const FETCHED_ANNOTATIONS = "FETCHED_ANNOTATIONS";
