export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN";

export const SET_REPO_REV = "SET_REPO_REV";
export const SET_PATH = "SET_PATH";

export const SET_QUERY = "SET_QUERY";

export const WANT_SRCLIB_DATA_VERSION = "WANT_SRCLIB_DATA_VERSION";
export const FETCHED_SRCLIB_DATA_VERSION = "FETCHED_SRCLIB_DATA_VERSION";

export const WANT_DEFS = "WANT_DEFS";
export const FETCHED_DEFS = "FETCHED_DEFS";

export const WANT_ANNOTATIONS = "WANT_ANNOTATIONS";
export const FETCHED_ANNOTATIONS = "FETCHED_ANNOTATIONS";

export const EXPIRE_DEFS = "EXPIRE_DEFS";
export const EXPIRE_ANNOTATIONS = "EXPIRE_ANNOTATIONS";
export const EXPIRE_SRCLIB_DATA_VERSION = "EXPIRE_SRCLIB_DATA_VERSION";
