export const repoMockedModel = [
    'almeidapaulooliveira/ant-design',
    'sourcegraph/sourcegraph',
    'almeidapaulooliveira/react-custom-scrollbars',
    'almeidapaulooliveira/react-packages',
    'bartonhammond/meteor-slingshot',
    'primer/react',
    'redis/redis',
    'facebook/react',
    'npm/npm',
    'npm/cli',
    'docker/app',
    'kubernetes/dashboard',
    'kubernetes/website',
    'kubernetes/kubernetes',
    'kubernetes/minikube',
    'nginx/docker-nginx',
    'opencontainers/runc',
    'opencontainers/image-spec',
    'ant-design/ant-design',
    'ant-design/ant-design-pro',
    'ant-design/ant-design-pro-layout',
    'ant-design/ant-design-icons',
    'ant-design/ant-design-pro-blocks',
    'ant-design/ant-design-pro-cli',
    'ant-design/ant-design-pro-site',
    'ant-design/ant-design-pro-table',
    'ant-design/ant-design-pro-form',
    'ant-design/ant-design-pro-list',
    'ant-design/ant-design-pro-field',
    'ant-design/ant-design-pro-descriptions',
]

export const filesMockedModel = [
    { file: 'CodyChat.tsx', path: 'sourcegraph/sourcegraph/client/cody-ui/src' },
    { file: 'CodyChatView.tsx', path: 'sourcegraph/sourcegraph/client/cody-ui/src' },
    { file: 'Cody.ts', path: 'sourcegraph/sourcegraph/client/cody-ui/src' },
    { file: 'CodyLogo.ts', path: 'sourcegraph/sourcegraph/client/cody-ui/src/icons' },
    { file: 'CodyModel.ts', path: 'sourcegraph/sourcegraph/client/models' },
    { file: 'CustomScroller.tsx', path: 'almeidapaulooliveira/react-custom-scrollbars' },
    { file: 'argos-upload.ts', path: 'ant-design/ant-design/scripts' },
    { file: 'SingleNumber.tsx', path: 'ant-design/ant-design/components/badge' },
    { file: 'button.tsx', path: 'ant-design/ant-design/components/button' },
    { file: 'CollapsePanel.tsx', path: 'ant-design/ant-design/components/collapse' },
    { file: 'Collapse.tsx', path: 'ant-design/ant-design/components/collapse' },
    { file: 'PreviewGroup.tsx', path: 'ant-design/ant-design/components/image' },
    { file: 'index.js', path: 'almeidapaulooliveira/react-custom-scrollbars/src/Scrollbars' },
    { file: 'getInnerHeight.js', path: 'almeidapaulooliveira/react-custom-scrollbars/src/utils' },
    { file: 'getInnerWidth.js', path: 'almeidapaulooliveira/react-custom-scrollbars/src/utils' },
    { file: 'getScrollbarWidth.js', path: 'almeidapaulooliveira/react-custom-scrollbars/src/utils' },
    { file: 'quiz.js', path: 'kubernetes/minikube/site/static/js' },
    { file: 'resetdeps.js', path: 'npm/cli/cli/scripts' },
    { file: 'publish.js', path: 'npm/cli/cli/scripts' },
    { file: 'create-node-pr.js', path: 'npm/cli/cli/scripts' },
    { file: 'fish-completion.js', path: 'npm/cli/cli/scripts' },
    { file: 'acl.c', path: 'redis/redis/src' },
    { file: 'adlist.c', path: 'redis/redis/src' },
    { file: 'adlist.h', path: 'redis/redis/src' },
    { file: 'ae.c', path: 'redis/redis/src' },
    { file: 'ae.h', path: 'redis/redis/src' },
    { file: 'ae_epoll.c', path: 'redis/redis/src' },
]
