import { CodeHosts, RepogroupMetadata } from './types'

export const android: RepogroupMetadata = {
    title: 'Android',
    name: 'android',
    url: '/android',
    repositories: [
        { name: "github.com/kotlin/kotlinx.serialization", codehost: CodeHosts.GITHUB },
        { name: "github.com/kotlin/dokka", codehost: CodeHosts.GITHUB },
        { name: "github.com/kotlin/kotlinx.coroutines", codehost: CodeHosts.GITHUB },
        { name: "github.com/kotlin/kotlin-fullstack-sample", codehost: CodeHosts.GITHUB },
        { name: "github.com/google/dagger", codehost: CodeHosts.GITHUB },
        { name: "github.com/square/retrofit", codehost: CodeHosts.GITHUB },
        { name: "github.com/square/okhttp", codehost: CodeHosts.GITHUB },
        { name: "github.com/square/moshi", codehost: CodeHosts.GITHUB },
        { name: "github.com/jgilfelt/chuck", codehost: CodeHosts.GITHUB },
        { name: "github.com/google/gson", codehost: CodeHosts.GITHUB },
        { name: "github.com/bumptech/glide", codehost: CodeHosts.GITHUB },
        { name: "github.com/ReactiveX/RxJava", codehost: CodeHosts.GITHUB },
        { name: "github.com/JakeWharton/timber", codehost: CodeHosts.GITHUB },
        { name: "github.com/JakeWharton/ThreeTenABP", codehost: CodeHosts.GITHUB },
        { name: "github.com/cashapp/sqldelight", codehost: CodeHosts.GITHUB },
        { name: "github.com/JakeWharton/SdkSearch", codehost: CodeHosts.GITHUB },
        { name: "github.com/JakeWharton/butterknife", codehost: CodeHosts.GITHUB },
        { name: "github.com/JakeWharton/Telecine", codehost: CodeHosts.GITHUB },
        { name: "github.com/YiiGuxing/TranslationPlugin", codehost: CodeHosts.GITHUB },
        { name: "github.com/pbreault/adb-idea", codehost: CodeHosts.GITHUB },
        { name: "github.com/JetBrains/kotlin", codehost: CodeHosts.GITHUB },
        { name: "github.com/JetBrains/intellij-plugins", codehost: CodeHosts.GITHUB },
        { name: "github.com/JetBrains/intellij-community", codehost: CodeHosts.GITHUB },
        { name: "github.com/JetBrains/kotlin-native", codehost: CodeHosts.GITHUB },
        { name: "github.com/JetBrains/kotlin-web-site", codehost: CodeHosts.GITHUB },
        { name: "github.com/JetBrains/ideavim", codehost: CodeHosts.GITHUB },
        { name: "github.com/android/kotlin", codehost: CodeHosts.GITHUB },
        { name: "github.com/android/user-interface-samples", codehost: CodeHosts.GITHUB },
        { name: "github.com/android/views-widgets-samples", codehost: CodeHosts.GITHUB },
        { name: "github.com/android/animation-samples", codehost: CodeHosts.GITHUB },
        { name: "github.com/android/play-billing-samples", codehost: CodeHosts.GITHUB },
        { name: "github.com/android/architecture-samples", codehost: CodeHosts.GITHUB },
        { name: "github.com/android/location-samples", codehost: CodeHosts.GITHUB },
        { name: "github.com/android/camera-samples", codehost: CodeHosts.GITHUB },
        { name: "github.com/android/compose-samples", codehost: CodeHosts.GITHUB },
        { name: "github.com/android/ndk-samples", codehost: CodeHosts.GITHUB },
        { name: "github.com/android/plaid", codehost: CodeHosts.GITHUB },
        { name: "github.com/android/topeka", codehost: CodeHosts.GITHUB },
        { name: "github.com/android/testing-samples", codehost: CodeHosts.GITHUB },
        { name: "github.com/android/databinding-samples", codehost: CodeHosts.GITHUB },
        { name: "github.com/android/kotlin-guides", codehost: CodeHosts.GITHUB },
        { name: "github.com/android/android-test", codehost: CodeHosts.GITHUB },
        { name: "github.com/android/uamp", codehost: CodeHosts.GITHUB },
        { name: "github.com/android/sunflower", codehost: CodeHosts.GITHUB },
        { name: "github.com/skydoves/TransformationLayout", codehost: CodeHosts.GITHUB },
        { name: "github.com/codepath/android_guides", codehost: CodeHosts.GITHUB },
        { name: "github.com/google/iosched", codehost: CodeHosts.GITHUB },
        { name: "github.com/futurice/android-best-practices", codehost: CodeHosts.GITHUB },
        { name: "github.com/lgvalle/Material-Animations", codehost: CodeHosts.GITHUB },
        { name: "github.com/wasabeef/awesome-android-ui", codehost: CodeHosts.GITHUB },
        { name: "github.com/nisrulz/android-tips-tricks", codehost: CodeHosts.GITHUB },
        { name: "github.com/MindorksOpenSource/from-java-to-kotlin", codehost: CodeHosts.GITHUB },
        { name: "github.com/dbacinski/Design-Patterns-In-Kotlin", codehost: CodeHosts.GITHUB },
        { name: "github.com/Solido/awesome-flutter", codehost: CodeHosts.GITHUB },
        { name: "github.com/iampawan/FlutterExampleApps", codehost: CodeHosts.GITHUB },
        { name: "github.com/mitesh77/Best-Flutter-UI-Templates", codehost: CodeHosts.GITHUB },
    ],
    description: 'Interesting examples of Go.',
    examples: [
        {
            title: 'Search for usages of the Retry-After header in non-vendor Go files:',
            exampleQuery:
                '<span class="repogroup-page__keyword-text">file:</span>.go <span class="repogroup-page__keyword-text">-file:</span>vendor/ Retry-After',
        },
        {
            title: 'Find examples of sending JSON in a HTTP POST request:',
            exampleQuery: 'repogroup:goteam <span class="repogroup-page__keyword-text">file:</span>.go http.Post json',
        },
        {
            title: 'Find error handling examples in Go',
            exampleQuery: 'if err != nil {:[_]} <span class="repogroup-page__keyword-text">lang:</span>go',
        },
        {
            title: 'Find usage examples of cmp.Diff with options',
            exampleQuery: '<span class="repogroup-page__keyword-text">lang:go</span> cmp.Diff(:[_], :[_], :[opts])',
        },
        {
            title: 'Find examples for setting timeouts on http.Transport',
            exampleQuery:
                'http.Transport{:[_], MaxIdleConns: :[idleconns], :[_]} <span class="repogroup-page__keyword-text">-file:</span>vendor <span class="repogroup-page__keyword-text">lang:</span>go',
        },
        {
            title: 'Find examples of Switch statements in Go',
            exampleQuery:
                'switch :[_] := :[_].(type) { :[string] } <span class="repogroup-page__keyword-text">lang:</span>go <span class="repogroup-page__keyword-text">count:</span>1000',
        },
    ],
    homepageDescription: 'Interesting examples of Go.',
    homepageIcon: 'https://code.benco.io/icon-collection/logos/go-lang.svg',
}
