import { CodeHosts, RepogroupMetadata } from './types'
import { SearchPatternType } from '../../../shared/src/graphql/schema'
import * as React from 'react'

export const ethereum: RepogroupMetadata = {
    title: 'Ethereum',
    name: 'ethereum',
    url: '/ethereum',
    repositories: [
        { name: 'ethereum/alethzero', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/bench', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/benchmarking', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/blockies', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/branding', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/browser-solidity', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/btcrelay', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/casper', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/cbc-casper', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/common', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/cpp-dependencies', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/cpp-dependencies-win64', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/cpp-ethash', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/cpp-ethereum', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/cpp-ethereum-cmake', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/cryptopp', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/dapp-bin', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/dapp-styles', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/devcommon', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/devp2p', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/diary', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/documentation', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/dopple', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/economic-modeling', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/ecp', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/EIPs', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/emacs-solidity', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/ens', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/ens-registrar-dapp', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/eth-abi', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/eth-account', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/eth-bloom', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/eth-keyfile', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/eth-keys', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/eth-rlp', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/eth-tester', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/eth-utils', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/ethash', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/ethbot', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/ethdev-site', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/ethendance', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/ethereum-buildbot', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/ethereum-client-binaries', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/ethereum-console', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/ethereum-dockers', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/ethereum-docs', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/ethereum-org', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/ethereum-org-website', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/ethereum-ppa', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/ethereum.org', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/ethereumj', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/evmc', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/evmjit', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/foundation', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/frontier-guide', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/gav', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/genesis_block_generator', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/gethkey', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/go-build', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/go-casper', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/go-ethereum', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/guide', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/homebrew-ethereum', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/homestead-guide', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/hunter-cache', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/interfaces', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/jeff', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/jenkins-docker', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/langlab', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/leveldb', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/libethereum', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/libsnark', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/libweb3core', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/libwhisper', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/meteor-dapp-catalog', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/meteor-dapp-wallet', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/meteor-dapp-whisper-chat-client', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/meteor-ethereum-networkinfo', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/meteor-package-accounts', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/meteor-package-blocks', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/meteor-package-elements', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/meteor-package-tools', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/mining', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/mist', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/mix', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/moon-browser', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/moon-lang', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/moon-tool', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/natspec.js', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/news', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/node-ethereum', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/oyente', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/plasma', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/pm', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/populus', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/profiling', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/py-evm', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/py-geth', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/py-solc', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/py-trie', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/pydevp2p', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/pyethapp', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/pyethereum', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/pyethsaletool', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/pyeth_keys', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/pyrlp', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/py_ecc', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/py_pairing', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/remix', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/remix-core', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/remix-debugger', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/remix-lib', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/remix-live', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/remix-solidity', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/remix-tests', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/remixd', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/research', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/ropsten', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/rpc-tests', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/scavenger_hunt', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/serpent', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/serpent-go', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/sharding', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/simplecasper', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/solc-bin', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/solc-js', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/solidity', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/solidity-examples', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/solidity-test-bytecode', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/solidity.js', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/stake-voice', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/statesweep', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/swarm-dapps', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/system-testing', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/test-tools', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/tests', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/tryethereum', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/vim-solidity', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/vyper', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/web3.js', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/web3.py', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/webthree', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/webthree-helpers', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/webthree-umbrella', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/wiki', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/www', codehost: CodeHosts.GITHUB },
        { name: 'ethereum/yellowpaper', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/browser-builds', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/common', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/eth-bin-to-method-ids', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/eth-bin-to-ops', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/eth-query', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/ethashjs', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/ethereumjs-abi', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/ethereumjs-account', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/ethereumjs-block', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/ethereumjs-blockchain', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/ethereumjs-blockstream', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/ethereumjs-connect', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/ethereumjs-devp2p', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/ethereumjs-icap', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/ethereumjs-ledger', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/ethereumjs-lib', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/ethereumjs-stub-rpc-server', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/ethereumjs-testing', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/ethereumjs-tx', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/ethereumjs-units', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/ethereumjs-util', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/ethereumjs-vm', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/ethereumjs-wallet', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/ethereumjs.github.io', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/ethrpc', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/geth.js', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/helpeth', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/ideas', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/keythereum', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/merkle-patricia-tree', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/node-blockchain-server', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/node-devp2p', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/node-devp2p-dpt', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/node-devp2p-eth', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/node-devp2p-rlpx', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/node-ethash', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/organization', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/rlp', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/rustbn.js', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/solidity.js', codehost: CodeHosts.GITHUB },
        { name: 'ethereumjs/tests', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/benchmark', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/bountyetc', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/btcrelay', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/classic-dapp-ui', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/Cloud-Template', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/cpp-ethereum', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/dapp-styles', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/docs-website', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/easm', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/ecip1017test', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/ECIPs', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/emerald-cli', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/emerald-js', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/emerald-js-ui', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/emerald-mobile-wallet', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/emerald-platform', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/emerald-rocksdb', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/emerald-rs', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/emerald-wallet', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/etcommon-rs', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/ethash', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/ethereum-classic-client-binaries', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/etherkube', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/etherup', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/etherwallet', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/explorer', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/geth-ELK', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/gitbook-plugin-coss', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/go-ethereum', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/hmac-drbg-rs', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/homebrew-classic', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/homerun', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/janus', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/libsecp256k1-rs', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/metamask-plugin', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/meteor-dapp-wallet', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/meteor-package-accounts', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/meteor-package-blocks', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/meteor-package-elements', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/meteor-package-tools', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/mist', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/parity', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/Peridot', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/phoenix-project', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/project-funding', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/pydevp2p', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/pyethapp', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/pyethereum', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/README', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/rfc', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/smart-contract-tools', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/social-fork-analysis', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/sputnikvm', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/sputnikvm-callback', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/sputnikvm-dev', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/sputnikvm-dev-web', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/sputnikvm-ffi', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/tests', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/TokenMint', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/volunteer', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/wasm2evm', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/web3.js', codehost: CodeHosts.GITHUB },
        { name: 'ethereumproject/wiki', codehost: CodeHosts.GITHUB },
        { name: 'ewasm/bn', codehost: CodeHosts.GITHUB },
        { name: 'ewasm/c-libeth', codehost: CodeHosts.GITHUB },
        { name: 'ewasm/design', codehost: CodeHosts.GITHUB },
        { name: 'ewasm/evm2wasm', codehost: CodeHosts.GITHUB },
        { name: 'ewasm/evm2wasm-frontend', codehost: CodeHosts.GITHUB },
        { name: 'ewasm/ewasm-cleanup', codehost: CodeHosts.GITHUB },
        { name: 'ewasm/ewasm-kernel', codehost: CodeHosts.GITHUB },
        { name: 'ewasm/ewasm-tests', codehost: CodeHosts.GITHUB },
        { name: 'ewasm/fixed-bn.js', codehost: CodeHosts.GITHUB },
        { name: 'ewasm/hera', codehost: CodeHosts.GITHUB },
        { name: 'ewasm/pm', codehost: CodeHosts.GITHUB },
        { name: 'ewasm/rust-ewasm', codehost: CodeHosts.GITHUB },
        { name: 'ewasm/testnet', codehost: CodeHosts.GITHUB },
        { name: 'ewasm/tests', codehost: CodeHosts.GITHUB },
        { name: 'ewasm/wasm-gc', codehost: CodeHosts.GITHUB },
        { name: 'ewasm/wasm-json-toolkit', codehost: CodeHosts.GITHUB },
        { name: 'ewasm/wasm-metering', codehost: CodeHosts.GITHUB },
        { name: 'ewasm/wasm-metering-old', codehost: CodeHosts.GITHUB },
        { name: 'ewasm/wast2wasm', codehost: CodeHosts.GITHUB },
    ],
    description:
        'Search across core ethereum code. Includes repositories from the ethereum, ethereumJS, and ewasm organizations. Compose a search query using regex or exact matches, and narrow your search using filters such as `file:` and `repo:`. Read the code search documentation to see all search features and filters.',
    examples: [
        {
            title: 'Search for usages of `CALLCODE` or `DELEGATECALL`:',
            exampleQuery: (
                <>
                    <span className="repogroup-page__keyword-text">case:</span>
                    {'yes (CALLCODE|DELEGATECALL)'}
                </>
            ),
            rawQuery: 'case:yes (CALLCODE|DELEGATECALL)',
            patternType: SearchPatternType.regexp,
        },
        {
            title: 'Find usages of `ECDSA`:',
            exampleQuery: <>{'ECDSA'}</>,
            rawQuery: 'ECDSA',
            patternType: SearchPatternType.regexp,
        },
        {
            title: 'Usages of `eth_sendTransaction` or `eth_call`:',
            exampleQuery: <>{'eth_(sendTransaction|call)'}</>,
            rawQuery: 'eth_(sendTransaction|call)',
            patternType: SearchPatternType.regexp,
        },
    ],
    homepageDescription: 'Search across core ethereum code.',
    homepageIcon: 'https://upload.wikimedia.org/wikipedia/commons/0/05/Ethereum_logo_2014.svg',
}
