import { CodeHosts, RepogroupMetadata } from './types'
import { SearchPatternType } from '../../../shared/src/graphql/schema'
import * as React from 'react'

export const kubernetes: RepogroupMetadata = {
    title: 'Kubernetes',
    name: 'kubernetes',
    url: '/kubernetes',
    repositories: [
        { name: 'kubernetes/kubernetes', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes/heapster', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes/contrib', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes/dashboard', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes/kubernetes-anywhere', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes/website', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes/kubernetes-docs-zh', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes/release', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes/kube-deploy', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes/minikube', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes/test-infra', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes/features', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes/community', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes/kube-state-metrics', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes/node-problem-detector', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes/frakti', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes/kompose', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes/kops', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes/kubernetes-template-project', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes/git-sync', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes/k8s.io', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes/client-go', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes/gengo', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes/perf-tests', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes/ingress-nginx', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes/kubeadm', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes/repo-infra', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes/dns', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes/apimachinery', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes/apiserver', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-sigs/poseidon', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-sigs/kubeadm-dind-cluster', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-sigs/aws-alb-ingress-controller', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-sigs/aws-iam-authenticator', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-sigs/testing_frameworks', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-sigs/federation-v2', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-sigs/application', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-sigs/cluster-api', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-sigs/aws-encryption-provider', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-sigs/kubebuilder', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-sigs/kustomize', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-sigs/controller-runtime', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-sigs/gcp-compute-persistent-disk-csi-driver', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-sigs/cluster-api-provider-openstack', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-sigs/controller-tools', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-sigs/architecture-tracking', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-sigs/gcp-filestore-csi-driver', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-sigs/cluster-api-provider-gcp', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-sigs/cluster-api-provider-aws', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-sigs/contributor-site', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-sigs/cluster-api-provider-vsphere', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-sigs/contributor-playground', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-sigs/kube-storage-version-migrator', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-client/python', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-client/gen', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-client/go-base', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-client/go', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-client/python-base', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-client/javascript', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-client/ruby', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-client/java', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-client/csharp', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-client/haskell', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-incubator/kubespray', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-incubator/bootkube', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-incubator/node-feature-discovery', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-incubator/cluster-proportional-autoscaler', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-incubator/rktlet', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-incubator/cri-o', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-incubator/service-catalog', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-incubator/spartakus', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-incubator/cluster-capacity', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-incubator/kube-aws', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-incubator/nfs-provisioner', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-incubator/reference-docs', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-incubator/cri-tools', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-incubator/external-dns', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-incubator/external-storage', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-incubator/custom-metrics-apiserver', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-incubator/apiserver-builder', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-incubator/ip-masq-agent', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-incubator/metrics-server', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-incubator/kube-arbitrator', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-incubator/descheduler', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-incubator/cluster-proportional-vertical-autoscaler', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-csi/csi-test', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-csi/external-attacher', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-csi/external-provisioner', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-csi/drivers', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-csi/driver-registrar', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-csi/docs', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-csi/kubernetes-csi.github.io', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-csi/livenessprobe', codehost: CodeHosts.GITHUB },
        { name: 'kubernetes-csi/external-snapshotter', codehost: CodeHosts.GITHUB },
        { name: 'vitessio/vitess', codehost: CodeHosts.GITHUB },
        { name: 'google/gvisor', codehost: CodeHosts.GITHUB },
        { name: 'bcicen/ctop', codehost: CodeHosts.GITHUB },
        { name: 'gizak/termui', codehost: CodeHosts.GITHUB },
        { name: 'go-kratos/kratos', codehost: CodeHosts.GITHUB },
        { name: 'uber-go/za', codehost: CodeHosts.GITHUB },
        { name: 'robcalcroft/react-use-lazy-load-image', codehost: CodeHosts.GITHUB },
        { name: 'intercaetera/react-use-message-bar', codehost: CodeHosts.GITHUB },
        { name: 'wowlusitong/react-use-modal', codehost: CodeHosts.GITHUB },
        { name: 'zhangkaiyulw/react-use-path', codehost: CodeHosts.GITHUB },
        { name: 'neo/react-use-scroll-position', codehost: CodeHosts.GITHUB },
        { name: 'lessmess-dev/react-use-trigger', codehost: CodeHosts.GITHUB },
        { name: 'perlin-network/react-use-wavelet', codehost: CodeHosts.GITHUB },
        { name: 'streamich/react-use', codehost: CodeHosts.GITHUB },
        { name: 'GeDiez/react-use-formless', codehost: CodeHosts.GITHUB },
        { name: 'venil7/react-usemiddleware', codehost: CodeHosts.GITHUB },
        { name: 'alex-cory/react-useportal', codehost: CodeHosts.GITHUB },
        { name: 'vardius/react-user-media', codehost: CodeHosts.GITHUB },
        { name: 'f/react-wait', codehost: CodeHosts.GITHUB },
        { name: 'AvraamMavridis/react-window-communication-hook', codehost: CodeHosts.GITHUB },
        { name: 'yesmeck/react-with-hooks', codehost: CodeHosts.GITHUB },
        { name: 'mfrachet/reaktion', codehost: CodeHosts.GITHUB },
        { name: 'iusehooks/redhooks', codehost: CodeHosts.GITHUB },
        { name: 'ianobermiller/redux-react-hook', codehost: CodeHosts.GITHUB },
        { name: 'regionjs/region-core', codehost: CodeHosts.GITHUB },
        { name: 'imbhargav5/rehooks-visibility-sensor', codehost: CodeHosts.GITHUB },
        { name: 'pedronasser/resynced', codehost: CodeHosts.GITHUB },
        { name: 'brn/rrh', codehost: CodeHosts.GITHUB },
        { name: 'LeetCode-OpenSource/rxjs-hooks', codehost: CodeHosts.GITHUB },
        { name: 'dejorrit/scroll-data-hook', codehost: CodeHosts.GITHUB },
        { name: 'style-hook/style-hook', codehost: CodeHosts.GITHUB },
        { name: 'vercel/swr', codehost: CodeHosts.GITHUB },
        { name: 'jaredpalmer/the-platform', codehost: CodeHosts.GITHUB },
        { name: 'danieldelcore/trousers', codehost: CodeHosts.GITHUB },
        { name: 'mauricedb/use-abortable-fetch', codehost: CodeHosts.GITHUB },
        { name: 'awmleer/use-action', codehost: CodeHosts.GITHUB },
        { name: 'awmleer/use-async-memo', codehost: CodeHosts.GITHUB },
        { name: 'lowewenzel/use-autocomplete', codehost: CodeHosts.GITHUB },
        { name: 'sergey-s/use-axios-react', codehost: CodeHosts.GITHUB },
        { name: 'zcallan/use-browser-history', codehost: CodeHosts.GITHUB },
        { name: 'samjbmason/use-cart', codehost: CodeHosts.GITHUB },
        { name: 'CharlesStover/use-clippy', codehost: CodeHosts.GITHUB },
        { name: 'dai-shi/use-context-selector', codehost: CodeHosts.GITHUB },
        { name: 'oktaysenkan/use-countries', codehost: CodeHosts.GITHUB },
        { name: 'xnimorz/use-debounce', codehost: CodeHosts.GITHUB },
        { name: 'sandiiarov/use-deep-compare', codehost: CodeHosts.GITHUB },
        { name: 'kentcdodds/use-deep-compare-effect', codehost: CodeHosts.GITHUB },
        { name: 'gregnb/use-detect-print', codehost: CodeHosts.GITHUB },
        { name: 'CharlesStover/use-dimensions', codehost: CodeHosts.GITHUB },
        { name: 'zattoo/use-double-click', codehost: CodeHosts.GITHUB },
        { name: 'sandiiarov/use-events', codehost: CodeHosts.GITHUB },
        { name: 'CharlesStover/use-force-update', codehost: CodeHosts.GITHUB },
        { name: 'sandiiarov/use-hotkeys', codehost: CodeHosts.GITHUB },
        { name: 'therealparmesh/use-hovering', codehost: CodeHosts.GITHUB },
        { name: 'ava/use-http', codehost: CodeHosts.GITHUB },
        { name: 'immerjs/use-immer', codehost: CodeHosts.GITHUB },
        { name: 'immerjs/immer', codehost: CodeHosts.GITHUB },
        { name: 'neighborhood999/use-input-file', codehost: CodeHosts.GITHUB },
        { name: 'helderburato/use-is-mounted-ref', codehost: CodeHosts.GITHUB },
        { name: 'davidicus/use-lang-direction', codehost: CodeHosts.GITHUB },
        { name: 'streamich/use-media', codehost: CodeHosts.GITHUB },
        { name: 'dimitrinicolas/use-mouse-action', codehost: CodeHosts.GITHUB },
        { name: 'jschloer/use-multiselect', codehost: CodeHosts.GITHUB },
        { name: 'wellyshen/use-places-autocomplete', codehost: CodeHosts.GITHUB },
        { name: 'sandiiarov/use-popper', codehost: CodeHosts.GITHUB },
        { name: 'alex-cory/use-react-modal', codehost: CodeHosts.GITHUB },
        { name: 'CharlesStover/use-react-router', codehost: CodeHosts.GITHUB },
        { name: 'tedstoychev/use-reactive-state', codehost: CodeHosts.GITHUB },
        { name: 'dai-shi/use-reducer-async', codehost: CodeHosts.GITHUB },
        { name: 'flepretre/use-redux', codehost: CodeHosts.GITHUB },
        { name: 'tudorgergely/use-scroll-to-bottom', codehost: CodeHosts.GITHUB },
        { name: 'sandiiarov/use-simple-undo', codehost: CodeHosts.GITHUB },
        { name: 'mfrachet/use-socketio', codehost: CodeHosts.GITHUB },
        { name: 'iamgyz/use-socket.io-client', codehost: CodeHosts.GITHUB },
        { name: 'kmoskwiak/useSSE', codehost: CodeHosts.GITHUB },
        { name: 'alex-cory/use-ssr', codehost: CodeHosts.GITHUB },
        { name: 'haydn/use-state-snapshots', codehost: CodeHosts.GITHUB },
        { name: 'philipp-spiess/use-substate', codehost: CodeHosts.GITHUB },
        { name: 'octet-stream/use-suspender', codehost: CodeHosts.GITHUB },
        { name: 'streamich/use-t', codehost: CodeHosts.GITHUB },
        { name: 'homerchen19/use-undo', codehost: CodeHosts.GITHUB },
        { name: 'donavon/use-dark-mode', codehost: CodeHosts.GITHUB },
        { name: 'KATT/use-is-typing', codehost: CodeHosts.GITHUB },
        { name: 'pranesh239/use-key-capture', codehost: CodeHosts.GITHUB },
        { name: 'tranbathanhtung/usePosition', codehost: CodeHosts.GITHUB },
        { name: 'Tweries/useReducerWithLocalStorage', codehost: CodeHosts.GITHUB },
        { name: 'pankod/react-hooks-screen-type', codehost: CodeHosts.GITHUB },
        { name: 'Purii/react-use-scrollspy', codehost: CodeHosts.GITHUB },
        { name: 'JCofman/react-hook-use-service-worker', codehost: CodeHosts.GITHUB },
        { name: 'bboydflo/use-value-after', codehost: CodeHosts.GITHUB },
        { name: 'wednesday-solutions/react-screentype-hoo', codehost: CodeHosts.GITHUB },
    ],
    description:
        'Search the trending and most starred Kubernetes repositories on GitHub. Explore with search examples below.',
    examples: [
        {
            title:
                'Use a ReplicationController configuration to ensure specified number of pod replicas are running at any one time:',
            exampleQuery: (
                <>
                    <span className="repogroup-page__keyword-text">file:</span>pod.yaml{' '}
                    <span className="repogroup-page__keyword-text">content:</span>"kind: ReplicationController"
                </>
            ),
            rawQuery: 'file:pod.yaml content:"kind: ReplicationController"',
            patternType: SearchPatternType.literal,
        },
        {
            title: 'Look for outdated `apiVersions` of admission webhooks:',
            exampleQuery: (
                <>
                    <span className="repogroup-page__keyword-text">content:</span>"apiVersion:
                    admissionregistration.k8s.io/v1beta1"
                </>
            ),
            description: `This apiVersion has been deprecated in favor of "admissionregistration.k8s.io/v1".
            You can read more about this at https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/`,
            rawQuery: 'content:"apiVersion: admissionregistration.k8s.io/v1beta1"',
            patternType: SearchPatternType.literal,
        },
        {
            title: 'Find Prometheus usage in YAML files:',
            exampleQuery: (
                <>
                    <span className="repogroup-page__keyword-text">lang:</span>yaml prom/prometheus
                </>
            ),
            rawQuery: 'lang:yaml prom/prometheus',
            patternType: SearchPatternType.literal,
        },
        {
            title: 'Search for examples of the sidecar pattern in Go:',
            exampleQuery: (
                <>
                    <span className="repogroup-page__keyword-text">lang:</span>go sidecar
                </>
            ),
            rawQuery: 'lang:go sidecar',
            patternType: SearchPatternType.literal,
        },
        {
            title: 'Browse diffs for recent code changes in the community:',
            exampleQuery: (
                <>
                    <span className="repogroup-page__keyword-text">type:</span>diff{' '}
                    <span className="repogroup-page__keyword-text">after:</span>"1 week ago"
                </>
            ),
            rawQuery: 'type:diff after:"1 week ago"',
            patternType: SearchPatternType.literal,
        },
    ],
    homepageDescription: 'Search within the Kubernetes community.',
    homepageIcon: 'https://code.benco.io/icon-collection/logos/kubernetes.svg',
}
