import { CodeHosts, RepogroupMetadata } from './types'

export const reactHooks: RepogroupMetadata = {
    title: 'React Hooks',
    name: 'react-hooks',
    url: '/react-hooks',
    repositories: [
         { name: "github.com/reactjs/rfcs", codehost: CodeHosts.GITHUB },
         { name: "github.com/juliettepretot/hook-into-props", codehost: CodeHosts.GITHUB },
         { name: "github.com/salvoravida/react-universal-hooks", codehost: CodeHosts.GITHUB },
         { name: "github.com/antoinejaussoin/jooks", codehost: CodeHosts.GITHUB },
         { name: "github.com/alibaba/hooks", codehost: CodeHosts.GITHUB },
         { name: "github.com/stevenpersia/captain-hook", codehost: CodeHosts.GITHUB },
         { name: "github.com/chrisjpatty/crooks", codehost: CodeHosts.GITHUB },
         { name: "github.com/latviancoder/hooks-by-example", codehost: CodeHosts.GITHUB },
         { name: "github.com/craig1123/react-recipes", codehost: CodeHosts.GITHUB },
         { name: "github.com/ant-design/sunflower", codehost: CodeHosts.GITHUB },
         { name: "github.com/21kb/react-hooks", codehost: CodeHosts.GITHUB },
         { name: "github.com/bdbch/react-devto", codehost: CodeHosts.GITHUB },
         { name: "github.com/bdbch/react-github", codehost: CodeHosts.GITHUB },
         { name: "github.com/bdbch/react-localstorage", codehost: CodeHosts.GITHUB },
         { name: "github.com/elgorditosalsero/react-gtm-hook", codehost: CodeHosts.GITHUB },
         { name: "github.com/avkonst/hookstate", codehost: CodeHosts.GITHUB },
         { name: "github.com/zhixiaoqiang/react-request-hook", codehost: CodeHosts.GITHUB },
         { name: "github.com/kevinwolfdev/formal", codehost: CodeHosts.GITHUB },
         { name: "github.com/alewin/useWorker", codehost: CodeHosts.GITHUB },
         { name: "github.com/MarvelSQ/use-properties-hook", codehost: CodeHosts.GITHUB },
         { name: "github.com/rehooks/component-size", codehost: CodeHosts.GITHUB },
         { name: "github.com/rehooks/document-title", codehost: CodeHosts.GITHUB },
         { name: "github.com/rehooks/document-visibility", codehost: CodeHosts.GITHUB },
         { name: "github.com/rehooks/input-value", codehost: CodeHosts.GITHUB },
         { name: "github.com/rehooks/local-storage", codehost: CodeHosts.GITHUB },
         { name: "github.com/rehooks/network-status", codehost: CodeHosts.GITHUB },
         { name: "github.com/rehooks/online-status", codehost: CodeHosts.GITHUB },
         { name: "github.com/rehooks/window-scroll-position", codehost: CodeHosts.GITHUB },
         { name: "github.com/rehooks/window-size", codehost: CodeHosts.GITHUB },
         { name: "github.com/react-rekindle/use-request", codehost: CodeHosts.GITHUB },
         { name: "github.com/staltz/use-profunctor-state", codehost: CodeHosts.GITHUB },
         { name: "github.com/withvoid/melting-pot", codehost: CodeHosts.GITHUB },
         { name: "github.com/diegohaz/constate", codehost: CodeHosts.GITHUB },
         { name: "github.com/fodau/conuse", codehost: CodeHosts.GITHUB },
         { name: "github.com/ctrlplusb/easy-peasy", codehost: CodeHosts.GITHUB },
         { name: "github.com/CharlesStover/fetch-suspense", codehost: CodeHosts.GITHUB },
         { name: "github.com/nearform/graphql-hooks", codehost: CodeHosts.GITHUB },
         { name: "github.com/mobxjs/mobx-react-lite", codehost: CodeHosts.GITHUB },
         { name: "github.com/upmostly/modali", codehost: CodeHosts.GITHUB },
         { name: "github.com/momentechnologies/moment-hooks", codehost: CodeHosts.GITHUB },
         { name: "github.com/daniel-dx/nice-hooks", codehost: CodeHosts.GITHUB },
         { name: "github.com/aiven715/promise-hook", codehost: CodeHosts.GITHUB },
         { name: "github.com/dai-shi/reactive-react-redux", codehost: CodeHosts.GITHUB },
         { name: "github.com/slorber/react-async-hook", codehost: CodeHosts.GITHUB },
         { name: "github.com/megazazik/react-cached-callback", codehost: CodeHosts.GITHUB },
         { name: "github.com/megazazik/react-context-refs", codehost: CodeHosts.GITHUB },
         { name: "github.com/wellyshen/react-cool-dimensions", codehost: CodeHosts.GITHUB },
         { name: "github.com/wellyshen/react-cool-onclickoutside", codehost: CodeHosts.GITHUB },
         { name: "github.com/wellyshen/react-cool-portal", codehost: CodeHosts.GITHUB },
         { name: "github.com/andy9775/react-declare-form", codehost: CodeHosts.GITHUB },
         { name: "github.com/yeskunall/react-dom-status-hook", codehost: CodeHosts.GITHUB },
         { name: "github.com/shiningjason/react-enhanced-reducer-hook", codehost: CodeHosts.GITHUB },
         { name: "github.com/ilyalesik/react-fetch-hook", codehost: CodeHosts.GITHUB },
         { name: "github.com/csfrequency/react-firebase-hooks", codehost: CodeHosts.GITHUB },
         { name: "github.com/ckedwards/react-form-stateful", codehost: CodeHosts.GITHUB },
         { name: "github.com/kitze/react-hanger", codehost: CodeHosts.GITHUB },
         { name: "github.com/mkosir/react-hook-mighty-mouse", codehost: CodeHosts.GITHUB },
         { name: "github.com/zakariaharti/react-hookedup", codehost: CodeHosts.GITHUB },
         { name: "github.com/ytiurin/react-hook-layout", codehost: CodeHosts.GITHUB },
         { name: "github.com/dai-shi/react-hooks-async", codehost: CodeHosts.GITHUB },
         { name: "github.com/dai-shi/react-hooks-global-state", codehost: CodeHosts.GITHUB },
         { name: "github.com/use-hooks/react-hooks-image-size", codehost: CodeHosts.GITHUB },
         { name: "github.com/beizhedenglong/react-hooks-lib", codehost: CodeHosts.GITHUB },
         { name: "github.com/kmkzt/react-hooks-svgdrawing", codehost: CodeHosts.GITHUB },
         { name: "github.com/shibe97/react-hooks-use-modal", codehost: CodeHosts.GITHUB },
         { name: "github.com/kmkzt/react-hooks-visible", codehost: CodeHosts.GITHUB },
         { name: "github.com/dai-shi/react-hooks-worker", codehost: CodeHosts.GITHUB },
         { name: "github.com/JohannesKlauss/react-hotkeys-hook", codehost: CodeHosts.GITHUB },
         { name: "github.com/sin/react-immer-hooks", codehost: CodeHosts.GITHUB },
         { name: "github.com/marceloadsj/react-indicative-hooks", codehost: CodeHosts.GITHUB },
         { name: "github.com/AvraamMavridis/react-intersection-visible-hook", codehost: CodeHosts.GITHUB },
         { name: "github.com/lessmess-dev/react-media-hook", codehost: CodeHosts.GITHUB },
         { name: "github.com/lordgiotto/react-metatags-hook", codehost: CodeHosts.GITHUB },
         { name: "github.com/mamal72/react-optimistic-ui-hook", codehost: CodeHosts.GITHUB },
         { name: "github.com/RyanFitzgerald/react-page-name", codehost: CodeHosts.GITHUB },
         { name: "github.com/vardius/react-peer-data", codehost: CodeHosts.GITHUB },
         { name: "github.com/dispix/react-pirate", codehost: CodeHosts.GITHUB },
         { name: "github.com/kalcifer/react-powerhooks", codehost: CodeHosts.GITHUB },
         { name: "github.com/moxystudio/react-promiseful", codehost: CodeHosts.GITHUB },
         { name: "github.com/hupe1980/react-recaptcha-hook", codehost: CodeHosts.GITHUB },
         { name: "github.com/schettino/react-request-hook", codehost: CodeHosts.GITHUB },
         { name: "github.com/inmagik/react-rocketjump", codehost: CodeHosts.GITHUB },
         { name: "github.com/hupe1980/react-script-hook", codehost: CodeHosts.GITHUB },
         { name: "github.com/Andarist/react-selector-hooks", codehost: CodeHosts.GITHUB },
         { name: "github.com/MikeyParton/react-speech-kit", codehost: CodeHosts.GITHUB },
         { name: "github.com/mcclayton/react-state-patterns", codehost: CodeHosts.GITHUB },
         { name: "github.com/FormidableLabs/react-swipeable", codehost: CodeHosts.GITHUB },
         { name: "github.com/dai-shi/react-tracked", codehost: CodeHosts.GITHUB },
         { name: "github.com/j-a-y-h/react-uniformed", codehost: CodeHosts.GITHUB },
         { name: "github.com/RyanRoll/react-use-api", codehost: CodeHosts.GITHUB },
         { name: "github.com/gregnb/react-use-calendar", codehost: CodeHosts.GITHUB },
         { name: "github.com/danoc/react-use-clipboard", codehost: CodeHosts.GITHUB },
         { name: "github.com/smmoosavi/react-use-data-loader", codehost: CodeHosts.GITHUB },
         { name: "github.com/JohannesKlauss/react-use-fetch-factory", codehost: CodeHosts.GITHUB },
         { name: "github.com/grug/react-use-fetch-with-redux", codehost: CodeHosts.GITHUB },
         { name: "github.com/wsmd/react-use-form-state", codehost: CodeHosts.GITHUB },
         { name: "github.com/Yaska/react-use-id-hook", codehost: CodeHosts.GITHUB },
         { name: "github.com/kigiri/react-use-idb", codehost: CodeHosts.GITHUB },
         { name: "github.com/CurationCorp/react-use-infinite-loader", codehost: CodeHosts.GITHUB },
         { name: "github.com/robcalcroft/react-use-input", codehost: CodeHosts.GITHUB },
         { name: "github.com/robcalcroft/react-use-lazy-load-image", codehost: CodeHosts.GITHUB },
         { name: "github.com/intercaetera/react-use-message-bar", codehost: CodeHosts.GITHUB },
         { name: "github.com/wowlusitong/react-use-modal", codehost: CodeHosts.GITHUB },
         { name: "github.com/zhangkaiyulw/react-use-path", codehost: CodeHosts.GITHUB },
         { name: "github.com/neo/react-use-scroll-position", codehost: CodeHosts.GITHUB },
         { name: "github.com/lessmess-dev/react-use-trigger", codehost: CodeHosts.GITHUB },
         { name: "github.com/perlin-network/react-use-wavelet", codehost: CodeHosts.GITHUB },
         { name: "github.com/streamich/react-use", codehost: CodeHosts.GITHUB },
         { name: "github.com/GeDiez/react-use-formless", codehost: CodeHosts.GITHUB },
         { name: "github.com/venil7/react-usemiddleware", codehost: CodeHosts.GITHUB },
         { name: "github.com/alex-cory/react-useportal", codehost: CodeHosts.GITHUB },
         { name: "github.com/vardius/react-user-media", codehost: CodeHosts.GITHUB },
         { name: "github.com/f/react-wait", codehost: CodeHosts.GITHUB },
         { name: "github.com/AvraamMavridis/react-window-communication-hook", codehost: CodeHosts.GITHUB },
         { name: "github.com/yesmeck/react-with-hooks", codehost: CodeHosts.GITHUB },
         { name: "github.com/mfrachet/reaktion", codehost: CodeHosts.GITHUB },
         { name: "github.com/iusehooks/redhooks", codehost: CodeHosts.GITHUB },
         { name: "github.com/ianobermiller/redux-react-hook", codehost: CodeHosts.GITHUB },
         { name: "github.com/regionjs/region-core", codehost: CodeHosts.GITHUB },
         { name: "github.com/imbhargav5/rehooks-visibility-sensor", codehost: CodeHosts.GITHUB },
         { name: "github.com/pedronasser/resynced", codehost: CodeHosts.GITHUB },
         { name: "github.com/brn/rrh", codehost: CodeHosts.GITHUB },
         { name: "github.com/LeetCode-OpenSource/rxjs-hooks", codehost: CodeHosts.GITHUB },
         { name: "github.com/dejorrit/scroll-data-hook", codehost: CodeHosts.GITHUB },
         { name: "github.com/style-hook/style-hook", codehost: CodeHosts.GITHUB },
         { name: "github.com/vercel/swr", codehost: CodeHosts.GITHUB },
         { name: "github.com/jaredpalmer/the-platform", codehost: CodeHosts.GITHUB },
         { name: "github.com/danieldelcore/trousers", codehost: CodeHosts.GITHUB },
         { name: "github.com/mauricedb/use-abortable-fetch", codehost: CodeHosts.GITHUB },
         { name: "github.com/awmleer/use-action", codehost: CodeHosts.GITHUB },
         { name: "github.com/awmleer/use-async-memo", codehost: CodeHosts.GITHUB },
         { name: "github.com/lowewenzel/use-autocomplete", codehost: CodeHosts.GITHUB },
         { name: "github.com/sergey-s/use-axios-react", codehost: CodeHosts.GITHUB },
         { name: "github.com/zcallan/use-browser-history", codehost: CodeHosts.GITHUB },
         { name: "github.com/samjbmason/use-cart", codehost: CodeHosts.GITHUB },
         { name: "github.com/CharlesStover/use-clippy", codehost: CodeHosts.GITHUB },
         { name: "github.com/dai-shi/use-context-selector", codehost: CodeHosts.GITHUB },
         { name: "github.com/oktaysenkan/use-countries", codehost: CodeHosts.GITHUB },
         { name: "github.com/xnimorz/use-debounce", codehost: CodeHosts.GITHUB },
         { name: "github.com/sandiiarov/use-deep-compare", codehost: CodeHosts.GITHUB },
         { name: "github.com/kentcdodds/use-deep-compare-effect", codehost: CodeHosts.GITHUB },
         { name: "github.com/gregnb/use-detect-print", codehost: CodeHosts.GITHUB },
         { name: "github.com/CharlesStover/use-dimensions", codehost: CodeHosts.GITHUB },
         { name: "github.com/zattoo/use-double-click", codehost: CodeHosts.GITHUB },
         { name: "github.com/sandiiarov/use-events", codehost: CodeHosts.GITHUB },
         { name: "github.com/CharlesStover/use-force-update", codehost: CodeHosts.GITHUB },
         { name: "github.com/sandiiarov/use-hotkeys", codehost: CodeHosts.GITHUB },
         { name: "github.com/therealparmesh/use-hovering", codehost: CodeHosts.GITHUB },
         { name: "github.com/ava/use-http", codehost: CodeHosts.GITHUB },
         { name: "github.com/immerjs/use-immer", codehost: CodeHosts.GITHUB },
         { name: "github.com/immerjs/immer", codehost: CodeHosts.GITHUB },
         { name: "github.com/neighborhood999/use-input-file", codehost: CodeHosts.GITHUB },
         { name: "github.com/helderburato/use-is-mounted-ref", codehost: CodeHosts.GITHUB },
         { name: "github.com/davidicus/use-lang-direction", codehost: CodeHosts.GITHUB },
         { name: "github.com/streamich/use-media", codehost: CodeHosts.GITHUB },
         { name: "github.com/dimitrinicolas/use-mouse-action", codehost: CodeHosts.GITHUB },
         { name: "github.com/jschloer/use-multiselect", codehost: CodeHosts.GITHUB },
         { name: "github.com/wellyshen/use-places-autocomplete", codehost: CodeHosts.GITHUB },
         { name: "github.com/sandiiarov/use-popper", codehost: CodeHosts.GITHUB },
         { name: "github.com/alex-cory/use-react-modal", codehost: CodeHosts.GITHUB },
         { name: "github.com/CharlesStover/use-react-router", codehost: CodeHosts.GITHUB },
         { name: "github.com/tedstoychev/use-reactive-state", codehost: CodeHosts.GITHUB },
         { name: "github.com/dai-shi/use-reducer-async", codehost: CodeHosts.GITHUB },
         { name: "github.com/flepretre/use-redux", codehost: CodeHosts.GITHUB },
         { name: "github.com/tudorgergely/use-scroll-to-bottom", codehost: CodeHosts.GITHUB },
         { name: "github.com/sandiiarov/use-simple-undo", codehost: CodeHosts.GITHUB },
         { name: "github.com/mfrachet/use-socketio", codehost: CodeHosts.GITHUB },
         { name: "github.com/iamgyz/use-socket.io-client", codehost: CodeHosts.GITHUB },
         { name: "github.com/kmoskwiak/useSSE", codehost: CodeHosts.GITHUB },
         { name: "github.com/alex-cory/use-ssr", codehost: CodeHosts.GITHUB },
         { name: "github.com/haydn/use-state-snapshots", codehost: CodeHosts.GITHUB },
         { name: "github.com/philipp-spiess/use-substate", codehost: CodeHosts.GITHUB },
         { name: "github.com/octet-stream/use-suspender", codehost: CodeHosts.GITHUB },
         { name: "github.com/streamich/use-t", codehost: CodeHosts.GITHUB },
         { name: "github.com/homerchen19/use-undo", codehost: CodeHosts.GITHUB },
         { name: "github.com/donavon/use-dark-mode", codehost: CodeHosts.GITHUB },
         { name: "github.com/KATT/use-is-typing", codehost: CodeHosts.GITHUB },
         { name: "github.com/pranesh239/use-key-capture", codehost: CodeHosts.GITHUB },
         { name: "github.com/tranbathanhtung/usePosition", codehost: CodeHosts.GITHUB },
         { name: "github.com/Tweries/useReducerWithLocalStorage", codehost: CodeHosts.GITHUB },
         { name: "github.com/pankod/react-hooks-screen-type", codehost: CodeHosts.GITHUB },
         { name: "github.com/Purii/react-use-scrollspy", codehost: CodeHosts.GITHUB },
         { name: "github.com/JCofman/react-hook-use-service-worker", codehost: CodeHosts.GITHUB },
         { name: "github.com/bboydflo/use-value-after", codehost: CodeHosts.GITHUB },
         { name: "github.com/wednesday-solutions/react-screentype-hook", codehost: CodeHosts.GITHUB },
    ],
    description: 'Examples of useState for ReactHooks.',
    examples: [
        {
            title: 'useState imports regex search:',
            exampleQuery: "import [^;]+useState[^;]+ from 'react'",
        },
        {
            title: 'useState with objects as input parameters structural search:',
            exampleQuery: 'useState({:[string]}) <span class="repogroup-page__keyword-text">count:</span>1000',
        },
        {
            title: 'useState with arrays as input parameters structural search:',
            exampleQuery: 'useState([:[string]]) <span class="repogroup-page__keyword-text">count:</span>1000',
        },
        {
            title: 'useState with any type of input parameters structural search:',
            exampleQuery: 'useState(:[string]) <span class="repogroup-page__keyword-text">count:</span>1000',
        },
        {
            title: 'useState with any type of input parameters structural search for only typescript files:',
            exampleQuery:
                'useState(:[string]) <span class="repogroup-page__keyword-text">count:</span>1000 <span class="repogroup-page__keyword-text">lang:</span>typescript',
        },
        {
            title: 'useState with exactly two input params for structural search, should return a lot fewer results:',
            exampleQuery: 'useState([:[1.], :[2.]]) <span class="repogroup-page__keyword-text">count:</span>1000',
        },
        {
            title: 'useState with two or more params in a specific file (need better eg here) with structural search:',
            exampleQuery:
                'useState([:[1], :[2]]) <span class="repogroup-page__keyword-text">count:</span>1000 <span class="repogroup-page__keyword-text">file:</span>docs/src/pages/components/transfer-list/TransferList.js',
        },
    ],
    homepageDescription: 'Examples of useState for ReactHooks.',
    homepageIcon: 'https://cdn4.iconfinder.com/data/icons/logos-3/600/React.js_logo-512.png',
}
