steps:
  - id: 'download-sourcegraph'
    name: 'gcr.io/cloud-builders/curl'
    entrypoint: /bin/bash
    args:
      - -c
      - |
        set -euxo pipefail &&
        mkdir sourcegraph &&
        curl -L https://github.com/sourcegraph/sourcegraph/archive/${_COMMIT_SHA}.tar.gz | tar xz -C sourcegraph --strip-components 1

  - id: 'docker-build'
    name: 'gcr.io/kaniko-project/executor:latest'
    dir: 'sourcegraph'
    args:
      - '--dockerfile=cmd/server/Dockerfile'
      - '--destination=${_IMAGE}'
      - '--context=dir://.'

      - '--cache=true'
      - '--cache-ttl=6h'

      - '--build-arg'
      - 'COMMIT_SHA=${_COMMIT_SHA}'

      - '--build-arg'
      - 'DATE=${_DATE}'

      - '--build-arg'
      - 'VERSION=${_VERSION}'

      - '--build-arg'
      - 'FRONTEND_PKG=${_FRONTEND_PKG}'

      - '--build-arg'
      - 'MANAGEMENT_CONSOLE_PKG=${_MANAGEMENT_CONSOLE_PKG}'

      - '--build-arg'
      - 'REPO_UPDATER_PKG=${_REPO_UPDATER_PKG}'

      - '--build-arg'
      - 'SERVER_PKG=${_SERVER_PKG}'

      - '--build-arg'
      - 'PRE_BUILD_SCRIPT=${_PRE_BUILD_SCRIPT}'

      - '--build-arg'
      - 'CTAGS_VERSION=${_CTAGS_VERSION}'

      - '--build-arg'
      - 'ENTERPRISE=${_ENTERPRISE}'
tags:
  - 'server'
  - '${_COMMIT_SHA}'
options:
  machineType: 'N1_HIGHCPU_32'
timeout: 1200s
substitutions:
  '_IMAGE': 'us.gcr.io/sourcegraph-dev/server:latest'
  '_COMMIT_SHA': 'unknown'
  '_DATE': 'unknown'
  '_VERSION': 'unknown'
  '_FRONTEND_PKG': 'github.com/sourcegraph/sourcegraph/cmd/frontend'
  '_MANAGEMENT_CONSOLE_PKG': 'github.com/sourcegraph/sourcegraph/cmd/management-console'
  '_REPO_UPDATER_PKG': 'github.com/sourcegraph/sourcegraph/cmd/repo-updater'
  '_SERVER_PKG': 'github.com/sourcegraph/sourcegraph/cmd/server'
  '_PRE_BUILD_SCRIPT': 'cmd/server/pre-build.sh'
  '_CTAGS_VERSION': '03f933a96d3ef87adbf9d167462d45ce69577edb'
  '_ENTERPRISE': 'false'
