{
 "title": "Frontend",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Frontend requests to Gitserver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Gitserver requests by duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(src_gitserver_request_duration_seconds_bucket{code=~\"2..\"}[1m])",
     "legendFormat": "≤ {{le}}s"
    }
   ]
  },
  {
   "title": "Gitserver error rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "format": "short",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(src_gitserver_request_duration_seconds_count{code=~\"5..\"}[1m])) / sum(rate(src_gitserver_request_duration_seconds_count[1m]))",
     "legendFormat": "% of 5.. responses"
    },
    {
     "expr": "sum(rate(src_gitserver_request_duration_seconds_count{code=~\"4..\"}[1m])) / sum(rate(src_gitserver_request_duration_seconds_count[1m]))",
     "legendFormat": "% of 4.. responses"
    }
   ]
  },
  {
   "title": "Gitserver request duration percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "format": "short",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(src_gitserver_request_duration_seconds_bucket{code=~\"2..\"}[1m]))",
     "legendFormat": "0.5p"
    },
    {
     "expr": "histogram_quantile(0.9, rate(src_gitserver_request_duration_seconds_bucket{code=~\"2..\"}[1m]))",
     "legendFormat": "0.9p"
    },
    {
     "expr": "histogram_quantile(0.99, rate(src_gitserver_request_duration_seconds_bucket{code=~\"2..\"}[1m]))",
     "legendFormat": "0.99p"
    }
   ]
  },
  {
   "title": "Frontend requests to Repoupdater",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  {
   "title": "Number of Repoupdater requests by duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(src_repoupdater_request_duration_seconds_bucket{code=~\"2..\"}[1m])",
     "legendFormat": "≤ {{le}}s"
    }
   ]
  },
  {
   "title": "Repoupdater error rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "format": "short",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(src_repoupdater_request_duration_seconds_count{code=~\"5..\"}[1m])) / sum(rate(src_repoupdater_request_duration_seconds_count[1m]))",
     "legendFormat": "% of 5.. responses"
    },
    {
     "expr": "sum(rate(src_repoupdater_request_duration_seconds_count{code=~\"4..\"}[1m])) / sum(rate(src_repoupdater_request_duration_seconds_count[1m]))",
     "legendFormat": "% of 4.. responses"
    }
   ]
  },
  {
   "title": "Repoupdater request duration percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "format": "short",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(src_repoupdater_request_duration_seconds_bucket{code=~\"2..\"}[1m]))",
     "legendFormat": "0.5p"
    },
    {
     "expr": "histogram_quantile(0.9, rate(src_repoupdater_request_duration_seconds_bucket{code=~\"2..\"}[1m]))",
     "legendFormat": "0.9p"
    },
    {
     "expr": "histogram_quantile(0.99, rate(src_repoupdater_request_duration_seconds_bucket{code=~\"2..\"}[1m]))",
     "legendFormat": "0.99p"
    }
   ]
  }
 ]
}