{
 "title": "HTTP",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "percentile", "query": ".90, .95, .98, .99" }
  ]
 },
 "panels": [
  {
   "title": "QPS by Status Code [rate-5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(job:src_http_request_count:rate5m, \"c\", \"${1}00s\", \"code\", \"([0-9]).*\")) by (c)",
     "legendFormat": "{{c}}"
    }
   ]
  },
  {
   "title": "QPS by Route [rate-5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(route:src_http_request_count:rate5m{route=~\"(xlang|graphql|page.def.landing|page.home|repo.resolve-rev|repo.create|repo.shield|lsp)\"}) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "P$percentile Request Duration [rate-5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile, route:src_http_request_duration_seconds_bucket:rate5m)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "P$percentile Overall Route Duration [rate-5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(route:src_http_request_duration_seconds_bucket:rate5m) by (le, route))",
     "legendFormat": "{{route}}"
    }
   ]
  }
 ]
}