{
 "title": "LSIF",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "HTTP uploads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of server requests by duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(lsif_http_upload_request_duration_seconds_bucket{status_code=~\"2..\"}[1m])",
     "legendFormat": "≤ {{le}}s"
    }
   ]
  },
  {
   "title": "Server error rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "format": "short",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(lsif_http_upload_request_duration_seconds_count{status_code=~\"5..\"}[1m])) / sum(rate(lsif_http_upload_request_duration_seconds_count[1m]))",
     "legendFormat": "% of 5.. responses"
    },
    {
     "expr": "sum(rate(lsif_http_upload_request_duration_seconds_count{status_code=~\"4..\"}[1m])) / sum(rate(lsif_http_upload_request_duration_seconds_count[1m]))",
     "legendFormat": "% of 4.. responses"
    }
   ]
  },
  {
   "title": "Server request duration percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "format": "short",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(lsif_http_upload_request_duration_seconds_bucket{status_code=~\"2..\"}[1m]))",
     "legendFormat": "0.5p"
    },
    {
     "expr": "histogram_quantile(0.9, rate(lsif_http_upload_request_duration_seconds_bucket{status_code=~\"2..\"}[1m]))",
     "legendFormat": "0.9p"
    },
    {
     "expr": "histogram_quantile(0.99, rate(lsif_http_upload_request_duration_seconds_bucket{status_code=~\"2..\"}[1m]))",
     "legendFormat": "0.99p"
    }
   ]
  },
  { "title": "HTTP queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Number of server requests by duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(lsif_http_query_request_duration_seconds_bucket{status_code=~\"2..\"}[1m])",
     "legendFormat": "≤ {{le}}s"
    }
   ]
  },
  {
   "title": "Server error rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "format": "short",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(lsif_http_query_request_duration_seconds_count{status_code=~\"5..\"}[1m])) / sum(rate(lsif_http_query_request_duration_seconds_count[1m]))",
     "legendFormat": "% of 5.. responses"
    },
    {
     "expr": "sum(rate(lsif_http_query_request_duration_seconds_count{status_code=~\"4..\"}[1m])) / sum(rate(lsif_http_query_request_duration_seconds_count[1m]))",
     "legendFormat": "% of 4.. responses"
    }
   ]
  },
  {
   "title": "Server request duration percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "format": "short",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(lsif_http_query_request_duration_seconds_bucket{status_code=~\"2..\"}[1m]))",
     "legendFormat": "0.5p"
    },
    {
     "expr": "histogram_quantile(0.9, rate(lsif_http_query_request_duration_seconds_bucket{status_code=~\"2..\"}[1m]))",
     "legendFormat": "0.9p"
    },
    {
     "expr": "histogram_quantile(0.99, rate(lsif_http_query_request_duration_seconds_bucket{status_code=~\"2..\"}[1m]))",
     "legendFormat": "0.99p"
    }
   ]
  },
  { "title": "Queue and job stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Queue size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "lsif_queue_size", "legendFormat": "queue size" }
   ]
  },
  {
   "title": "Job events",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 15 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(lsif_job_events_total{type=\"success\"}[1m])) by (class)",
     "legendFormat": "{{class}} success"
    },
    {
     "expr": "sum(rate(lsif_job_events_total{type=\"failure\"}[1m])) by (class)",
     "legendFormat": "{{class}} failure"
    }
   ]
  },
  {
   "title": "Number of convert jobs by duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(lsif_job_duration_seconds_bucket{class=\"convert\"}[1m])",
     "legendFormat": "≤ {{le}}s"
    }
   ]
  },
  {
   "title": "Convert jobs duration percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
   "format": "short",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(lsif_job_duration_seconds_bucket{class=\"convert\"}[1m]))",
     "legendFormat": "0.5p"
    },
    {
     "expr": "histogram_quantile(0.9, rate(lsif_job_duration_seconds_bucket{class=\"convert\"}[1m]))",
     "legendFormat": "0.9p"
    },
    {
     "expr": "histogram_quantile(0.99, rate(lsif_job_duration_seconds_bucket{class=\"convert\"}[1m]))",
     "legendFormat": "0.99p"
    }
   ]
  },
  { "title": "Database queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Number of database queries by duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(lsif_database_query_duration_seconds_bucket[1m])",
     "legendFormat": "≤ {{le}}s"
    }
   ]
  },
  {
   "title": "Database query error rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
   "format": "short",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(lsif_database_query_errors_total[1m]) / rate(lsif_database_query_duration_seconds_count[1m])",
     "legendFormat": "% of failing operations"
    }
   ]
  },
  {
   "title": "Database query duration percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
   "format": "short",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(lsif_database_query_duration_seconds_bucket[1m]))",
     "legendFormat": "0.5p"
    },
    {
     "expr": "histogram_quantile(0.9, rate(lsif_database_query_duration_seconds_bucket[1m]))",
     "legendFormat": "0.9p"
    },
    {
     "expr": "histogram_quantile(0.99, rate(lsif_database_query_duration_seconds_bucket[1m]))",
     "legendFormat": "0.99p"
    }
   ]
  },
  { "title": "Crosss-repo queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Number of xrepo queries by duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(lsif_xrepo_query_duration_seconds_bucket[1m])",
     "legendFormat": "≤ {{le}}s"
    }
   ]
  },
  {
   "title": "Xrepo query error rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
   "format": "short",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(lsif_xrepo_query_errors_total[1m]) / rate(lsif_xrepo_query_duration_seconds_count[1m])",
     "legendFormat": "% of failing operations"
    }
   ]
  },
  {
   "title": "Xrepo query duration percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
   "format": "short",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(lsif_xrepo_query_duration_seconds_bucket[1m]))",
     "legendFormat": "0.5p"
    },
    {
     "expr": "histogram_quantile(0.9, rate(lsif_xrepo_query_duration_seconds_bucket[1m]))",
     "legendFormat": "0.9p"
    },
    {
     "expr": "histogram_quantile(0.99, rate(lsif_xrepo_query_duration_seconds_bucket[1m]))",
     "legendFormat": "0.99p"
    }
   ]
  },
  { "title": "Database insertions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Number of database insertions by duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 36 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(lsif_database_insertion_duration_seconds_bucket[1m])",
     "legendFormat": "≤ {{le}}s"
    }
   ]
  },
  {
   "title": "Database insertion error rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 36 },
   "format": "short",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(lsif_database_insertion_errors_total[1m]) / rate(lsif_database_insertion_duration_seconds_count[1m])",
     "legendFormat": "% of failing operations"
    }
   ]
  },
  {
   "title": "Database query duration percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 36 },
   "format": "short",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(lsif_database_insertion_duration_seconds_bucket[1m]))",
     "legendFormat": "0.5p"
    },
    {
     "expr": "histogram_quantile(0.9, rate(lsif_database_insertion_duration_seconds_bucket[1m]))",
     "legendFormat": "0.9p"
    },
    {
     "expr": "histogram_quantile(0.99, rate(lsif_database_insertion_duration_seconds_bucket[1m]))",
     "legendFormat": "0.99p"
    }
   ]
  },
  { "title": "Crosss-repo insertions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Number of xrepo insertions by duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 43 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(lsif_xrepo_insertion_duration_seconds_bucket[1m])",
     "legendFormat": "≤ {{le}}s"
    }
   ]
  },
  {
   "title": "Xrepo insertion error rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 43 },
   "format": "short",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(lsif_xrepo_insertion_errors_total[1m]) / rate(lsif_xrepo_insertion_duration_seconds_count[1m])",
     "legendFormat": "% of failing operations"
    }
   ]
  },
  {
   "title": "Xrepo insertion duration percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 43 },
   "format": "short",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(lsif_xrepo_insertion_duration_seconds_bucket[1m]))",
     "legendFormat": "0.5p"
    },
    {
     "expr": "histogram_quantile(0.9, rate(lsif_xrepo_insertion_duration_seconds_bucket[1m]))",
     "legendFormat": "0.9p"
    },
    {
     "expr": "histogram_quantile(0.99, rate(lsif_xrepo_insertion_duration_seconds_bucket[1m]))",
     "legendFormat": "0.99p"
    }
   ]
  },
  { "title": "Caches and Filters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Cache utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4.8, "x": 0, "y": 50 },
   "format": "short",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "lsif_connection_cache_size / lsif_connection_cache_capacity",
     "legendFormat": "connection cache utilization"
    },
    {
     "expr": "lsif_document_cache_size / lsif_document_cache_capacity",
     "legendFormat": "document cache utilization"
    },
    {
     "expr": "lsif_result_chunk_cache_size / lsif_result_chunk_cache_capacity",
     "legendFormat": "result chunk cache utilization"
    }
   ]
  },
  {
   "title": "Connection cache events",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4.8, "x": 4.8, "y": 50 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(lsif_connection_cache_events_total{type=\"hit\"}[1m])",
     "legendFormat": "hits"
    },
    {
     "expr": "rate(lsif_connection_cache_events_total{type=\"miss\"}[1m])",
     "legendFormat": "misses"
    },
    {
     "expr": "rate(lsif_connection_cache_events_total{type=\"eviction\"}[1m])",
     "legendFormat": "evictions"
    },
    {
     "expr": "rate(lsif_connection_cache_events_total{type=\"locked-eviction\"}[1m])",
     "legendFormat": "locked entries"
    }
   ]
  },
  {
   "title": "Document cache events",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4.8, "x": 9.6, "y": 50 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(lsif_document_cache_events_total{type=\"hit\"}[1m])",
     "legendFormat": "hits"
    },
    {
     "expr": "rate(lsif_document_cache_events_total{type=\"miss\"}[1m])",
     "legendFormat": "misses"
    },
    {
     "expr": "rate(lsif_document_cache_events_total{type=\"eviction\"}[1m])",
     "legendFormat": "evictions"
    },
    {
     "expr": "rate(lsif_document_cache_events_total{type=\"locked-eviction\"}[1m])",
     "legendFormat": "locked entries"
    }
   ]
  },
  {
   "title": "Result chunk cache events",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4.8, "x": 14.399999999999999, "y": 50 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(lsif_result_chunk_cache_events_total{type=\"hit\"}[1m])",
     "legendFormat": "hits"
    },
    {
     "expr": "rate(lsif_result_chunk_cache_events_total{type=\"miss\"}[1m])",
     "legendFormat": "misses"
    },
    {
     "expr": "rate(lsif_result_chunk_cache_events_total{type=\"eviction\"}[1m])",
     "legendFormat": "evictions"
    },
    {
     "expr": "rate(lsif_result_chunk_cache_events_total{type=\"locked-eviction\"}[1m])",
     "legendFormat": "locked entries"
    }
   ]
  },
  {
   "title": "Bloom filter events",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4.8, "x": 19.2, "y": 50 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(lsif_bloom_filter_events_total{type=\"hit\"}[1m])",
     "legendFormat": "hits"
    },
    {
     "expr": "rate(lsif_bloom_filter_events_total{type=\"miss\"}[1m])",
     "legendFormat": "misses"
    }
   ]
  }
 ]
}