{
 "title": "Repoupdater",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Http handler calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Http handler calls by duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(src_repoupdater_http_handler_duration_seconds_bucket{code=~\"2..\"}[1m])",
     "legendFormat": "≤ {{le}}s"
    }
   ]
  },
  {
   "title": "Http handler error rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "format": "short",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(src_repoupdater_http_handler_duration_seconds_count{code=~\"5..\"}[1m])) / sum(rate(src_repoupdater_http_handler_duration_seconds_count[1m]))",
     "legendFormat": "% of 5.. responses"
    },
    {
     "expr": "sum(rate(src_repoupdater_http_handler_duration_seconds_count{code=~\"4..\"}[1m])) / sum(rate(src_repoupdater_http_handler_duration_seconds_count[1m]))",
     "legendFormat": "% of 4.. responses"
    }
   ]
  },
  {
   "title": "Http handler call duration percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "format": "short",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(src_repoupdater_http_handler_duration_seconds_bucket{code=~\"2..\"}[1m]))",
     "legendFormat": "0.5p"
    },
    {
     "expr": "histogram_quantile(0.9, rate(src_repoupdater_http_handler_duration_seconds_bucket{code=~\"2..\"}[1m]))",
     "legendFormat": "0.9p"
    },
    {
     "expr": "histogram_quantile(0.99, rate(src_repoupdater_http_handler_duration_seconds_bucket{code=~\"2..\"}[1m]))",
     "legendFormat": "0.99p"
    }
   ]
  },
  { "title": "Github requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Number of Github requests by duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(src_github_request_duration_seconds_bucket{code=~\"2..\"}[1m])",
     "legendFormat": "≤ {{le}}s"
    }
   ]
  },
  {
   "title": "Github error rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "format": "short",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(src_github_request_duration_seconds_count{code=~\"5..\"}[1m])) / sum(rate(src_github_request_duration_seconds_count[1m]))",
     "legendFormat": "% of 5.. responses"
    },
    {
     "expr": "sum(rate(src_github_request_duration_seconds_count{code=~\"4..\"}[1m])) / sum(rate(src_github_request_duration_seconds_count[1m]))",
     "legendFormat": "% of 4.. responses"
    }
   ]
  },
  {
   "title": "Github request duration percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "format": "short",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(src_github_request_duration_seconds_bucket{code=~\"2..\"}[1m]))",
     "legendFormat": "0.5p"
    },
    {
     "expr": "histogram_quantile(0.9, rate(src_github_request_duration_seconds_bucket{code=~\"2..\"}[1m]))",
     "legendFormat": "0.9p"
    },
    {
     "expr": "histogram_quantile(0.99, rate(src_github_request_duration_seconds_bucket{code=~\"2..\"}[1m]))",
     "legendFormat": "0.99p"
    }
   ]
  },
  { "title": "Bitbucket requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Number of Bitbucket requests by duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(src_bitbucket_request_duration_seconds_bucket{code=~\"2..\"}[1m])",
     "legendFormat": "≤ {{le}}s"
    }
   ]
  },
  {
   "title": "Bitbucket error rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "format": "short",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(src_bitbucket_request_duration_seconds_count{code=~\"5..\"}[1m])) / sum(rate(src_bitbucket_request_duration_seconds_count[1m]))",
     "legendFormat": "% of 5.. responses"
    },
    {
     "expr": "sum(rate(src_bitbucket_request_duration_seconds_count{code=~\"4..\"}[1m])) / sum(rate(src_bitbucket_request_duration_seconds_count[1m]))",
     "legendFormat": "% of 4.. responses"
    }
   ]
  },
  {
   "title": "Bitbucket request duration percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "format": "short",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(src_bitbucket_request_duration_seconds_bucket{code=~\"2..\"}[1m]))",
     "legendFormat": "0.5p"
    },
    {
     "expr": "histogram_quantile(0.9, rate(src_bitbucket_request_duration_seconds_bucket{code=~\"2..\"}[1m]))",
     "legendFormat": "0.9p"
    },
    {
     "expr": "histogram_quantile(0.99, rate(src_bitbucket_request_duration_seconds_bucket{code=~\"2..\"}[1m]))",
     "legendFormat": "0.99p"
    }
   ]
  },
  { "title": "Gitlab requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Number of Gitlab requests by duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(src_gitlab_request_duration_seconds_bucket{code=~\"2..\"}[1m])",
     "legendFormat": "≤ {{le}}s"
    }
   ]
  },
  {
   "title": "Gitlab error rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
   "format": "short",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(src_gitlab_request_duration_seconds_count{code=~\"5..\"}[1m])) / sum(rate(src_gitlab_request_duration_seconds_count[1m]))",
     "legendFormat": "% of 5.. responses"
    },
    {
     "expr": "sum(rate(src_gitlab_request_duration_seconds_count{code=~\"4..\"}[1m])) / sum(rate(src_gitlab_request_duration_seconds_count[1m]))",
     "legendFormat": "% of 4.. responses"
    }
   ]
  },
  {
   "title": "Gitlab request duration percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
   "format": "short",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(src_gitlab_request_duration_seconds_bucket{code=~\"2..\"}[1m]))",
     "legendFormat": "0.5p"
    },
    {
     "expr": "histogram_quantile(0.9, rate(src_gitlab_request_duration_seconds_bucket{code=~\"2..\"}[1m]))",
     "legendFormat": "0.9p"
    },
    {
     "expr": "histogram_quantile(0.99, rate(src_gitlab_request_duration_seconds_bucket{code=~\"2..\"}[1m]))",
     "legendFormat": "0.99p"
    }
   ]
  }
 ]
}