query GitHistoryQuery($repo: ID!, $revspec: String!, $first: Int, $afterCursor: String, $filePath: String) {
    node(id: $repo) {
        ... on Repository {
            id
            commit(rev: $revspec) {
                id
                ancestors(first: $first, path: $filePath, afterCursor: $afterCursor) {
                    # This is a bit hacky, but by fetching all the data needed by both
                    # the history panel and the commits page we ensure that our custom
                    # Apollo infinitiy scroll cache handling for this field works
                    # correctly. Eventually we should revsisit the use of infinity scroll
                    # on the commits page.
                    ...CommitsPage_GitCommitConnection
                    ...GitHistory_HistoryConnection
                }
            }
        }
    }
}

fragment GitHistory_HistoryConnection on GitCommitConnection {
    ...HistoryPanel_HistoryConnection
    pageInfo {
        hasNextPage
        endCursor
    }
}
