query GitHistoryQuery($repoName: String!, $revspec: String!, $first: Int, $afterCursor: String, $filePath: String) {
    repository(name: $repoName) {
        id
        commit(rev: $revspec) {
            id
            ancestors(first: $first, path: $filePath, afterCursor: $afterCursor) {
                ...GitHistory_HistoryConnection
            }
        }
    }
}

fragment GitHistory_HistoryConnection on GitCommitConnection {
    ...HistoryPanel_HistoryConnection
    pageInfo {
        hasNextPage
        endCursor
    }
}
