query CodyContextFiltersQuery {
    site {
        codyContextFilters(version: V1) {
            raw
        }
    }
}

query GitHistoryQuery($repoName: String!, $revspec: String!, $first: Int, $afterCursor: String, $filePath: String) {
    repository(name: $repoName) {
        id
        commit(rev: $revspec) {
            id
            ancestors(first: $first, path: $filePath, afterCursor: $afterCursor) {
                ...GitHistory_HistoryConnection
            }
        }
    }
}

query LastCommitQuery($repoName: String!, $revspec: String!, $filePath: String!) {
    repository(name: $repoName) {
        lastCommit: commit(rev: $revspec) {
            id
            ancestors(first: 1, path: $filePath) {
                nodes {
                    ...LastCommitFragment
                }
            }
        }
    }
}

fragment GitHistory_HistoryConnection on GitCommitConnection {
    ...HistoryPanel_HistoryConnection
    pageInfo {
        hasNextPage
        endCursor
    }
}

query RepoPage_PreciseCodeIntel(
    $repoName: String!
    $revspec: String!
    $filePath: String!
    $line: Int!
    $character: Int!
    $first: Int
    $afterCursor: String
) {
    repository(name: $repoName) {
        id
        commit(rev: $revspec) {
            id
            blob(path: $filePath) {
                canonicalURL
                lsif {
                    references(line: $line, character: $character, first: $first, after: $afterCursor) {
                        ...RepoPage_ReferencesLocationConnection
                    }
                }
            }
        }
    }
}

fragment RepoPage_ReferencesLocationConnection on LocationConnection {
    ...ReferencePanel_LocationConnection
    pageInfo {
        hasNextPage
        endCursor
    }
}
