{
 "title": "GraphQL Query Latencies",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "DefinitionAndHover",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: DefinitionAndHover\"}[5m])))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: DefinitionAndHover\"}[5m])))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: DefinitionAndHover\"}[5m])))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: DefinitionAndHover\"}[5m])))",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "Ranges",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": " histogram_quantile(0.99, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: Ranges\"}[5m])))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: Ranges\"}[5m])))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: Ranges\"}[5m])))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: Ranges\"}[5m])))",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "References",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: References\"}[5m])))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: References\"}[5m])))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: References\"}[5m])))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: References\"}[5m])))",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "ResolveRev",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: ResolveRev\"}[5m])))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: ResolveRev\"}[5m])))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: ResolveRev\"}[5m])))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: ResolveRev\"}[5m])))",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "FileContent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: FileContent\"}[5m])))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: FileContent\"}[5m])))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: FileContent\"}[5m])))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: FileContent\"}[5m])))",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "ESLintDiagnostics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: ESLintDiagnostics\"}[5m])))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: ESLintDiagnostics\"}[5m])))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: ESLintDiagnostics\"}[5m])))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: ESLintDiagnostics\"}[5m])))",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "GetCommits",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: GetCommits\"}[5m])))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: GetCommits\"}[5m])))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: GetCommits\"}[5m])))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: GetCommits\"}[5m])))",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "GetCommit",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: GetCommitGetCommit\"}[5m])))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: GetCommit\"}[5m])))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: GetCommit\"}[5m])))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: GetCommit\"}[5m])))",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "BlobContent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: BlobContent\"}[5m])))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: BlobContent\"}[5m])))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: BlobContent\"}[5m])))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: BlobContent\"}[5m])))",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "RepositoryComparisonDiff",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: RepositoryComparisonDiff\"}[5m])))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: RepositoryComparisonDiff\"}[5m])))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: RepositoryComparisonDiff\"}[5m])))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: RepositoryComparisonDiff\"}[5m])))",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "HighlightedFile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: HighlightedFile\"}[5m])))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: HighlightedFile\"}[5m])))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: HighlightedFile\"}[5m])))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: HighlightedFile\"}[5m])))",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "FileExternalLinks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: FileExternalLinks\"}[5m])))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: FileExternalLinks\"}[5m])))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: FileExternalLinks\"}[5m])))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: FileExternalLinks\"}[5m])))",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "TreeEntries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: TreeEntries\"}[5m])))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: TreeEntries\"}[5m])))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: TreeEntries\"}[5m])))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: TreeEntries\"}[5m])))",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "TreeCommits",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: TreeCommits\"}[5m])))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: TreeCommits\"}[5m])))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: TreeCommits\"}[5m])))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le)(rate(src_http_request_duration_seconds_bucket{route=\"graphql: TreeCommits\"}[5m])))",
     "legendFormat": "50th percentile"
    }
   ]
  }
 ]
}