# Rules that apply to deployment types with cadvisor (Docker Compose, Pure Docker). These rules
# otherwise yield null values.
groups:
  - name: cadvisor.rules
    rules:
      # The number of CPUs allocated to the container according to the configured Docker / Kubernetes limits.
      - record: cadvisor_container_cpu_limit
        expr: avg by (name)(container_spec_cpu_quota) / avg by (name)(container_spec_cpu_period)

      # Percentage of CPU cores the container consumed on average over a 1m period.
      # For example, if a container has a 4 CPU limit and this metric reports 50%,
      # it means the container consumed 2 cores on average over that 1m period.
      - record: cadvisor_container_cpu_usage_percentage_total
        expr: (avg by (name)(rate(container_cpu_usage_seconds_total[1m])) / cadvisor_container_cpu_limit) * 100.0

      # Percentage of memory usage the container is consuming.
      - record: cadvisor_container_memory_usage_percentage_total
        expr: max by (name)(container_memory_working_set_bytes / container_spec_memory_limit_bytes) * 100.0
