# Note: This file is ran relative to the repo root.
gitserver: gitserver
query-runner: query-runner
repo-updater: repo-updater
searcher: searcher
replacer: replacer
symbols: ./cmd/symbols/build.sh execute
github-proxy: github-proxy
frontend: env CONFIGURATION_MODE=server frontend
watch: ./enterprise/dev/changewatch.sh
nginx: nginx -p . -g 'daemon off;' -c $PWD/dev/nginx.conf 2>&1 | grep -v 'could not open error log file'
web: ENTERPRISE=1 ./node_modules/.bin/gulp --color watch
syntect_server: ./dev/syntect_server
zoekt-indexserver: ./dev/zoekt-wrapper zoekt-sourcegraph-indexserver -sourcegraph_url http://localhost:3090 -index $HOME/.sourcegraph/zoekt/index -interval 1m -listen :6072
zoekt-webserver: ./dev/zoekt-wrapper zoekt-webserver -index $HOME/.sourcegraph/zoekt/index -pprof -rpc -listen :3070
management-console: PROJECT_ROOT=./cmd/management-console TLS_CERT=$HOME/.sourcegraph/management/cert.pem TLS_KEY=$HOME/.sourcegraph/management/key.pem management-console
management-console-web: cd ./cmd/management-console/web && ./serve.sh
keycloak: ./enterprise/dev/auth-provider/keycloak.sh
# jaeger: docker run --name=jaeger --rm -p5775:5775/udp -p6831:6831/udp -p6832:6832/udp -p5778:5778 -p16686:16686 -p14268:14268 jaegertracing/all-in-one:latest
docsite: .bin/docsite -config doc/docsite.json serve -http=localhost:5080
