#
# Docker image for srclib-csharp
#

# Dependencies
FROM microsoft/aspnet:1.0.0-rc1-update1-coreclr
ARG TOOLCHAIN_VERSION

# Install srclib-csharp executable
ENV SRCLIBPATH /srclib
RUN git clone https://github.com/sourcegraph/srclib-csharp /srclib/srclib-csharp
RUN cd /srclib/srclib-csharp && git checkout $TOOLCHAIN_VERSION
RUN cd /srclib/srclib-csharp && dnu restore

# TODO(beyang): fill in once you get Dockerfile from Ildar
