
name: Resources Report
on:
  schedule:
  - cron: '0 9 * * *'
  repository_dispatch:
    types: [ resources-report ]

jobs:
  resources-report:
    if: github.repository == 'sourcegraph/sourcegraph'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up gcp key
      run: |
        echo ${{ secrets.RR_GCP_ACCOUNT_KEY }} | base64 -d > resources-report-credentials.json
    - name: report resources
      uses: ./internal/cmd/resources-report/.
      with:
        args: --aws --gcp --gcp.allowlist "cost-category:build"
      env:
        GOOGLE_APPLICATION_CREDENTIALS: resources-report-credentials.json
        AWS_ACCESS_KEY_ID: ${{ secrets.RR_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.RR_AWS_SECRET_ACCESS_KEY }}
        SLACK_WEBHOOK: ${{ secrets.RR_SLACK_WEBHOOK }}
        SHEET_ID: ${{ secrets.RR_SHEET_ID }}
