name: scip-go
on:
  push:
    paths:
      - '**.go'
      - '**/scip-go.yml'

jobs:
  scip-go:
    # Skip running on forks
    if: github.repository == 'sourcegraph/sourcegraph'
    runs-on: ubuntu-latest
    # Temporarily pin to v0.1.15 as v0.1.16 has a regression
    # https://github.com/sourcegraph/scip-go/issues/119
    container: sourcegraph/scip-go:v0.1.15
    strategy:
      matrix:
        root:
          - ''
          - lib
          - monitoring
          - dev/ci/images
    steps:
      # Setup
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set directory to safe for git
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Get src-cli
        run: |
          curl -L https://sourcegraph.com/.api/src-cli/src_linux_amd64 -o /usr/local/bin/src
          chmod +x /usr/local/bin/src

      - name: Install ASDF
        uses: asdf-vm/actions/setup@v3

      - name: Install matching Go toolchain
        run: |
          asdf plugin add golang
          asdf install golang

      - name: Run scip-go
        working-directory: ${{ matrix.root }}
        run: scip-go --no-animation

      - name: Upload scip-go dump to Dotcom
        working-directory: ${{ matrix.root }}
        run: src code-intel upload -github-token='${{ secrets.GITHUB_TOKEN }}' -no-progress -repo=github.com/sourcegraph/sourcegraph
        env:
          SRC_ENDPOINT: https://sourcegraph.com/
          SRC_ACCESS_TOKEN: ${{ secrets.SRC_ACCESS_TOKEN_DOTCOM }}

      - name: Upload scip-go dump to S2
        working-directory: ${{ matrix.root }}
        run: src code-intel upload -github-token='${{ secrets.GITHUB_TOKEN }}' -no-progress -repo=github.com/sourcegraph/sourcegraph
        env:
          SRC_ENDPOINT: https://sourcegraph.sourcegraph.com/
          SRC_ACCESS_TOKEN: ${{ secrets.SRC_ACCESS_TOKEN_S2 }}

      - name: Upload scip-go dump to Demo
        working-directory: ${{ matrix.root }}
        run: src code-intel upload -github-token='${{ secrets.GITHUB_TOKEN }}' -no-progress -repo=github.com/sourcegraph/sourcegraph
        env:
          SRC_ENDPOINT: https://demo.sourcegraph.com/
          SRC_ACCESS_TOKEN: ${{ secrets.SRC_ACCESS_TOKEN_DEMO }}
